package templates

import (
	"strings"
	"testing"

	"github.com/adams-shaun/gorge/compliance/oraclegen"
)

// TestCharmModeZonesKeepBattlefieldFixtures: a charm mode whose ValidTgts$
// names a battlefield type keeps a battlefield slot even though its
// TargetType$ is Spell, so the committed battlefield scenario (and its
// verdict) is preserved. A mode that names only instant/sorcery or an
// ability stays stack-only. This is the regression that stale-d a declared
// set's verdicts: routing "creature or legendary spell" (Icy Reception) to
// the stack changed the generated bytes.
func TestCharmModeZonesKeepBattlefieldFixtures(t *testing.T) {
	reg := loadGenRegistry(t)
	cases := []struct {
		card  string
		svar  string
		slots []string
	}{
		// Counter's ValidTgts$ names a battlefield type -> battlefield slot.
		{"Icy Reception", "DBCounter", []string{"Creature,Card.Legendary"}},
		{"Theorix Charm", "DBCounter", []string{"Card.nonCreature"}},
		// Instant/sorcery-only -> stack-only (no battlefield permanent).
		{"Choreographed Sparks", "DBCopySpell", []string{"Instant.YouCtrl,Sorcery.YouCtrl@Stack"}},
		// Ability-types are intrinsically stack-only.
		{"Return the Favor", "DBChangeTarget", []string{"Card,Emblem@Stack"}},
	}
	for _, tc := range cases {
		got := oraclegen.ChainSlots(faceOf(t, reg, tc.card), tc.svar)
		if strings.Join(got, "|") != strings.Join(tc.slots, "|") {
			t.Errorf("%s %s: ChainSlots = %v, want %v", tc.card, tc.svar, got, tc.slots)
		}
	}
}

// TestTopLevelCounterStaysStack: a top-level Counter whose ValidTgts$ names
// a battlefield-card type (Card, Card.White) is still a stack target -- it
// goes through targetsSpell/counterSpell, not the charm mode path -- so its
// generated scenario keeps the precast spell it counters.
func TestTopLevelCounterStaysStack(t *testing.T) {
	reg := loadGenRegistry(t)
	for _, name := range []string{"Countersculpt", "Precise Redaction", "Icy Reception"} {
		c, ok := reg.Lookup(name)
		if !ok || len(c.Faces) == 0 {
			t.Fatalf("%s not in corpus", name)
		}
	}
	for _, name := range []string{"Countersculpt", "Precise Redaction"} {
		it, skip := Generate(reg, name)
		if skip != nil {
			t.Errorf("%s: %s", name, skip.Reason)
			continue
		}
		if it.Template != "counter-spell" {
			t.Errorf("%s: template = %q, want counter-spell", name, it.Template)
			continue
		}
		casts := 0
		for _, st := range it.Scenario.Steps {
			if st.Op == "cast" {
				casts++
			}
		}
		if casts < 2 {
			t.Errorf("%s: counter-spell scenario has %d cast steps, want 2 (precast + counter)", name, casts)
		}
	}
	// Icy Reception is a charm, not a top-level Counter: it must NOT route
	// to the counter template.
	if it, skip := Generate(reg, "Icy Reception"); skip != nil {
		t.Errorf("Icy Reception: %s", skip.Reason)
	} else if it.Template != "cast-resolve" {
		t.Errorf("Icy Reception: template = %q, want cast-resolve", it.Template)
	}
}
