package main

import (
	"bytes"
	"fmt"
	"io"
	"os"
	"runtime/debug"
	"sort"
	"strings"

	"github.com/adams-shaun/gorge/compliance"
	"github.com/adams-shaun/gorge/compliance/adopt"
)

// printedDir is where compliance/printed/<SET>.json lives, relative to the
// repo root, as gate.Check and adopt.Status read it.
const printedDir = "compliance/printed"

// runSetsTable runs the compliance gate at BOTH levels over the committed
// printed sets and renders one row per set:
//
//	| SET | level A | level B | notes |
//
// level A shows YES when the set has no outstanding level-A problem card,
// else n/m (clean cards / the set's card count); level B always shows the
// fraction. Counting is per CARD, not per problem: a card failing two
// requirements is one failing card (adopt.SetStatus.ProblemCards). notes
// summarises the set's outstanding problems at level B by reason bucket
// (largest first, ties in adopt.Buckets column order, at most 4 buckets
// then +N more), prefixed "A:" with the level-A buckets when level A is
// not clean -- leftovers there mean the report is wrong at the source.
//
// The gate is measured, not read from compliance/declared.json, so the
// level-B column works before any set is declared B. Only the sets with a
// committed compliance/printed/<SET>.json are measured (that is the set
// source; a manifest-only set has no gate claim at either level). Both
// levels run through the same child-process batches as `status -all` (one
// status child per level, at most adopt.ChildMaxCards cards each), because
// a gate run's heap cannot shrink in-process. Output is deterministic: no
// wall clock, the git head is the only identifier.
func runSetsTable(dir, out, level string, only []string, procs int) error {
	levels, err := parseLevels(level)
	if err != nil {
		return err
	}
	if os.Getenv("GOMEMLIMIT") == "" {
		// A gate batch is allocation-heavy (an engine per scenario); a
		// soft limit keeps the collector ahead of it.
		debug.SetMemoryLimit(768 << 20)
	}
	reg, err := loadReg(dir)
	if err != nil {
		return err
	}
	cs, err := adopt.Build(reg, ".")
	if err != nil {
		return err
	}
	codes := cs.SetCodes()
	if len(only) > 0 {
		codes = only
	}
	// A manifest-only set (no compliance/printed list) has no gate claim:
	// Build falls back to its manifest cards for the census, but the gate
	// walk reports "no printed list" for every card. Keep them out.
	measured := make([]string, 0, len(codes))
	for _, c := range codes {
		if _, err := compliance.LoadPrinted(printedDir, c); err == nil {
			measured = append(measured, c)
		}
	}
	codes = measured
	byLevel := map[string][]adopt.SetStatus{}
	for _, l := range levels {
		sets, err := cs.StatusChunked(codes, procs, func(batch []string) ([]adopt.SetStatus, error) {
			return statusChild(dir, l, batch)
		})
		if err != nil {
			return err
		}
		byLevel[l] = sets
	}
	var b bytes.Buffer
	writeSetsTable(&b, cs, byLevel["A"], byLevel["B"], gitHead())
	if out == "" {
		_, err = os.Stdout.Write(b.Bytes())
		return err
	}
	if err := os.WriteFile(out, b.Bytes(), 0o644); err != nil {
		return err
	}
	fmt.Fprintf(os.Stderr, "wrote %s\n", out)
	return nil
}

// parseLevels splits -level's comma-separated list into A/B codes.
func parseLevels(s string) ([]string, error) {
	var out []string
	for _, p := range strings.Split(s, ",") {
		if p != "A" && p != "B" {
			return nil, fmt.Errorf("sets -level wants A or B, got %q", p)
		}
		if !containsStr(out, p) {
			out = append(out, p)
		}
	}
	if len(out) == 0 {
		return nil, fmt.Errorf("sets -level wants at least one of A or B")
	}
	return out, nil
}

// writeSetsTable renders the table from the measured level lines. Either
// level's slice may be nil (its level was not requested): its column then
// reads em dash.
func writeSetsTable(w io.Writer, cs *adopt.Census, setsA, setsB []adopt.SetStatus, head string) {
	a := bySet(setsA)
	b := bySet(setsB)
	rank := func(s adopt.SetStatus) int {
		for i, f := range cs.Config.Formats {
			if containsStr(s.Formats, f.Name) {
				return i
			}
		}
		return len(cs.Config.Formats)
	}
	codes := make([]string, 0, len(a)+len(b))
	seen := map[string]bool{}
	for _, m := range []map[string]adopt.SetStatus{a, b} {
		for k := range m {
			if !seen[k] {
				seen[k] = true
				codes = append(codes, k)
			}
		}
	}
	sort.Slice(codes, func(i, j int) bool {
		sa, sb := lineOf(a, b, codes[i]), lineOf(a, b, codes[j])
		if ra, rb := rank(sa), rank(sb); ra != rb {
			return ra < rb
		}
		if sa.Released != sb.Released {
			return sa.Released > sb.Released
		}
		return codes[i] < codes[j]
	})
	fmt.Fprintf(w, "# Compliance sets\n\nGenerated by `go run ./cmd/oraclediff sets` at %s; generated, never committed (the .coverage/ tables, spec 2026-10-03 W2). The gate is measured at both levels, not read from compliance/declared.json.\n\n", head)
	fmt.Fprintln(w, "| SET | level A | level B | notes |")
	fmt.Fprintln(w, "|---|---|---|---|")
	for _, code := range codes {
		sa, sb := a[code], b[code]
		fmt.Fprintf(w, "| %s | %s | %s | %s |\n", code,
			levelCell(ptr(sa, setsA != nil), "A"), levelCell(ptr(sb, setsB != nil), "B"),
			setsNotes(&sa, setsA != nil, &sb, setsB != nil))
	}
}

func lineOf(a, b map[string]adopt.SetStatus, code string) adopt.SetStatus {
	if s, ok := a[code]; ok {
		return s
	}
	return b[code]
}

func ptr(s adopt.SetStatus, measured bool) *adopt.SetStatus {
	if !measured {
		return nil
	}
	return &s
}

// levelCell renders one level's column: YES at level A when the set has no
// problem card (level B keeps the fraction so a single regression shows as
// 304/305), else clean/m over cards.
func levelCell(s *adopt.SetStatus, level string) string {
	if s == nil {
		return "—"
	}
	if s.ProblemCards == 0 {
		if level == "A" {
			return "YES"
		}
		return fmt.Sprintf("%d/%d", s.Cards, s.Cards)
	}
	return fmt.Sprintf("%d/%d", s.Cards-s.ProblemCards, s.Cards)
}

// setsNotes renders the notes column: the level-B bucket summary, prefixed
// "A:" with the level-A summary when level A is not clean; em dash when
// the set is clean at both measured levels.
func setsNotes(a *adopt.SetStatus, aMeasured bool, b *adopt.SetStatus, bMeasured bool) string {
	var parts []string
	if aMeasured && a != nil && a.ProblemCards > 0 {
		parts = append(parts, "A: "+bucketSummary(a.Buckets))
	}
	if bMeasured && b != nil && b.ProblemCards > 0 {
		parts = append(parts, bucketSummary(b.Buckets))
	}
	if len(parts) == 0 {
		return "—"
	}
	return strings.Join(parts, "; ")
}

// bucketSummary renders a compact bucket note: largest bucket first, ties
// in adopt.Buckets column order, at most 4 buckets then "+N more".
func bucketSummary(buckets map[string]int) string {
	type kv struct {
		name string
		n    int
	}
	var ks []kv
	for _, b := range adopt.Buckets {
		if n := buckets[b]; n > 0 {
			ks = append(ks, kv{b, n})
		}
	}
	sort.SliceStable(ks, func(i, j int) bool { return ks[i].n > ks[j].n })
	var parts []string
	for i, k := range ks {
		if i == 4 {
			parts = append(parts, fmt.Sprintf("+%d more", len(ks)-4))
			break
		}
		parts = append(parts, fmt.Sprintf("%d %s", k.n, k.name))
	}
	return strings.Join(parts, ", ")
}

func bySet(sets []adopt.SetStatus) map[string]adopt.SetStatus {
	m := make(map[string]adopt.SetStatus, len(sets))
	for _, s := range sets {
		m[s.Set] = s
	}
	return m
}

func containsStr(xs []string, x string) bool {
	for _, v := range xs {
		if v == x {
			return true
		}
	}
	return false
}
