package main

import (
	"bufio"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/adams-shaun/gorge/compliance/adopt"
)

// runTickets emits one would-be ticket per finding class (section 11.3
// C4). It never files anything: without -out it prints the list; with -out
// it writes <id>.md briefs, index.jsonl and file.sh, the `agentctl issue
// add` commands an operator reviews and runs. Ids are stable, so running
// file.sh twice files nothing new.
func runTickets(dir, out string, minCards int, anyIn string, asJSON bool) error {
	reg, err := loadReg(dir)
	if err != nil {
		return err
	}
	cs, err := adopt.Build(reg, ".")
	if err != nil {
		return err
	}
	if anyIn == "" {
		anyIn = cs.Config.Formats[0].Name
	}
	ts, notes, err := cs.Tickets(reg, ".", adopt.TicketOptions{MinCards: minCards, AnyIn: anyIn})
	if err != nil {
		return err
	}
	byClass := map[string]int{}
	for _, t := range ts {
		byClass[t.Class]++
	}
	if out != "" {
		if err := writeTickets(out, ts); err != nil {
			return err
		}
	}
	if asJSON {
		enc := json.NewEncoder(os.Stdout)
		enc.SetEscapeHTML(false)
		for _, t := range ts {
			if err := enc.Encode(t); err != nil {
				return err
			}
		}
		return nil
	}
	for _, t := range ts {
		fmt.Printf("P%d %-10s %4d cards  %-52s %s\n", t.Priority, t.Class, len(t.Cards), t.ID, t.Title)
	}
	classes := make([]string, 0, len(byClass))
	for c := range byClass {
		classes = append(classes, c)
	}
	sort.Strings(classes)
	var parts []string
	for _, c := range classes {
		parts = append(parts, fmt.Sprintf("%s %d", c, byClass[c]))
	}
	for _, n := range notes {
		fmt.Println("not filed:", n)
	}
	fmt.Printf("tickets: %d (%s); primitive scope: %d+ tournament cards, or any card in %s\n", len(ts), strings.Join(parts, ", "), minCards, anyIn)
	if out != "" {
		fmt.Printf("wrote %s/<id>.md, %s/index.jsonl and %s/file.sh (review, then run file.sh to file them)\n", out, out, out)
	}
	return nil
}

func writeTickets(out string, ts []adopt.Ticket) error {
	if err := os.MkdirAll(out, 0o755); err != nil {
		return err
	}
	old, _ := filepath.Glob(filepath.Join(out, "compliance-*.md"))
	for _, p := range old {
		if err := os.Remove(p); err != nil {
			return err
		}
	}
	idx, err := os.Create(filepath.Join(out, "index.jsonl"))
	if err != nil {
		return err
	}
	defer idx.Close()
	sh, err := os.Create(filepath.Join(out, "file.sh"))
	if err != nil {
		return err
	}
	defer sh.Close()
	iw, sw := bufio.NewWriter(idx), bufio.NewWriter(sh)
	fmt.Fprintf(sw, "#!/bin/sh\n# Generated by `go run ./cmd/oraclediff tickets -out %s`: one agentctl ticket per\n# compliance finding class. Review the briefs, then run this from the agentctl\n# checkout with REPO set to the gorge checkout. Ids are stable, so a re-run\n# files nothing twice.\nset -e\n: \"${REPO:?set REPO to the gorge checkout}\"\nD=$(cd \"$(dirname \"$0\")\" && pwd)\n", out)
	enc := json.NewEncoder(iw)
	enc.SetEscapeHTML(false)
	for _, t := range ts {
		p := filepath.Join(out, t.ID+".md")
		if err := os.WriteFile(p, []byte(t.Body), 0o644); err != nil {
			return err
		}
		row := struct {
			adopt.Ticket
			Brief string `json:"brief"`
		}{t, t.ID + ".md"}
		if err := enc.Encode(row); err != nil {
			return err
		}
		fmt.Fprintf(sw, "python3 -m agentctl issue add \"$REPO\" --id %s --priority %d --title %s --brief-file \"$D/%s.md\"\n", t.ID, t.Priority, shQuote(t.Title), t.ID)
	}
	if err := iw.Flush(); err != nil {
		return err
	}
	return sw.Flush()
}

func shQuote(s string) string { return "'" + strings.ReplaceAll(s, "'", `'\''`) + "'" }
