package main

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/adams-shaun/gorge/cards"
	"github.com/adams-shaun/gorge/effects"
)

// The coverage command writes the card-support overview: a full breakdown
// (coverage.md) and a short summary (summary.md, the headline and the by-type
// split) into one output directory, `.coverage/` by default.
//
// GENERATED, NEVER COMMITTED (W2 of the 2026-10-03 lasagna spec). These
// tables used to live in README.md (a spliced block) and docs/coverage.md,
// refreshed by a CI job that committed back to main -- 90 bot commits in 14
// days that every live branch had to rebase across. Now `.coverage/` is
// gitignored, and the `card coverage` workflow publishes both files as the
// run's job summary and an uploaded artifact. Nothing writes README.md.
//
// WHY THE TABLE IS NOT BY SET. Forge's card scripts carry no set or edition
// data at all — a script is one card's behaviour, printed-set-agnostic, which
// is exactly why gorge can compile them without shipping them. Set membership
// lives in a different Forge tree (forge-gui/res/editions), which is GPL-3.0
// like the rest and which `forgec fetch` deliberately does not pull: adding it
// would double the fetched corpus and add a second GPL dependency for a
// cosmetic axis. So the breakdown groups by the three things the compiled IR
// does carry and that a reader actually wants: card type, colour and mana
// value. Card type is the useful one — it tracks which engine subsystems are
// done — and the other two are there to show the gap is not concentrated in
// one colour or at one end of the curve.
//
// The output is deterministic: no wall clock anywhere, every table sorted,
// and the only identifier printed is the corpus commit the measurement ran
// against, so two runs over the same corpus and tree are byte-identical and
// can be diffed.
const (
	coverageDocFile     = "coverage.md"
	coverageSummaryFile = "summary.md"
)

// topMissingInDoc is how many unimplemented primitives coverage.md ranks.
const topMissingInDoc = 20

type coverageData struct {
	// Corpus is the Forge commit the corpus was fetched at, "" when no lock
	// file is present.
	Corpus    string
	Cards     int
	Supported int
	Tokens    int
	ByType    []cards.CoverageGroup
	ByColour  []cards.CoverageGroup
	ByMana    []cards.CoverageGroup
	Missing   []cards.MissingPrimitive
}

func (d coverageData) percent() float64 {
	if d.Cards == 0 {
		return 0
	}
	return 100 * float64(d.Supported) / float64(d.Cards)
}

// byCountThenKey re-sorts a CoverageBy result into the order a reader wants
// for an unordered axis: biggest bucket first, ties broken on the key so the
// output stays deterministic.
func byCountThenKey(g []cards.CoverageGroup) []cards.CoverageGroup {
	out := append([]cards.CoverageGroup(nil), g...)
	sort.Slice(out, func(i, j int) bool {
		if out[i].Cards != out[j].Cards {
			return out[i].Cards > out[j].Cards
		}
		return out[i].Key < out[j].Key
	})
	return out
}

func measureCoverage(r *cards.Registry, dir string) coverageData {
	sup := effects.Supported()
	cv := r.Coverage(sup)
	d := coverageData{
		Cards:     cv.Cards,
		Supported: cv.Supported,
		Tokens:    len(r.Tokens),
		ByType:    byCountThenKey(r.CoverageBy(sup, cards.PrimaryTypeGroup)),
		ByColour:  byCountThenKey(r.CoverageBy(sup, cards.ColourGroup)),
		ByMana:    r.CoverageBy(sup, cards.ManaValueGroup),
		Missing:   cv.TopMissing(topMissingInDoc),
	}
	if l, err := cards.ReadLock(dir); err == nil {
		d.Corpus = l.Commit
	}
	return d
}

func groupTable(b *strings.Builder, header string, g []cards.CoverageGroup) {
	fmt.Fprintf(b, "| %s | Cards | Playable | %% |\n|---|---:|---:|---:|\n", header)
	for _, row := range g {
		fmt.Fprintf(b, "| %s | %d | %d | %.1f%% |\n", row.Key, row.Cards, row.Supported, row.Percent())
	}
}

// renderSummary is summary.md: the headline number and the by-type split,
// and nothing else. The full breakdown is coverage.md beside it, which this
// summary links to by a relative path.
func renderSummary(d coverageData) string {
	var b strings.Builder
	b.WriteString("<!-- generated by `make coverage`; edit cmd/forgec/coverage.go, not this file -->\n\n")
	fmt.Fprintf(&b, "Of the **%d** cards in the compiled Forge corpus, gorge can fully play **%d (%.1f%%)** —\n",
		d.Cards, d.Supported, d.percent())
	b.WriteString("every primitive the card's script names is implemented. By card type:\n\n")
	groupTable(&b, "Card type", d.ByType)
	b.WriteString("\nFull breakdown, including colour, mana value and what the remaining gap is\nwaiting on: [coverage.md](" + coverageDocFile + ").\n")
	return b.String()
}

func renderCoverageDoc(d coverageData) string {
	var b strings.Builder
	b.WriteString("# Card coverage\n\n")
	b.WriteString("<!-- generated by `make coverage`; edit cmd/forgec/coverage.go, not this file -->\n\n")
	fmt.Fprintf(&b, "gorge compiles [Card-Forge/forge](https://github.com/Card-Forge/forge)'s card\nscripts (pinned on gorge's fork, [adams-shaun/forge](https://github.com/adams-shaun/forge)) into an IR and implements the primitives that IR names. A card counts\nas **playable** here when every primitive its script references is implemented;\none missing primitive makes the whole card unplayable, so this is a strict\nlower bound on what the engine can do.\n\n")
	fmt.Fprintf(&b, "- Cards in the corpus: **%d**\n", d.Cards)
	fmt.Fprintf(&b, "- Fully playable: **%d (%.1f%%)**\n", d.Supported, d.percent())
	fmt.Fprintf(&b, "- Token scripts compiled: **%d**\n", d.Tokens)
	if d.Corpus != "" {
		fmt.Fprintf(&b, "- Corpus pin: `adams-shaun/forge@%s`\n", d.Corpus)
	}
	b.WriteString("\n## Why not by set?\n\n")
	b.WriteString("Forge card scripts carry no set or edition data: a script is one card's\nbehaviour, independent of which set printed it. Set membership lives in a\nseparate Forge resource tree that `forgec fetch` deliberately does not pull.\nSo the breakdown below groups by what the compiled IR does carry — card type,\ncolour and mana value. Card type is the informative axis: it tracks which\nengine subsystems are finished.\n\n")
	b.WriteString("## By card type\n\n")
	groupTable(&b, "Card type", d.ByType)
	b.WriteString("\n## By colour\n\n")
	b.WriteString("Colour here is the card's printed colour — the colours of its mana cost and\ncolour indicator — not its Commander colour identity.\n\n")
	groupTable(&b, "Colour", d.ByColour)
	b.WriteString("\n## By mana value\n\n")
	groupTable(&b, "Mana value", d.ByMana)
	b.WriteString("\n## What the gap is waiting on\n\n")
	b.WriteString("Each row is one unimplemented primitive and how many otherwise-playable cards\nit alone blocks. Implementing the top row unlocks that many cards at once.\n\n")
	b.WriteString("| Primitive | Cards blocked |\n|---|---:|\n")
	for _, m := range d.Missing {
		fmt.Fprintf(&b, "| `%s` | %d |\n", m.Name, m.Cards)
	}
	b.WriteString("\nRegenerate this file with `make coverage`.\n")
	return b.String()
}

// coverageCmd measures the corpus in dir and writes coverage.md and
// summary.md into outDir, creating it. Unchanged files are left alone.
func coverageCmd(dir, outDir string) error {
	r, err := loadReportRegistry(dir)
	if err != nil {
		return err
	}
	d := measureCoverage(r, dir)
	// A corpus that compiled but yielded nothing is a broken fetch, not 0%
	// coverage. Refuse rather than publish a table of zeroes.
	if d.Cards == 0 {
		return fmt.Errorf("no named cards in %s — the corpus is missing or empty; run `make fetch-cards`", dir)
	}
	if err := os.MkdirAll(outDir, 0o755); err != nil {
		return err
	}
	for _, f := range []struct{ name, body string }{
		{coverageDocFile, renderCoverageDoc(d)},
		{coverageSummaryFile, renderSummary(d)},
	} {
		p := filepath.Join(outDir, f.name)
		if cur, err := os.ReadFile(p); err == nil && string(cur) == f.body {
			continue
		}
		if err := os.WriteFile(p, []byte(f.body), 0o644); err != nil {
			return err
		}
		fmt.Printf("coverage: wrote %s\n", p)
	}
	fmt.Printf("coverage: %d/%d cards playable (%.1f%%)\n", d.Supported, d.Cards, d.percent())
	return nil
}
