// Package tsgen turns Go structs into TypeScript interfaces from their
// SOURCE, type-checked with go/types (no runtime reflection): json tags name
// the fields, omitempty makes them optional, pointers admit null, slices
// become arrays, string-keyed maps become Records. It exists so
// web/src/protocol.ts can never drift from package protocol — the committed
// file is regenerated by cmd/gentypes and diff-checked in lint.
package tsgen

import (
	"fmt"
	"go/ast"
	"go/importer"
	"go/parser"
	"go/token"
	"go/types"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
)

// Options drives one generation. Roots are walked transitively; Unions are
// emitted as string-literal union types (name -> values), sorted by name.
// Every root must come from one Loader, so one Go type is one types.Type.
type Options struct {
	Roots  []types.Type
	Unions map[string][]string
	Header string
}

// Loader type-checks packages from source. One Loader shares one importer,
// so a package reached from two roots is loaded once and its named types are
// pointer-identical.
type Loader struct {
	fset *token.FileSet
	imp  types.ImporterFrom
}

// NewLoader returns a Loader backed by the stdlib source importer (go/build
// resolution, module-aware).
func NewLoader() *Loader {
	fset := token.NewFileSet()
	return &Loader{fset: fset, imp: importer.ForCompiler(fset, "source", nil).(types.ImporterFrom)}
}

// Lookup type-checks pkgPath and returns its package-level type name.
func (l *Loader) Lookup(pkgPath, name string) (types.Type, error) {
	pkg, err := l.imp.ImportFrom(pkgPath, ".", 0)
	if err != nil {
		return nil, fmt.Errorf("tsgen: load %s: %w", pkgPath, err)
	}
	return lookupIn(pkg, name)
}

// CheckFiles type-checks exactly the named source files as package pkgPath
// (imports resolved through the Loader) and returns the package. It lets a
// test generate from types declared in its own _test.go file.
func (l *Loader) CheckFiles(pkgPath string, files ...string) (*types.Package, error) {
	var asts []*ast.File
	for _, f := range files {
		af, err := parser.ParseFile(l.fset, f, nil, 0)
		if err != nil {
			return nil, err
		}
		asts = append(asts, af)
	}
	conf := types.Config{Importer: l.imp}
	return conf.Check(pkgPath, l.fset, asts, nil)
}

// LookupIn returns pkg's package-level type name.
func LookupIn(pkg *types.Package, name string) (types.Type, error) { return lookupIn(pkg, name) }

func lookupIn(pkg *types.Package, name string) (types.Type, error) {
	tn, ok := pkg.Scope().Lookup(name).(*types.TypeName)
	if !ok {
		return nil, fmt.Errorf("tsgen: %s has no type %s", pkg.Path(), name)
	}
	return tn.Type(), nil
}

type gen struct {
	order []*types.Named
	seen  map[*types.Named]bool
	names map[string]*types.Named
	err   error
	cmts  *comments
}

// Generate renders the header, the unions, then one interface per struct in
// first-encounter order (roots first, nested types as they are met). Two
// distinct struct types with the same name are an error, as is an anonymous
// struct: the output needs a stable, unique name for each.
func Generate(o Options) (string, error) {
	g := &gen{seen: map[*types.Named]bool{}, names: map[string]*types.Named{}, cmts: newComments()}
	for _, r := range o.Roots {
		g.visit(r)
		if g.err != nil {
			return "", g.err
		}
	}
	var b strings.Builder
	b.WriteString(o.Header)
	b.WriteString("// Code generated by cmd/gentypes; DO NOT EDIT.\n")
	unionNames := make([]string, 0, len(o.Unions))
	for n := range o.Unions {
		unionNames = append(unionNames, n)
	}
	sort.Strings(unionNames)
	for _, n := range unionNames {
		vals := make([]string, len(o.Unions[n]))
		for i, v := range o.Unions[n] {
			vals[i] = fmt.Sprintf("%q", v)
		}
		fmt.Fprintf(&b, "\nexport type %s = %s;\n", n, strings.Join(vals, " | "))
	}
	for _, t := range g.order {
		b.WriteString("\n")
		g.writeStruct(&b, t)
	}
	return b.String(), nil
}

// isRawMessage reports whether t is exactly encoding/json.RawMessage.
func isRawMessage(t types.Type) bool {
	n, ok := types.Unalias(t).(*types.Named)
	return ok && n.Obj().Pkg() != nil && n.Obj().Pkg().Path() == "encoding/json" && n.Obj().Name() == "RawMessage"
}

// visit registers t (a struct) and every struct reachable from its fields.
func (g *gen) visit(t types.Type) {
	t = deref(t)
	if g.err != nil || isRawMessage(t) {
		return
	}
	st, ok := t.Underlying().(*types.Struct)
	if !ok {
		return
	}
	n, named := t.(*types.Named)
	if !named {
		g.err = fmt.Errorf("tsgen: anonymous struct in %v cannot be named", t)
		return
	}
	if g.seen[n] {
		return
	}
	name := n.Obj().Name()
	if prev, ok := g.names[name]; ok && prev != n {
		g.err = fmt.Errorf("tsgen: two structs named %s: %v and %v", name, prev, n)
		return
	}
	g.seen[n] = true
	g.names[name] = n
	// Fields are visited before t is appended so nested types are declared
	// first; TypeScript does not need that, but a reader does.
	for i := 0; i < st.NumFields(); i++ {
		if name, _ := jsonName(st.Field(i), st.Tag(i)); name == "" {
			continue
		}
		g.visit(elemStruct(st.Field(i).Type()))
	}
	g.order = append(g.order, n)
}

func (g *gen) writeStruct(b *strings.Builder, t *types.Named) {
	if doc := g.cmts.structDoc(t); doc != "" {
		writeComment(b, doc)
	}
	st := t.Underlying().(*types.Struct)
	fmt.Fprintf(b, "export interface %s {\n", t.Obj().Name())
	for i := 0; i < st.NumFields(); i++ {
		f := st.Field(i)
		name, omitempty := jsonName(f, st.Tag(i))
		if name == "" {
			continue
		}
		if doc := g.cmts.fieldDoc(t, f.Name()); doc != "" {
			writeComment(b, doc)
		}
		q := ""
		if omitempty {
			q = "?"
		}
		fmt.Fprintf(b, "  %s%s: %s;\n", name, q, tsType(f.Type()))
	}
	b.WriteString("}\n")
}

// writeComment emits doc as a /* ... */ block. Long comments are NOT wrapped:
// each source line becomes one ` * ` line, so the emitted text is the writer's
// line structure unchanged and the output is byte-deterministic. Any `*/` in
// the text is escaped to `* /` so the doc cannot terminate its own block (a
// Go writer using a //-comment may legally contain that sequence).
func writeComment(b *strings.Builder, doc string) {
	lines := strings.Split(escapeComment(doc), "\n")
	b.WriteString("  /**\n")
	for _, ln := range lines {
		if ln == "" {
			b.WriteString("   *\n")
		} else {
			b.WriteString("   * " + ln + "\n")
		}
	}
	b.WriteString("   */\n")
}

// escapeComment neutralises the one sequence that can terminate a block
// comment (`*/`) by separating the two characters. Deterministic and context-
// free; `/*` needs no handling because block comments do not nest, so only the
// terminator can end the block early.
func escapeComment(s string) string {
	return strings.ReplaceAll(s, "*/", "* /")
}

// jsonName is the wire name and whether omitempty is set; "" means skip
// (json:"-" or an unexported field). An embedded field is named by its type,
// exactly as encoding/json would NOT flatten it here (the generator emits it
// as a nested member, as it always has).
func jsonName(f *types.Var, tag string) (string, bool) {
	if !f.Exported() {
		return "", false
	}
	tv, _ := lookupTag(tag, "json")
	if tv == "-" {
		return "", false
	}
	name, opts, _ := strings.Cut(tv, ",")
	if name == "" {
		name = f.Name()
	}
	return name, strings.Contains(opts, "omitempty")
}

// lookupTag is the struct-tag convention parser (the one encoding/json
// reads): space-separated key:"quoted value" pairs.
func lookupTag(tag, key string) (string, bool) {
	for tag != "" {
		i := 0
		for i < len(tag) && tag[i] == ' ' {
			i++
		}
		tag = tag[i:]
		if tag == "" {
			break
		}
		i = 0
		for i < len(tag) && tag[i] > ' ' && tag[i] != ':' && tag[i] != '"' && tag[i] != 0x7f {
			i++
		}
		if i == 0 || i+1 >= len(tag) || tag[i] != ':' || tag[i+1] != '"' {
			break
		}
		name := tag[:i]
		tag = tag[i+1:]
		i = 1
		for i < len(tag) && tag[i] != '"' {
			if tag[i] == '\\' {
				i++
			}
			i++
		}
		if i >= len(tag) {
			break
		}
		qvalue := tag[:i+1]
		tag = tag[i+1:]
		if key == name {
			value, err := strconv.Unquote(qvalue)
			if err != nil {
				break
			}
			return value, true
		}
	}
	return "", false
}

// tsType maps one Go type to TypeScript.
func tsType(t types.Type) string {
	t = types.Unalias(t)
	if isRawMessage(t) {
		return "unknown"
	}
	switch u := t.Underlying().(type) {
	case *types.Pointer:
		return tsType(u.Elem()) + " | null"
	case *types.Interface:
		return "unknown"
	case *types.Basic:
		switch {
		case u.Info()&types.IsBoolean != 0:
			return "boolean"
		case u.Info()&types.IsString != 0:
			return "string"
		case u.Info()&(types.IsInteger|types.IsFloat) != 0:
			return "number"
		}
	case *types.Slice:
		if b, ok := u.Elem().Underlying().(*types.Basic); ok && b.Kind() == types.Uint8 {
			return "string" // encoding/json base64-encodes []byte
		}
		return tsType(u.Elem()) + "[]"
	case *types.Array:
		parts := make([]string, u.Len())
		for i := range parts {
			parts[i] = tsType(u.Elem())
		}
		return "[" + strings.Join(parts, ", ") + "]"
	case *types.Map:
		return "Record<string, " + tsType(u.Elem()) + ">"
	case *types.Struct:
		if n, ok := t.(*types.Named); ok {
			return n.Obj().Name()
		}
		return ""
	}
	return "unknown"
}

func deref(t types.Type) types.Type {
	t = types.Unalias(t)
	for {
		p, ok := t.Underlying().(*types.Pointer)
		if !ok {
			return t
		}
		t = types.Unalias(p.Elem())
	}
}

// elemStruct digs through pointers, slices, arrays and maps to the struct a
// field ultimately holds, if any.
func elemStruct(t types.Type) types.Type {
	for {
		t = types.Unalias(t)
		switch u := t.Underlying().(type) {
		case *types.Pointer:
			t = u.Elem()
		case *types.Slice:
			t = u.Elem()
		case *types.Array:
			t = u.Elem()
		case *types.Map:
			t = u.Elem()
		default:
			return t
		}
	}
}

// comments carries the Go doc comments (struct and field) that the generator
// emits as /* ... */ blocks. go/types carries no comments, so each package is parsed from source once, keyed by import path. Loading is
// lazy and best-effort: a package whose source cannot be located simply
// contributes no comments rather than failing the whole generation.
type comments struct {
	moduleRoot string
	modulePath string
	loaded     map[string]bool
	pkgs       map[string]*pkgComments
}

// pkgComments holds one package's struct and field doc comments, keyed by
// declaration name (struct) and, within a struct, by field name.
type pkgComments struct {
	structs map[string]string
	fields  map[string]map[string]string
}

func newComments() *comments {
	return &comments{loaded: map[string]bool{}, pkgs: map[string]*pkgComments{}}
}

// structDoc returns the doc comment above a struct type, or "".
func (c *comments) structDoc(t *types.Named) string {
	return c.pkg(t).structs[t.Obj().Name()]
}

// fieldDoc returns the doc comment above a struct field, or "".
func (c *comments) fieldDoc(t *types.Named, field string) string {
	pc := c.pkg(t)
	return pc.fields[t.Obj().Name()][field]
}

// pkg resolves t's package comments, loading them from source if needed.
func (c *comments) pkg(t *types.Named) *pkgComments {
	pkgPath := ""
	if p := t.Obj().Pkg(); p != nil {
		pkgPath = p.Path()
	}
	if pc, ok := c.pkgs[pkgPath]; ok {
		return pc
	}
	pc := &pkgComments{structs: map[string]string{}, fields: map[string]map[string]string{}}
	c.pkgs[pkgPath] = pc // record first so a failure never re-loads
	if dir, err := c.packageDir(pkgPath); err == nil {
		if parsed, err := parsePackageDir(dir); err == nil {
			pc.structs = parsed.structs
			pc.fields = parsed.fields
		}
	}
	return pc
}

// packageDir resolves an import path to a directory inside the current module.
// It finds the enclosing go.mod by walking up from the working directory. A
// package outside the module has no directory here and yields an error, which
// pkg turns into "no comments".
func (c *comments) packageDir(pkgPath string) (string, error) {
	if c.modulePath == "" {
		if err := c.findModule(); err != nil {
			return "", err
		}
	}
	if pkgPath == c.modulePath {
		return c.moduleRoot, nil
	}
	if !strings.HasPrefix(pkgPath, c.modulePath+"/") {
		return "", fmt.Errorf("package %s is outside module %s", pkgPath, c.modulePath)
	}
	rel := strings.TrimPrefix(pkgPath, c.modulePath+"/")
	return filepath.Join(c.moduleRoot, filepath.FromSlash(rel)), nil
}

// findModule walks up from the working directory to the go.mod that declares
// the current module and records its root and module path.
func (c *comments) findModule() error {
	dir, err := os.Getwd()
	if err != nil {
		return err
	}
	for {
		gomod := filepath.Join(dir, "go.mod")
		if fi, statErr := os.Stat(gomod); statErr == nil && !fi.IsDir() {
			data, readErr := os.ReadFile(gomod)
			if readErr != nil {
				return readErr
			}
			for _, line := range strings.Split(string(data), "\n") {
				line = strings.TrimSpace(line)
				if rest, ok := strings.CutPrefix(line, "module "); ok {
					c.moduleRoot = dir
					c.modulePath = strings.TrimSpace(rest)
					return nil
				}
			}
			return fmt.Errorf("no module directive in %s", gomod)
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			return fmt.Errorf("no go.mod found above %s", dir)
		}
		dir = parent
	}
}

// parsePackageDir parses every .go file in dir and collects the doc comments
// of structs and their fields. Non-test files are parsed first so a real
// declaration wins over a test-only shadow with the same name. Comment text is
// returned with each `//`/`/* */` line trimmed to its content, joined by \n.
func parsePackageDir(dir string) (*pkgComments, error) {
	pc := &pkgComments{structs: map[string]string{}, fields: map[string]map[string]string{}}
	entries, err := os.ReadDir(dir)
	if err != nil {
		return nil, err
	}
	var regular, tests []string
	for _, e := range entries {
		if e.IsDir() || !strings.HasSuffix(e.Name(), ".go") {
			continue
		}
		p := filepath.Join(dir, e.Name())
		if strings.HasSuffix(e.Name(), "_test.go") {
			tests = append(tests, p)
		} else {
			regular = append(regular, p)
		}
	}
	sort.Strings(regular)
	sort.Strings(tests)
	for _, file := range regular {
		f, parseErr := parser.ParseFile(token.NewFileSet(), file, nil, parser.ParseComments)
		if parseErr != nil {
			continue // a file that does not parse contributes nothing
		}
		collectStructComments(pc, f, true)
	}
	for _, file := range tests {
		f, parseErr := parser.ParseFile(token.NewFileSet(), file, nil, parser.ParseComments)
		if parseErr != nil {
			continue
		}
		collectStructComments(pc, f, false)
	}
	return pc, nil
}

// collectStructComments records the struct and field doc comments in one parsed
// file. When overwrite is false (a test file), an already-recorded declaration
// is left untouched so the real code's comment wins.
func collectStructComments(pc *pkgComments, f *ast.File, overwrite bool) {
	for _, decl := range f.Decls {
		gd, ok := decl.(*ast.GenDecl)
		if !ok || gd.Tok != token.TYPE {
			continue
		}
		for _, spec := range gd.Specs {
			ts, ok := spec.(*ast.TypeSpec)
			if !ok {
				continue
			}
			st, ok := ts.Type.(*ast.StructType)
			if !ok {
				continue
			}
			// A single type declaration hangs its comment on the GenDecl's Doc,
			// not the TypeSpec's; a grouped `type ( ... )`'s comments live on
			// each TypeSpec. Prefer the TypeSpec, fall back to the GenDecl.
			doc := commentText(ts.Doc)
			if doc == "" {
				doc = commentText(gd.Doc)
			}
			if doc != "" && (overwrite || pc.structs[ts.Name.Name] == "") {
				pc.structs[ts.Name.Name] = doc
			}
			if len(st.Fields.List) == 0 {
				continue
			}
			fm := pc.fields[ts.Name.Name]
			if fm == nil {
				fm = map[string]string{}
				pc.fields[ts.Name.Name] = fm
			}
			for _, field := range st.Fields.List {
				doc := commentText(field.Doc)
				if doc == "" {
					continue
				}
				for _, name := range field.Names {
					if overwrite || fm[name.Name] == "" {
						fm[name.Name] = doc
					}
				}
			}
		}
	}
}

// commentText flattens a comment group to its content, one string per source
// line. `//` and `/* */` forms are both handled; blank leading/trailing lines
// are dropped so a `/* */` block does not open and close on empty lines.
func commentText(cg *ast.CommentGroup) string {
	if cg == nil {
		return ""
	}
	var lines []string
	for _, c := range cg.List {
		text := c.Text
		switch {
		case strings.HasPrefix(text, "//"):
			lines = append(lines, strings.TrimPrefix(strings.TrimPrefix(text, "//"), " "))
		case strings.HasPrefix(text, "/*"):
			text = strings.TrimSuffix(strings.TrimPrefix(text, "/*"), "*/")
			for _, ln := range strings.Split(text, "\n") {
				ln = strings.TrimPrefix(ln, " ")
				ln = strings.TrimPrefix(ln, "*")
				ln = strings.TrimPrefix(ln, " ")
				lines = append(lines, ln)
			}
		}
	}
	for len(lines) > 0 && strings.TrimSpace(lines[0]) == "" {
		lines = lines[1:]
	}
	for len(lines) > 0 && strings.TrimSpace(lines[len(lines)-1]) == "" {
		lines = lines[:len(lines)-1]
	}
	return strings.Join(lines, "\n")
}
