// Code generated by protocol/manabrew/internal/schemagen; DO NOT EDIT.

package manabrew

var (
	schemaActOutput                         = &schema{kind: schemaStruct}
	schemaAgentPrompt                       = &schema{kind: schemaStruct}
	schemaAttackTargetDto                   = &schema{kind: schemaStruct}
	schemaAttackerAssignment                = &schema{kind: schemaStruct}
	schemaAttackerOptionDto                 = &schema{kind: schemaStruct}
	schemaAvailableAction                   = &schema{kind: schemaStruct}
	schemaBlockableAttackerDto              = &schema{kind: schemaStruct}
	schemaBlockerAssignment                 = &schema{kind: schemaStruct}
	schemaBoardTargetsDecision              = &schema{kind: schemaStruct}
	schemaBooleanDecision                   = &schema{kind: schemaStruct}
	schemaCancelOutput                      = &schema{kind: schemaStruct}
	schemaCardBackFaceSummary               = &schema{kind: schemaStruct}
	schemaCardChoiceDto                     = &schema{kind: schemaStruct}
	schemaCardDto                           = &schema{kind: schemaStruct}
	schemaCardIdentity                      = &schema{kind: schemaStruct}
	schemaCardImageUris                     = &schema{kind: schemaStruct}
	schemaCardView                          = &schema{kind: schemaStruct}
	schemaChooseActionInput                 = &schema{kind: schemaStruct}
	schemaChooseAttackersInput              = &schema{kind: schemaStruct}
	schemaChooseBlockersInput               = &schema{kind: schemaStruct}
	schemaChooseBoardTargetsInput           = &schema{kind: schemaStruct}
	schemaChooseBooleanInput                = &schema{kind: schemaStruct}
	schemaChooseCardsDecision               = &schema{kind: schemaStruct}
	schemaChooseCardsInput                  = &schema{kind: schemaStruct}
	schemaChooseColorInput                  = &schema{kind: schemaStruct}
	schemaChooseCombatDamageAssignmentInput = &schema{kind: schemaStruct}
	schemaChooseDamageAssignmentOrderInput  = &schema{kind: schemaStruct}
	schemaChooseFromSelectionInput          = &schema{kind: schemaStruct}
	schemaChooseNumberInput                 = &schema{kind: schemaStruct}
	schemaClassLevelDto                     = &schema{kind: schemaStruct}
	schemaClientDirective                   = &schema{kind: schemaStruct}
	schemaClientMessage                     = &schema{kind: schemaStruct}
	schemaClientResponse                    = &schema{kind: schemaStruct}
	schemaColorDecision                     = &schema{kind: schemaStruct}
	schemaCombatAssignmentDto               = &schema{kind: schemaStruct}
	schemaDamageAssignment                  = &schema{kind: schemaStruct}
	schemaDamageAssignmentDecision          = &schema{kind: schemaStruct}
	schemaDamageAssignmentOrderDecision     = &schema{kind: schemaStruct}
	schemaDeck                              = &schema{kind: schemaStruct}
	schemaDeckCard                          = &schema{kind: schemaStruct}
	schemaDeckCardIdentity                  = &schema{kind: schemaStruct}
	schemaDeckLabel                         = &schema{kind: schemaStruct}
	schemaDeclareAttackersDecision          = &schema{kind: schemaStruct}
	schemaDeclareBlockersDecision           = &schema{kind: schemaStruct}
	schemaDiceRollEntry                     = &schema{kind: schemaStruct}
	schemaDiceRolledAcknowledged            = &schema{kind: schemaStruct}
	schemaDiceRolledInput                   = &schema{kind: schemaStruct}
	schemaDirectiveInput                    = &schema{kind: schemaStruct}
	schemaDisplayMessage                    = &schema{kind: schemaStruct}
	schemaEngineMessage                     = &schema{kind: schemaStruct}
	schemaErrorMessage                      = &schema{kind: schemaStruct}
	schemaGameOverInput                     = &schema{kind: schemaStruct}
	schemaGameViewDto                       = &schema{kind: schemaStruct}
	schemaHiddenCard                        = &schema{kind: schemaStruct}
	schemaMana                              = &schema{kind: schemaStruct}
	schemaMulliganDecision                  = &schema{kind: schemaStruct}
	schemaMulliganInput                     = &schema{kind: schemaStruct}
	schemaMulliganPutBackDecision           = &schema{kind: schemaStruct}
	schemaMulliganPutBackInput              = &schema{kind: schemaStruct}
	schemaNumberDecision                    = &schema{kind: schemaStruct}
	schemaOwnDeckExtension                  = &schema{kind: schemaStruct}
	schemaOwnDeckRow                        = &schema{kind: schemaStruct}
	schemaPassOutput                        = &schema{kind: schemaStruct}
	schemaPassUntil                         = &schema{kind: schemaStruct}
	schemaPayManaCostInput                  = &schema{kind: schemaStruct}
	schemaPayOutput                         = &schema{kind: schemaStruct}
	schemaPaymentAction                     = &schema{kind: schemaStruct}
	schemaPlayerDto                         = &schema{kind: schemaStruct}
	schemaPromptBase                        = &schema{kind: schemaStruct}
	schemaPromptInput                       = &schema{kind: schemaStruct}
	schemaPromptMessage                     = &schema{kind: schemaStruct}
	schemaPromptOutput                      = &schema{kind: schemaStruct}
	schemaPromptOutputData                  = &schema{kind: schemaStruct}
	schemaPromptPresentation                = &schema{kind: schemaStruct}
	schemaProtocolError                     = &schema{kind: schemaStruct}
	schemaReorderDecision                   = &schema{kind: schemaStruct}
	schemaReorderInput                      = &schema{kind: schemaStruct}
	schemaReorderItem                       = &schema{kind: schemaStruct}
	schemaRestoreSnapshotOutput             = &schema{kind: schemaStruct}
	schemaRevealCardsAcknowledged           = &schema{kind: schemaStruct}
	schemaRevealCardsInput                  = &schema{kind: schemaStruct}
	schemaSagaChapterDto                    = &schema{kind: schemaStruct}
	schemaScryDecision                      = &schema{kind: schemaStruct}
	schemaScryInput                         = &schema{kind: schemaStruct}
	schemaSelectionDecision                 = &schema{kind: schemaStruct}
	schemaSelectionOption                   = &schema{kind: schemaStruct}
	schemaStackObjectDto                    = &schema{kind: schemaStruct}
	schemaStateDelta                        = &schema{kind: schemaStruct}
	schemaStateUpdate                       = &schema{kind: schemaStruct}
	schemaTargetRef                         = &schema{kind: schemaStruct}
	schemaVisibleCard                       = &schema{kind: schemaStruct}
	schemaZoneDto                           = &schema{kind: schemaStruct}
	schemaschema                            = &schema{kind: schemaStruct}
)

func init() {
	schemaActOutput.fields = map[string]*schema{
		"actionId": nil,
	}
	schemaAgentPrompt.fields = map[string]*schema{
		"decidingPlayerId": nil,
		"input":            schemaPromptInput,
		"promptId":         nil,
		"sourceCard":       schemaCardDto,
	}
	schemaAttackTargetDto.fields = map[string]*schema{
		"id":    nil,
		"kind":  nil,
		"label": nil,
	}
	schemaAttackerAssignment.fields = map[string]*schema{
		"attackerId": nil,
		"targetId":   nil,
	}
	schemaAttackerOptionDto.fields = map[string]*schema{
		"attackerId":     nil,
		"mustAttack":     nil,
		"validTargetIds": nil,
	}
	schemaAvailableAction.fields = map[string]*schema{
		"abilityIndex":   nil,
		"cardId":         nil,
		"cost":           nil,
		"description":    nil,
		"id":             nil,
		"isClassLevelUp": nil,
		"isManaAbility":  nil,
		"label":          nil,
		"mode":           nil,
		"producedMana":   &schema{kind: schemaList, elem: schemaMana},
		"type":           nil,
	}
	schemaBlockableAttackerDto.fields = map[string]*schema{
		"attackerId":      nil,
		"maxBlockers":     nil,
		"minBlockers":     nil,
		"mustBeBlocked":   nil,
		"validBlockerIds": nil,
	}
	schemaBlockerAssignment.fields = map[string]*schema{
		"attackerId": nil,
		"blockerId":  nil,
	}
	schemaBoardTargetsDecision.fields = map[string]*schema{
		"chosen": &schema{kind: schemaList, elem: schemaTargetRef},
	}
	schemaBooleanDecision.fields = map[string]*schema{
		"value": nil,
	}
	schemaCancelOutput.fields = map[string]*schema{}
	schemaCardBackFaceSummary.fields = map[string]*schema{
		"manaCost":  nil,
		"name":      nil,
		"power":     nil,
		"toughness": nil,
		"types":     nil,
	}
	schemaCardChoiceDto.fields = map[string]*schema{
		"id":    nil,
		"label": nil,
	}
	schemaCardDto.fields = map[string]*schema{
		"attachedTo":        nil,
		"attachmentIds":     nil,
		"attackTargetId":    nil,
		"attackingPlayerId": nil,
		"basePower":         nil,
		"baseToughness":     nil,
		"choices":           &schema{kind: schemaList, elem: schemaCardChoiceDto},
		"classLevel":        nil,
		"classLevels":       &schema{kind: schemaList, elem: schemaClassLevelDto},
		"cmc":               nil,
		"color":             nil,
		"commanderTax":      nil,
		"controllerId":      nil,
		"counters":          nil,
		"damage":            nil,
		"effectiveManaCost": nil,
		"exerted":           nil,
		"finalChapter":      nil,
		"flashbackCost":     nil,
		"foil":              nil,
		"id":                nil,
		"identity":          schemaCardIdentity,
		"isAttacking":       nil,
		"isBestowed":        nil,
		"isCopy":            nil,
		"isCrewed":          nil,
		"isDoubleFaced":     nil,
		"isFaceDown":        nil,
		"isMadnessExiled":   nil,
		"isPlotted":         nil,
		"isRingBearer":      nil,
		"isTransformed":     nil,
		"isWarpExiled":      nil,
		"keywords":          nil,
		"kickerCost":        nil,
		"madnessCost":       nil,
		"manaCost":          nil,
		"mergedCardIds":     nil,
		"ownerId":           nil,
		"phasedOut":         nil,
		"power":             nil,
		"sagaChapters":      &schema{kind: schemaList, elem: schemaSagaChapterDto},
		"subtypes":          nil,
		"summoningSick":     nil,
		"supertypes":        nil,
		"tapped":            nil,
		"text":              nil,
		"toughness":         nil,
		"types":             nil,
		"wouldDieInCombat":  nil,
	}
	schemaCardIdentity.fields = map[string]*schema{
		"cardNumber":  nil,
		"isToken":     nil,
		"name":        nil,
		"setCode":     nil,
		"tokenScript": nil,
	}
	schemaCardImageUris.fields = map[string]*schema{
		"art_crop":    nil,
		"border_crop": nil,
		"large":       nil,
		"normal":      nil,
		"small":       nil,
	}
	schemaCardView.fields = map[string]*schema{}
	schemaChooseActionInput.fields = map[string]*schema{
		"actions": &schema{kind: schemaList, elem: schemaAvailableAction},
	}
	schemaChooseAttackersInput.fields = map[string]*schema{
		"attackTargets": &schema{kind: schemaList, elem: schemaAttackTargetDto},
		"attackers":     &schema{kind: schemaList, elem: schemaAttackerOptionDto},
	}
	schemaChooseBlockersInput.fields = map[string]*schema{
		"attackers":           &schema{kind: schemaList, elem: schemaBlockableAttackerDto},
		"availableBlockerIds": nil,
		"error":               nil,
	}
	schemaChooseBoardTargetsInput.fields = map[string]*schema{
		"cancellable":   nil,
		"candidates":    &schema{kind: schemaList, elem: schemaTargetRef},
		"chosenTargets": &schema{kind: schemaList, elem: schemaTargetRef},
		"hostile":       nil,
		"intent":        nil,
		"maxTargets":    nil,
		"minTargets":    nil,
		"presentation":  schemaPromptPresentation,
	}
	schemaChooseBooleanInput.fields = map[string]*schema{
		"confirmLabel": nil,
		"denyLabel":    nil,
		"presentation": schemaPromptPresentation,
	}
	schemaChooseCardsDecision.fields = map[string]*schema{
		"chosenCardIds": nil,
	}
	schemaChooseCardsInput.fields = map[string]*schema{
		"cards":        &schema{kind: schemaList, elem: schemaCardDto},
		"max":          nil,
		"min":          nil,
		"presentation": schemaPromptPresentation,
	}
	schemaChooseColorInput.fields = map[string]*schema{
		"amount":        nil,
		"presentation":  schemaPromptPresentation,
		"repeatAllowed": nil,
		"validColors":   nil,
	}
	schemaChooseCombatDamageAssignmentInput.fields = map[string]*schema{
		"attackerHasDeathtouch": nil,
		"attackerId":            nil,
		"blockerIds":            nil,
		"defenderId":            nil,
		"totalDamage":           nil,
	}
	schemaChooseDamageAssignmentOrderInput.fields = map[string]*schema{
		"attackerId":   nil,
		"blockerCards": &schema{kind: schemaList, elem: schemaCardDto},
		"blockerIds":   nil,
	}
	schemaChooseFromSelectionInput.fields = map[string]*schema{
		"maxTotal":     nil,
		"minTotal":     nil,
		"options":      &schema{kind: schemaList, elem: schemaSelectionOption},
		"presentation": schemaPromptPresentation,
	}
	schemaChooseNumberInput.fields = map[string]*schema{
		"max":          nil,
		"min":          nil,
		"presentation": schemaPromptPresentation,
	}
	schemaClassLevelDto.fields = map[string]*schema{
		"abilities": nil,
		"level":     nil,
		"maxLevel":  nil,
		"minLevel":  nil,
	}
	schemaClientDirective.fields = map[string]*schema{
		"directive": schemaDirectiveInput,
		"kind":      nil,
	}
	schemaClientMessage.fields = map[string]*schema{}
	schemaClientResponse.fields = map[string]*schema{
		"action":   schemaPromptOutput,
		"kind":     nil,
		"promptId": nil,
	}
	schemaColorDecision.fields = map[string]*schema{
		"chosenColors": nil,
	}
	schemaCombatAssignmentDto.fields = map[string]*schema{
		"attackerId": nil,
		"blockerId":  nil,
	}
	schemaDamageAssignment.fields = map[string]*schema{
		"assigneeId": nil,
		"damage":     nil,
	}
	schemaDamageAssignmentDecision.fields = map[string]*schema{
		"assignments": &schema{kind: schemaList, elem: schemaDamageAssignment},
	}
	schemaDamageAssignmentOrderDecision.fields = map[string]*schema{
		"orderedBlockerIds": nil,
	}
	schemaDeck.fields = map[string]*schema{
		"attractions":     &schema{kind: schemaList, elem: schemaDeckCard},
		"cardTags":        nil,
		"cards":           &schema{kind: schemaList, elem: schemaDeckCard},
		"color":           nil,
		"commanders":      &schema{kind: schemaList, elem: schemaDeckCard},
		"companion":       schemaDeckCard,
		"contraptions":    &schema{kind: schemaList, elem: schemaDeckCard},
		"coverCardFace":   nil,
		"coverCardName":   nil,
		"customTags":      nil,
		"description":     nil,
		"draft":           nil,
		"editor":          nil,
		"format":          nil,
		"id":              nil,
		"labels":          &schema{kind: schemaList, elem: schemaDeckLabel},
		"maybeboard":      &schema{kind: schemaList, elem: schemaDeckCard},
		"name":            nil,
		"planes":          &schema{kind: schemaList, elem: schemaDeckCard},
		"playmatAssetId":  nil,
		"playmatSettings": nil,
		"playmatUrl":      nil,
		"schemes":         &schema{kind: schemaList, elem: schemaDeckCard},
		"sideboard":       &schema{kind: schemaList, elem: schemaDeckCard},
		"stackPositions":  nil,
		"tokens":          &schema{kind: schemaList, elem: schemaDeckCard},
		"version":         nil,
	}
	schemaDeckCard.fields = map[string]*schema{
		"allParts":      nil,
		"backFace":      schemaCardBackFaceSummary,
		"cmc":           nil,
		"color":         nil,
		"colorIdentity": nil,
		"identity":      schemaDeckCardIdentity,
		"imageLanguage": nil,
		"isDoubleFaced": nil,
		"keywords":      nil,
		"layout":        nil,
		"manaCost":      nil,
		"power":         nil,
		"subtypes":      nil,
		"supertypes":    nil,
		"text":          nil,
		"toughness":     nil,
		"types":         nil,
		"uris":          schemaCardImageUris,
	}
	schemaDeckCardIdentity.fields = map[string]*schema{
		"cardNumber":  nil,
		"foil":        nil,
		"id":          nil,
		"name":        nil,
		"oracleId":    nil,
		"setCode":     nil,
		"tokenScript": nil,
	}
	schemaDeckLabel.fields = map[string]*schema{
		"color": nil,
		"name":  nil,
	}
	schemaDeclareAttackersDecision.fields = map[string]*schema{
		"assignments": &schema{kind: schemaList, elem: schemaAttackerAssignment},
	}
	schemaDeclareBlockersDecision.fields = map[string]*schema{
		"assignments": &schema{kind: schemaList, elem: schemaBlockerAssignment},
	}
	schemaDiceRollEntry.fields = map[string]*schema{
		"finalResults":   nil,
		"highlighted":    nil,
		"ignoredRolls":   nil,
		"label":          nil,
		"naturalResults": nil,
		"playerId":       nil,
		"round":          nil,
	}
	schemaDiceRolledAcknowledged.fields = map[string]*schema{}
	schemaDiceRolledInput.fields = map[string]*schema{
		"presentation": schemaPromptPresentation,
		"rolls":        &schema{kind: schemaList, elem: schemaDiceRollEntry},
		"sides":        nil,
	}
	schemaDirectiveInput.fields = map[string]*schema{
		"type": nil,
	}
	schemaDisplayMessage.fields = map[string]*schema{
		"event": nil,
		"kind":  nil,
	}
	schemaEngineMessage.fields = map[string]*schema{}
	schemaErrorMessage.fields = map[string]*schema{
		"error": schemaProtocolError,
		"kind":  nil,
	}
	schemaGameOverInput.fields = map[string]*schema{}
	schemaGameViewDto.fields = map[string]*schema{
		"activePlaneNames":    nil,
		"activePlayerId":      nil,
		"combatAssignments":   &schema{kind: schemaList, elem: schemaCombatAssignmentDto},
		"dayTime":             nil,
		"gameId":              nil,
		"gameOver":            nil,
		"initiativeHolderId":  nil,
		"monarchId":           nil,
		"players":             &schema{kind: schemaList, elem: schemaPlayerDto},
		"priorityPlayerId":    nil,
		"stack":               &schema{kind: schemaList, elem: schemaStackObjectDto},
		"step":                nil,
		"turn":                nil,
		"winnerId":            nil,
		"x_gorge_own_deck_v1": schemaOwnDeckExtension,
		"zones":               &schema{kind: schemaList, elem: schemaZoneDto},
	}
	schemaHiddenCard.fields = map[string]*schema{
		"id":         nil,
		"visibility": nil,
	}
	schemaMana.fields = map[string]*schema{
		"amount": nil,
		"color":  nil,
	}
	schemaMulliganDecision.fields = map[string]*schema{
		"keep": nil,
	}
	schemaMulliganInput.fields = map[string]*schema{
		"handCardIds":   nil,
		"mulliganCount": nil,
	}
	schemaMulliganPutBackDecision.fields = map[string]*schema{
		"cardIds": nil,
	}
	schemaMulliganPutBackInput.fields = map[string]*schema{
		"cards":       &schema{kind: schemaList, elem: schemaCardDto},
		"count":       nil,
		"handCardIds": nil,
	}
	schemaNumberDecision.fields = map[string]*schema{
		"chosenNumber": nil,
	}
	schemaOwnDeckExtension.fields = map[string]*schema{
		"commanders": nil,
		"main":       &schema{kind: schemaList, elem: schemaOwnDeckRow},
		"name":       nil,
		"sideboard":  &schema{kind: schemaList, elem: schemaOwnDeckRow},
	}
	schemaOwnDeckRow.fields = map[string]*schema{
		"count": nil,
		"name":  nil,
	}
	schemaPassOutput.fields = map[string]*schema{
		"exhaustStack": nil,
		"until":        schemaPassUntil,
	}
	schemaPassUntil.fields = map[string]*schema{
		"phase":    nil,
		"playerId": nil,
	}
	schemaPayManaCostInput.fields = map[string]*schema{
		"actions":            &schema{kind: schemaList, elem: schemaPaymentAction},
		"canConfirmFromPool": nil,
		"cardId":             nil,
		"cardName":           nil,
		"manaCost":           nil,
		"presentation":       schemaPromptPresentation,
	}
	schemaPayOutput.fields = map[string]*schema{
		"auto": nil,
	}
	schemaPaymentAction.fields = map[string]*schema{
		"abilityIndex":  nil,
		"cardId":        nil,
		"description":   nil,
		"id":            nil,
		"isManaAbility": nil,
		"producedMana":  &schema{kind: schemaList, elem: schemaMana},
		"type":          nil,
	}
	schemaPlayerDto.fields = map[string]*schema{
		"activeSchemeNames":   nil,
		"cardsDrawnThisTurn":  nil,
		"commanderCasts":      nil,
		"commanderDamage":     nil,
		"controlledBy":        nil,
		"counters":            nil,
		"damagePrevention":    nil,
		"dungeonState":        nil,
		"extraTurnCount":      nil,
		"hasCityBlessing":     nil,
		"hasEnduringStory":    nil,
		"id":                  nil,
		"isExtraTurn":         nil,
		"isHuman":             nil,
		"landsPlayedThisTurn": nil,
		"life":                nil,
		"manaPool":            nil,
		"maxHandSize":         nil,
		"maxLandPlaysPerTurn": nil,
		"name":                nil,
		"playerKeywords":      nil,
		"ringLevel":           nil,
		"speed":               nil,
		"status":              nil,
		"teamNumber":          nil,
		"unlimitedHandSize":   nil,
		"unlimitedLandPlays":  nil,
	}
	schemaPromptBase.fields = map[string]*schema{
		"presentation": schemaPromptPresentation,
	}
	schemaPromptInput.fields = map[string]*schema{}
	schemaPromptMessage.fields = map[string]*schema{
		"decidingPlayerId": nil,
		"input":            schemaPromptInput,
		"kind":             nil,
		"promptId":         nil,
		"sourceCard":       schemaCardDto,
	}
	schemaPromptOutput.fields = map[string]*schema{
		"output": schemaPromptOutputData,
		"type":   nil,
	}
	schemaPromptOutputData.fields = map[string]*schema{}
	schemaPromptPresentation.fields = map[string]*schema{
		"description": nil,
		"targets":     &schema{kind: schemaList, elem: schemaTargetRef},
		"text":        nil,
		"title":       nil,
	}
	schemaProtocolError.fields = map[string]*schema{
		"code":     nil,
		"message":  nil,
		"promptId": nil,
	}
	schemaReorderDecision.fields = map[string]*schema{
		"orderedIds": nil,
	}
	schemaReorderInput.fields = map[string]*schema{
		"items":        &schema{kind: schemaList, elem: schemaReorderItem},
		"presentation": schemaPromptPresentation,
	}
	schemaReorderItem.fields = map[string]*schema{
		"card":   schemaCardDto,
		"id":     nil,
		"oracle": nil,
	}
	schemaRestoreSnapshotOutput.fields = map[string]*schema{
		"checkpointId": nil,
	}
	schemaRevealCardsAcknowledged.fields = map[string]*schema{}
	schemaRevealCardsInput.fields = map[string]*schema{
		"cards":         &schema{kind: schemaList, elem: schemaCardDto},
		"ownerPlayerId": nil,
		"presentation":  schemaPromptPresentation,
		"zone":          nil,
	}
	schemaSagaChapterDto.fields = map[string]*schema{
		"ability": nil,
		"chapter": nil,
	}
	schemaScryDecision.fields = map[string]*schema{
		"zoneCardIds": nil,
	}
	schemaScryInput.fields = map[string]*schema{
		"cards":        &schema{kind: schemaList, elem: schemaCardDto},
		"presentation": schemaPromptPresentation,
		"zones":        nil,
	}
	schemaSelectionDecision.fields = map[string]*schema{
		"chosenIndices": nil,
	}
	schemaSelectionOption.fields = map[string]*schema{
		"canRepeat": nil,
		"label":     nil,
		"weight":    nil,
	}
	schemaStackObjectDto.fields = map[string]*schema{
		"controllerId":      nil,
		"faceIndex":         nil,
		"id":                nil,
		"identity":          schemaCardIdentity,
		"isCasting":         nil,
		"isDoubleFaced":     nil,
		"isPermanentSpell":  nil,
		"ownerId":           nil,
		"sourceAbilityText": nil,
		"sourceId":          nil,
		"targets":           &schema{kind: schemaList, elem: schemaTargetRef},
		"text":              nil,
	}
	schemaStateDelta.fields = map[string]*schema{
		"base":        nil,
		"fingerprint": nil,
		"kind":        nil,
		"patch":       nil,
	}
	schemaStateUpdate.fields = map[string]*schema{
		"gameView": schemaGameViewDto,
		"kind":     nil,
	}
	schemaTargetRef.fields = map[string]*schema{
		"id":     nil,
		"intent": nil,
		"kind":   nil,
		"oracle": nil,
	}
	schemaVisibleCard.fields = map[string]*schema{
		"attachedTo":        nil,
		"attachmentIds":     nil,
		"attackTargetId":    nil,
		"attackingPlayerId": nil,
		"basePower":         nil,
		"baseToughness":     nil,
		"choices":           &schema{kind: schemaList, elem: schemaCardChoiceDto},
		"classLevel":        nil,
		"classLevels":       &schema{kind: schemaList, elem: schemaClassLevelDto},
		"cmc":               nil,
		"color":             nil,
		"commanderTax":      nil,
		"controllerId":      nil,
		"counters":          nil,
		"damage":            nil,
		"effectiveManaCost": nil,
		"exerted":           nil,
		"finalChapter":      nil,
		"flashbackCost":     nil,
		"foil":              nil,
		"id":                nil,
		"identity":          schemaCardIdentity,
		"isAttacking":       nil,
		"isBestowed":        nil,
		"isCopy":            nil,
		"isCrewed":          nil,
		"isDoubleFaced":     nil,
		"isFaceDown":        nil,
		"isMadnessExiled":   nil,
		"isPlotted":         nil,
		"isRingBearer":      nil,
		"isTransformed":     nil,
		"isWarpExiled":      nil,
		"keywords":          nil,
		"kickerCost":        nil,
		"madnessCost":       nil,
		"manaCost":          nil,
		"mergedCardIds":     nil,
		"ownerId":           nil,
		"phasedOut":         nil,
		"power":             nil,
		"sagaChapters":      &schema{kind: schemaList, elem: schemaSagaChapterDto},
		"subtypes":          nil,
		"summoningSick":     nil,
		"supertypes":        nil,
		"tapped":            nil,
		"text":              nil,
		"toughness":         nil,
		"types":             nil,
		"visibility":        nil,
		"wouldDieInCombat":  nil,
	}
	schemaZoneDto.fields = map[string]*schema{
		"cards":   &schema{kind: schemaList, elem: schemaCardView},
		"count":   nil,
		"ownerId": nil,
		"zone":    nil,
	}
	schemaschema.fields = map[string]*schema{}
}

// schemaOfTarget returns the schema of a Decode target: a non-nil pointer
// to one of this package's structs. ok is false for a nil pointer or any
// other type.
func schemaOfTarget(v any) (s *schema, ok bool) {
	switch x := v.(type) {
	case *ActOutput:
		return schemaActOutput, x != nil
	case *AgentPrompt:
		return schemaAgentPrompt, x != nil
	case *AttackTargetDto:
		return schemaAttackTargetDto, x != nil
	case *AttackerAssignment:
		return schemaAttackerAssignment, x != nil
	case *AttackerOptionDto:
		return schemaAttackerOptionDto, x != nil
	case *AvailableAction:
		return schemaAvailableAction, x != nil
	case *BlockableAttackerDto:
		return schemaBlockableAttackerDto, x != nil
	case *BlockerAssignment:
		return schemaBlockerAssignment, x != nil
	case *BoardTargetsDecision:
		return schemaBoardTargetsDecision, x != nil
	case *BooleanDecision:
		return schemaBooleanDecision, x != nil
	case *CancelOutput:
		return schemaCancelOutput, x != nil
	case *CardBackFaceSummary:
		return schemaCardBackFaceSummary, x != nil
	case *CardChoiceDto:
		return schemaCardChoiceDto, x != nil
	case *CardDto:
		return schemaCardDto, x != nil
	case *CardIdentity:
		return schemaCardIdentity, x != nil
	case *CardImageUris:
		return schemaCardImageUris, x != nil
	case *CardView:
		return schemaCardView, x != nil
	case *ChooseActionInput:
		return schemaChooseActionInput, x != nil
	case *ChooseAttackersInput:
		return schemaChooseAttackersInput, x != nil
	case *ChooseBlockersInput:
		return schemaChooseBlockersInput, x != nil
	case *ChooseBoardTargetsInput:
		return schemaChooseBoardTargetsInput, x != nil
	case *ChooseBooleanInput:
		return schemaChooseBooleanInput, x != nil
	case *ChooseCardsDecision:
		return schemaChooseCardsDecision, x != nil
	case *ChooseCardsInput:
		return schemaChooseCardsInput, x != nil
	case *ChooseColorInput:
		return schemaChooseColorInput, x != nil
	case *ChooseCombatDamageAssignmentInput:
		return schemaChooseCombatDamageAssignmentInput, x != nil
	case *ChooseDamageAssignmentOrderInput:
		return schemaChooseDamageAssignmentOrderInput, x != nil
	case *ChooseFromSelectionInput:
		return schemaChooseFromSelectionInput, x != nil
	case *ChooseNumberInput:
		return schemaChooseNumberInput, x != nil
	case *ClassLevelDto:
		return schemaClassLevelDto, x != nil
	case *ClientDirective:
		return schemaClientDirective, x != nil
	case *ClientMessage:
		return schemaClientMessage, x != nil
	case *ClientResponse:
		return schemaClientResponse, x != nil
	case *ColorDecision:
		return schemaColorDecision, x != nil
	case *CombatAssignmentDto:
		return schemaCombatAssignmentDto, x != nil
	case *DamageAssignment:
		return schemaDamageAssignment, x != nil
	case *DamageAssignmentDecision:
		return schemaDamageAssignmentDecision, x != nil
	case *DamageAssignmentOrderDecision:
		return schemaDamageAssignmentOrderDecision, x != nil
	case *Deck:
		return schemaDeck, x != nil
	case *DeckCard:
		return schemaDeckCard, x != nil
	case *DeckCardIdentity:
		return schemaDeckCardIdentity, x != nil
	case *DeckLabel:
		return schemaDeckLabel, x != nil
	case *DeclareAttackersDecision:
		return schemaDeclareAttackersDecision, x != nil
	case *DeclareBlockersDecision:
		return schemaDeclareBlockersDecision, x != nil
	case *DiceRollEntry:
		return schemaDiceRollEntry, x != nil
	case *DiceRolledAcknowledged:
		return schemaDiceRolledAcknowledged, x != nil
	case *DiceRolledInput:
		return schemaDiceRolledInput, x != nil
	case *DirectiveInput:
		return schemaDirectiveInput, x != nil
	case *DisplayMessage:
		return schemaDisplayMessage, x != nil
	case *EngineMessage:
		return schemaEngineMessage, x != nil
	case *ErrorMessage:
		return schemaErrorMessage, x != nil
	case *GameOverInput:
		return schemaGameOverInput, x != nil
	case *GameViewDto:
		return schemaGameViewDto, x != nil
	case *HiddenCard:
		return schemaHiddenCard, x != nil
	case *Mana:
		return schemaMana, x != nil
	case *MulliganDecision:
		return schemaMulliganDecision, x != nil
	case *MulliganInput:
		return schemaMulliganInput, x != nil
	case *MulliganPutBackDecision:
		return schemaMulliganPutBackDecision, x != nil
	case *MulliganPutBackInput:
		return schemaMulliganPutBackInput, x != nil
	case *NumberDecision:
		return schemaNumberDecision, x != nil
	case *OwnDeckExtension:
		return schemaOwnDeckExtension, x != nil
	case *OwnDeckRow:
		return schemaOwnDeckRow, x != nil
	case *PassOutput:
		return schemaPassOutput, x != nil
	case *PassUntil:
		return schemaPassUntil, x != nil
	case *PayManaCostInput:
		return schemaPayManaCostInput, x != nil
	case *PayOutput:
		return schemaPayOutput, x != nil
	case *PaymentAction:
		return schemaPaymentAction, x != nil
	case *PlayerDto:
		return schemaPlayerDto, x != nil
	case *PromptBase:
		return schemaPromptBase, x != nil
	case *PromptInput:
		return schemaPromptInput, x != nil
	case *PromptMessage:
		return schemaPromptMessage, x != nil
	case *PromptOutput:
		return schemaPromptOutput, x != nil
	case *PromptOutputData:
		return schemaPromptOutputData, x != nil
	case *PromptPresentation:
		return schemaPromptPresentation, x != nil
	case *ProtocolError:
		return schemaProtocolError, x != nil
	case *ReorderDecision:
		return schemaReorderDecision, x != nil
	case *ReorderInput:
		return schemaReorderInput, x != nil
	case *ReorderItem:
		return schemaReorderItem, x != nil
	case *RestoreSnapshotOutput:
		return schemaRestoreSnapshotOutput, x != nil
	case *RevealCardsAcknowledged:
		return schemaRevealCardsAcknowledged, x != nil
	case *RevealCardsInput:
		return schemaRevealCardsInput, x != nil
	case *SagaChapterDto:
		return schemaSagaChapterDto, x != nil
	case *ScryDecision:
		return schemaScryDecision, x != nil
	case *ScryInput:
		return schemaScryInput, x != nil
	case *SelectionDecision:
		return schemaSelectionDecision, x != nil
	case *SelectionOption:
		return schemaSelectionOption, x != nil
	case *StackObjectDto:
		return schemaStackObjectDto, x != nil
	case *StateDelta:
		return schemaStateDelta, x != nil
	case *StateUpdate:
		return schemaStateUpdate, x != nil
	case *TargetRef:
		return schemaTargetRef, x != nil
	case *VisibleCard:
		return schemaVisibleCard, x != nil
	case *ZoneDto:
		return schemaZoneDto, x != nil
	case *schema:
		return schemaschema, x != nil
	}
	return nil, false
}

// derefPromptInputData turns a pointer to a PromptInputData member (what the
// case tables allocate so json.Unmarshal has an addressable target) back into
// the value every consumer type-switches on. Anything else is returned as is.
func derefPromptInputData(v PromptInputData) PromptInputData {
	switch x := v.(type) {
	case *ChooseActionInput:
		if x != nil {
			return *x
		}
	case *ChooseAttackersInput:
		if x != nil {
			return *x
		}
	case *ChooseBlockersInput:
		if x != nil {
			return *x
		}
	case *ChooseBoardTargetsInput:
		if x != nil {
			return *x
		}
	case *ChooseBooleanInput:
		if x != nil {
			return *x
		}
	case *ChooseCardsInput:
		if x != nil {
			return *x
		}
	case *ChooseColorInput:
		if x != nil {
			return *x
		}
	case *ChooseCombatDamageAssignmentInput:
		if x != nil {
			return *x
		}
	case *ChooseDamageAssignmentOrderInput:
		if x != nil {
			return *x
		}
	case *ChooseFromSelectionInput:
		if x != nil {
			return *x
		}
	case *ChooseNumberInput:
		if x != nil {
			return *x
		}
	case *DiceRolledInput:
		if x != nil {
			return *x
		}
	case *GameOverInput:
		if x != nil {
			return *x
		}
	case *MulliganInput:
		if x != nil {
			return *x
		}
	case *MulliganPutBackInput:
		if x != nil {
			return *x
		}
	case *PayManaCostInput:
		if x != nil {
			return *x
		}
	case *ReorderInput:
		if x != nil {
			return *x
		}
	case *RevealCardsInput:
		if x != nil {
			return *x
		}
	case *ScryInput:
		if x != nil {
			return *x
		}
	}
	return v
}

// derefPromptOutputValue turns a pointer to a PromptOutputValue member (what the
// case tables allocate so json.Unmarshal has an addressable target) back into
// the value every consumer type-switches on. Anything else is returned as is.
func derefPromptOutputValue(v PromptOutputValue) PromptOutputValue {
	switch x := v.(type) {
	case *ActOutput:
		if x != nil {
			return *x
		}
	case *BoardTargetsDecision:
		if x != nil {
			return *x
		}
	case *BooleanDecision:
		if x != nil {
			return *x
		}
	case *CancelOutput:
		if x != nil {
			return *x
		}
	case *ChooseCardsDecision:
		if x != nil {
			return *x
		}
	case *ColorDecision:
		if x != nil {
			return *x
		}
	case *DamageAssignmentDecision:
		if x != nil {
			return *x
		}
	case *DamageAssignmentOrderDecision:
		if x != nil {
			return *x
		}
	case *DeclareAttackersDecision:
		if x != nil {
			return *x
		}
	case *DeclareBlockersDecision:
		if x != nil {
			return *x
		}
	case *DiceRolledAcknowledged:
		if x != nil {
			return *x
		}
	case *MulliganDecision:
		if x != nil {
			return *x
		}
	case *MulliganPutBackDecision:
		if x != nil {
			return *x
		}
	case *NumberDecision:
		if x != nil {
			return *x
		}
	case *PassOutput:
		if x != nil {
			return *x
		}
	case *PayOutput:
		if x != nil {
			return *x
		}
	case *ReorderDecision:
		if x != nil {
			return *x
		}
	case *RestoreSnapshotOutput:
		if x != nil {
			return *x
		}
	case *RevealCardsAcknowledged:
		if x != nil {
			return *x
		}
	case *ScryDecision:
		if x != nil {
			return *x
		}
	case *SelectionDecision:
		if x != nil {
			return *x
		}
	}
	return v
}
