#!/usr/bin/env python3
"""Generate gorge's SpellBench FDN Limited catalog from 17lands replay data.

The deck pool follows DraftZero's FDN definition (github.com/danieljbrooks/
draft-zero, tools/extract_decks.py --set FDN --format PremierDraft
--min-winrate 0.60): every main deck from the 17lands FDN PremierDraft replay
data whose player sits in the >= 60% game-win-rate bucket, one deck per
(draft_id, build_index). 17lands public data is CC BY 4.0; a deck list is card
names and counts only (no card text).

Outputs (both committed):
  internal/spellbench/fdn-cards.tsv        the FDN Limited card universe (the
                                           replay file's deck_* columns) with
                                           play-frequency weights
  internal/spellbench/decks/fdn-limited/   the fixed benchmark pool: -n decks
                                           chosen deterministically (sha256 of
                                           draft_id:build_index, ascending)

Usage:
  scripts/spellbench-fdn-catalog.py <replay_data_FDN_PremierDraft.csv[.gz]> [-n 16]
"""
import argparse
import collections
import csv
import gzip
import hashlib
import json
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SB = os.path.join(ROOT, "internal", "spellbench")
BASICS = {"Plains", "Island", "Swamp", "Mountain", "Forest"}


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("replay")
    ap.add_argument("-n", type=int, default=16)
    ap.add_argument("--min-winrate", type=float, default=0.60)
    a = ap.parse_args()
    csv.field_size_limit(10**9)
    op = gzip.open if a.replay.endswith(".gz") else open
    with op(a.replay, "rt", newline="") as fh:
        r = csv.reader(fh)
        h = next(r)
        ix = {k: i for i, k in enumerate(h)}
        deck_cols = [(i, k[5:]) for i, k in enumerate(h) if k.startswith("deck_")]
        builds = {}  # (draft_id, build_index) -> (wr, deck, colours)
        games = collections.Counter()
        for row in r:
            if len(row) != len(h) or row[ix["expansion"]] != "FDN" or row[ix["event_type"]] != "PremierDraft":
                continue
            key = (row[ix["draft_id"]], row[ix["build_index"]])
            games[key] += 1
            if key in builds:
                continue
            try:
                wr = float(row[ix["user_game_win_rate_bucket"]])
            except ValueError:
                wr = -1.0
            deck = {n: int(row[i]) for i, n in deck_cols if row[i] not in ("", "0")}
            colours = row[ix["main_colors"]] + (row[ix["splash_colors"]] or "")
            builds[key] = (wr, deck, colours)

    names = sorted(n for _, n in deck_cols)
    copies_all = collections.Counter()
    copies_wr = collections.Counter()
    decks_wr = collections.Counter()
    games_wr = collections.Counter()  # copies x games the build played
    for key, (wr, deck, _) in builds.items():
        for n, c in deck.items():
            copies_all[n] += c
            if wr >= a.min_winrate - 1e-9:
                copies_wr[n] += c
                decks_wr[n] += 1
                games_wr[n] += c * games[key]

    with open(os.path.join(SB, "fdn-cards.tsv"), "w") as out:
        out.write("# FDN Limited card universe: the deck_* columns of 17lands' FDN PremierDraft replay data (CC BY 4.0).\n")
        out.write("# Weights over %d distinct decks (draft_id, build_index); wr60 = the >= %.2f game-win-rate bucket (%d decks).\n"
                  % (len(builds), a.min_winrate, sum(1 for v in builds.values() if v[0] >= a.min_winrate - 1e-9)))
        out.write("# Generated by scripts/spellbench-fdn-catalog.py; do not edit by hand.\n")
        out.write("name\tbasic\tcopies_all\tcopies_wr60\tdecks_wr60\tgame_copies_wr60\n")
        for n in names:
            out.write("%s\t%d\t%d\t%d\t%d\t%d\n" % (n, n in BASICS, copies_all[n], copies_wr[n], decks_wr[n], games_wr[n]))

    pool = []
    for key, (wr, deck, colours) in builds.items():
        if wr < a.min_winrate - 1e-9 or sum(deck.values()) < 40:
            continue
        pool.append((hashlib.sha256(("%s:%s" % key).encode()).hexdigest(), key, deck, colours))
    pool.sort()
    ddir = os.path.join(SB, "decks", "fdn-limited")
    os.makedirs(ddir, exist_ok=True)
    for f in os.listdir(ddir):
        if f.endswith(".json"):
            os.remove(os.path.join(ddir, f))
    for i, (digest, key, deck, colours) in enumerate(pool[: a.n], 1):
        name = "FDN%02d-%s" % (i, colours or "C")
        doc = {
            "name": name,
            "format": "limited",
            "archetype": colours,
            "notes": "SpellBench FDN Limited catalog deck %s (mainboard, bo1). Source: 17lands FDN PremierDraft "
                     "replay data (CC BY 4.0), deck sha256(draft_id:build_index)=%s, player in the >= %.2f "
                     "game-win-rate bucket (the DraftZero FDN pool definition)." % (name, digest[:16], a.min_winrate),
            "cards": [{"name": n, "count": deck[n]} for n in sorted(deck)],
        }
        with open(os.path.join(ddir, name.lower() + ".json"), "w") as out:
            json.dump(doc, out, indent=1)
            out.write("\n")
    print("builds %d, wr60 decks %d, pool written %d" % (len(builds), len(pool), min(a.n, len(pool))), file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
