package searchprobe

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"reflect"
	"sort"
	"strings"
	"testing"

	"github.com/adams-shaun/gorge/view"
)

// canon_gen.go is generated from the reflective plan of view.View
// (canon_reflect_test.go) by genCanonEncoder. TestCanonGenIsCurrent
// regenerates it and fails when the committed file differs, so a field
// added to (or removed from, or retagged on) any type the view reaches
// cannot be silently dropped from the board digest: the build goes red
// until the encoder is regenerated with
//
//	CANON_REGEN=1 go test ./internal/searchprobe -run TestCanonGenIsCurrent
//
// and TestCanonGenIsReflective then holds the regenerated encoder to the
// reflective oracle byte for byte on real boards.

const canonGenFile = "canon_gen.go"

type canonGen struct {
	out     bytes.Buffer
	imports map[string]string // pkg path -> name
	funcs   map[*canonPlan]string
	queue   []*canonPlan
	tmp     int
}

func genCanonEncoder() ([]byte, error) {
	root := viewPlan()
	if u := root.unsupported(); len(u) != 0 {
		return nil, fmt.Errorf("unsupported nodes: %v", u)
	}
	g := &canonGen{imports: map[string]string{}, funcs: map[*canonPlan]string{}}
	g.funcName(root)
	var body bytes.Buffer
	for len(g.queue) > 0 {
		p := g.queue[0]
		g.queue = g.queue[1:]
		g.out.Reset()
		g.genStruct(p)
		body.Write(g.out.Bytes())
	}
	var head bytes.Buffer
	head.WriteString("// Code generated by genCanonEncoder (canon_gen_test.go); DO NOT EDIT.\n\npackage searchprobe\n\nimport (\n\t\"encoding/binary\"\n\t\"slices\"\n")
	paths := make([]string, 0, len(g.imports))
	for p := range g.imports {
		paths = append(paths, p)
	}
	sort.Strings(paths)
	for _, p := range paths {
		fmt.Fprintf(&head, "\t%q\n", p)
	}
	head.WriteString(")\n\n")
	fmt.Fprintf(&head, "// encodeView appends v's canonical encoding (canon.go).\nfunc (e *canonEncoder) encodeView(v *%s) error {\n\te.strKeys, e.intKeys, e.uKeys = e.strKeys[:0], e.intKeys[:0], e.uKeys[:0]\n\treturn e.%s(v)\n}\n\n", g.typeExpr(root.typ), g.funcs[root])
	head.Write(body.Bytes())
	return format.Source(head.Bytes())
}

func (g *canonGen) funcName(p *canonPlan) string {
	if n, ok := g.funcs[p]; ok {
		return n
	}
	t := p.typ
	if t.Name() == "" {
		panic("anonymous struct in the view: " + t.String())
	}
	n := "enc" + strings.ReplaceAll(t.String(), ".", "_")
	g.funcs[p] = n
	g.queue = append(g.queue, p)
	return n
}

func (g *canonGen) typeExpr(t reflect.Type) string {
	if t.Name() != "" {
		if t.PkgPath() == "" {
			return t.Name()
		}
		if t.PkgPath() == reflect.TypeFor[canonEncoder]().PkgPath() {
			return t.Name()
		}
		if !strings.Contains(t.String(), ".") || t.Name()[0] < 'A' || t.Name()[0] > 'Z' {
			panic("unexported type " + t.String())
		}
		g.imports[t.PkgPath()] = strings.SplitN(t.String(), ".", 2)[0]
		return t.String()
	}
	switch t.Kind() {
	case reflect.Slice:
		return "[]" + g.typeExpr(t.Elem())
	case reflect.Pointer:
		return "*" + g.typeExpr(t.Elem())
	case reflect.Array:
		return fmt.Sprintf("[%d]%s", t.Len(), g.typeExpr(t.Elem()))
	case reflect.Map:
		return "map[" + g.typeExpr(t.Key()) + "]" + g.typeExpr(t.Elem())
	}
	panic("type expression for " + t.String())
}

func (g *canonGen) p(format string, args ...any) { fmt.Fprintf(&g.out, format+"\n", args...) }

func (g *canonGen) v() string { g.tmp++; return fmt.Sprintf("x%d", g.tmp) }

func (g *canonGen) genStruct(p *canonPlan) {
	g.p("func (e *canonEncoder) %s(v *%s) error {", g.funcs[p], g.typeExpr(p.typ))
	for _, f := range p.fields {
		sf := p.typ.Field(f.index)
		expr := "v." + sf.Name
		if f.omitEmpty {
			g.p("if %s {\ne.buf = append(e.buf, 0)\n} else {\ne.buf = append(e.buf, 1)", g.emptyExpr(f.plan, expr))
			g.value(f.plan, expr)
			g.p("}")
		} else {
			g.value(f.plan, expr)
		}
	}
	g.p("return nil\n}\n")
}

// emptyExpr is encoding/json's isEmptyValue of expr.
func (g *canonGen) emptyExpr(p *canonPlan, expr string) string {
	switch p.kind {
	case canonBool:
		return "!" + expr
	case canonInt, canonUint, canonFloat:
		return expr + " == 0"
	case canonString, canonSlice, canonMap:
		return "len(" + expr + ") == 0"
	case canonArray:
		if p.n == 0 {
			return "true"
		}
		return "false"
	case canonPointer:
		return expr + " == nil"
	case canonStruct:
		return "false"
	}
	panic("empty of unsupported")
}

// value appends the encoding of expr (addressable for a struct) under p.
func (g *canonGen) value(p *canonPlan, expr string) {
	switch p.kind {
	case canonBool:
		g.p("if %s {\ne.buf = append(e.buf, 1)\n} else {\ne.buf = append(e.buf, 0)\n}", expr)
	case canonInt:
		g.p("e.buf = binary.AppendVarint(e.buf, int64(%s))", expr)
	case canonUint:
		g.p("e.buf = binary.AppendUvarint(e.buf, uint64(%s))", expr)
	case canonFloat:
		g.p("if err := e.appendFloat(float64(%s)); err != nil {\nreturn err\n}", expr)
	case canonString:
		g.p("e.appendString(string(%s))", expr)
	case canonStruct:
		g.p("if err := e.%s(&%s); err != nil {\nreturn err\n}", g.funcName(p), expr)
	case canonPointer:
		g.p("if %s == nil {\ne.buf = append(e.buf, 0)\n} else {\ne.buf = append(e.buf, 1)", expr)
		if p.elem.kind == canonStruct {
			g.p("if err := e.%s(%s); err != nil {\nreturn err\n}", g.funcName(p.elem), expr)
		} else {
			g.value(p.elem, "(*"+expr+")")
		}
		g.p("}")
	case canonSlice:
		g.p("if %s == nil {\ne.buf = append(e.buf, 0)\n} else {\ne.buf = append(e.buf, 1)", expr)
		g.list(p, expr)
		g.p("}")
	case canonArray:
		g.list(p, expr)
	case canonMap:
		g.mapValue(p, expr)
	default:
		panic("unsupported " + p.typ.String())
	}
}

func (g *canonGen) list(p *canonPlan, expr string) {
	i := g.v()
	g.p("e.buf = binary.AppendUvarint(e.buf, uint64(len(%s)))", expr)
	g.p("for %s := range %s {", i, expr)
	g.value(p.elem, expr+"["+i+"]")
	g.p("}")
}

// mapValue sorts the keys in e's key scratch as a stack frame (start..end),
// so a map nested in a map value sorts above it and truncates back.
func (g *canonGen) mapValue(p *canonPlan, expr string) {
	var scratch, conv, app string
	switch p.key {
	case canonString:
		scratch, conv, app = "e.strKeys", "string", "e.appendString(%s)"
	case canonInt:
		scratch, conv, app = "e.intKeys", "int64", "e.buf = binary.AppendVarint(e.buf, %s)"
	case canonUint:
		scratch, conv, app = "e.uKeys", "uint64", "e.buf = binary.AppendUvarint(e.buf, %s)"
	}
	kt := g.typeExpr(p.typ.Key())
	start, end, k, j, mv := g.v(), g.v(), g.v(), g.v(), g.v()
	g.p("if %s == nil {\ne.buf = append(e.buf, 0)\n} else {\ne.buf = append(e.buf, 1)", expr)
	g.p("e.buf = binary.AppendUvarint(e.buf, uint64(len(%s)))", expr)
	g.p("%s := len(%s)", start, scratch)
	g.p("for %s := range %s {\n%s = append(%s, %s(%s))\n}", k, expr, scratch, scratch, conv, k)
	g.p("%s := len(%s)", end, scratch)
	g.p("slices.Sort(%s[%s:%s])", scratch, start, end)
	g.p("for %s := %s; %s < %s; %s++ {", j, start, j, end, j)
	g.p("%s := %s[%s]", k, scratch, j)
	g.p(app, k)
	g.p("%s := %s[%s(%s)]", mv, expr, kt, k)
	g.value(p.elem, mv)
	g.p("}")
	if p.key == canonString {
		g.p("clear(%s[%s:%s])", scratch, start, end)
	}
	g.p("%s = %s[:%s]\n}", scratch, scratch, start)
}

// TestCanonGenIsCurrent: canon_gen.go is exactly what the generator emits
// from view.View's current shape (the dropped-field guard).
func TestCanonGenIsCurrent(t *testing.T) {
	want, err := genCanonEncoder()
	if err != nil {
		t.Fatal(err)
	}
	if os.Getenv("CANON_REGEN") == "1" {
		if err := os.WriteFile(canonGenFile, want, 0o644); err != nil {
			t.Fatal(err)
		}
		return
	}
	got, err := os.ReadFile(canonGenFile)
	if err != nil {
		t.Fatal(err)
	}
	if !bytes.Equal(got, want) {
		t.Fatalf("%s is stale against view.View's types: regenerate with CANON_REGEN=1 go test ./internal/searchprobe -run TestCanonGenIsCurrent", canonGenFile)
	}
}

// TestCanonGenCoversEveryField walks every struct type view.View reaches
// and requires its generated function to name every field the reflective
// plan encodes -- an independent count, in case the generator itself
// regresses.
func TestCanonGenCoversEveryField(t *testing.T) {
	src, err := os.ReadFile(canonGenFile)
	if err != nil {
		t.Fatal(err)
	}
	seen := map[*canonPlan]bool{}
	var walk func(p *canonPlan)
	structs := 0
	walk = func(p *canonPlan) {
		if seen[p] {
			return
		}
		seen[p] = true
		switch p.kind {
		case canonSlice, canonArray, canonPointer, canonMap:
			walk(p.elem)
		case canonStruct:
			structs++
			name := "enc" + strings.ReplaceAll(p.typ.String(), ".", "_")
			i := bytes.Index(src, []byte("func (e *canonEncoder) "+name+"("))
			if i < 0 {
				t.Fatalf("no generated encoder for %s", p.typ)
			}
			body := src[i:]
			if j := bytes.Index(body, []byte("\n}\n")); j >= 0 {
				body = body[:j]
			}
			exported := 0
			for k := 0; k < p.typ.NumField(); k++ {
				if f := p.typ.Field(k); f.IsExported() && f.Tag.Get("json") != "-" {
					exported++
				}
			}
			if exported != len(p.fields) {
				t.Fatalf("%s: %d encodable fields, plan has %d", p.typ, exported, len(p.fields))
			}
			for _, f := range p.fields {
				if !bytes.Contains(body, []byte("v."+p.typ.Field(f.index).Name)) {
					t.Fatalf("%s.%s is not encoded by %s", p.typ, p.typ.Field(f.index).Name, name)
				}
				walk(f.plan)
			}
		}
	}
	walk(viewPlan())
	t.Logf("%d struct types covered", structs)
	_ = view.View{}
}

// TestCanonGenIsReflective: across several real games (two-seat and
// four-seat, different decks, with and without potential actions), the
// generated encoder appends exactly the reflective oracle's bytes on every
// observed board (canonOf checks it), and does so without allocating once
// its scratch has grown.
func TestCanonGenIsReflective(t *testing.T) {
	games := []struct {
		seed  uint64
		names []string
	}{
		{30_000_002, []string{"mono-red-prowess", "mono-blue-tempo"}},
		{41, []string{"uw-control", "the-epic-storm"}},
		{77, []string{"death-n-taxes", "tron", "mono-green-stompy", "dimir-tempo"}},
	}
	boards := 0
	var gen canonEncoder
	for _, g := range games {
		views := canonGameViewsOf(t, 160, g.seed, g.names...)
		for i := range views {
			canonOf(t, &views[i])
			boards++
		}
		v := &views[len(views)/2]
		if err := gen.encodeView(v); err != nil {
			t.Fatal(err)
		}
		if n := testing.AllocsPerRun(20, func() { gen.buf = gen.buf[:0]; _ = gen.encodeView(v) }); n != 0 {
			t.Fatalf("encodeView allocates %.1f per call", n)
		}
	}
	t.Logf("%d boards byte-identical", boards)
}
