// Code generated by genCanonEncoder (canon_gen_test.go); DO NOT EDIT.

package searchprobe

import (
	"encoding/binary"
	"github.com/adams-shaun/gorge/cards"
	"github.com/adams-shaun/gorge/decision"
	"github.com/adams-shaun/gorge/deck"
	"github.com/adams-shaun/gorge/state"
	"github.com/adams-shaun/gorge/view"
	"slices"
)

// encodeView appends v's canonical encoding (canon.go).
func (e *canonEncoder) encodeView(v *view.View) error {
	e.strKeys, e.intKeys, e.uKeys = e.strKeys[:0], e.intKeys[:0], e.uKeys[:0]
	return e.encview_View(v)
}

func (e *canonEncoder) encview_View(v *view.View) error {
	e.buf = binary.AppendUvarint(e.buf, uint64(v.Viewer))
	if v.OwnDeck == nil {
		e.buf = append(e.buf, 0)
	} else {
		e.buf = append(e.buf, 1)
		if v.OwnDeck == nil {
			e.buf = append(e.buf, 0)
		} else {
			e.buf = append(e.buf, 1)
			if err := e.encdeck_Manifest(v.OwnDeck); err != nil {
				return err
			}
		}
	}
	e.appendString(string(v.Visibility))
	e.buf = binary.AppendVarint(e.buf, int64(v.Turn))
	e.buf = binary.AppendVarint(e.buf, int64(v.Round))
	e.appendString(string(v.Step))
	e.appendString(string(v.Phase))
	e.buf = binary.AppendUvarint(e.buf, uint64(v.Active))
	e.buf = binary.AppendUvarint(e.buf, uint64(v.Priority))
	if v.Over {
		e.buf = append(e.buf, 1)
	} else {
		e.buf = append(e.buf, 0)
	}
	if v.Draw {
		e.buf = append(e.buf, 1)
	} else {
		e.buf = append(e.buf, 0)
	}
	if v.Winner == nil {
		e.buf = append(e.buf, 0)
	} else {
		e.buf = append(e.buf, 1)
		e.buf = binary.AppendUvarint(e.buf, uint64((*v.Winner)))
	}
	if v.Players == nil {
		e.buf = append(e.buf, 0)
	} else {
		e.buf = append(e.buf, 1)
		e.buf = binary.AppendUvarint(e.buf, uint64(len(v.Players)))
		for x1 := range v.Players {
			if err := e.encview_PlayerView(&v.Players[x1]); err != nil {
				return err
			}
		}
	}
	if v.Stack == nil {
		e.buf = append(e.buf, 0)
	} else {
		e.buf = append(e.buf, 1)
		e.buf = binary.AppendUvarint(e.buf, uint64(len(v.Stack)))
		for x2 := range v.Stack {
			if err := e.encview_StackView(&v.Stack[x2]); err != nil {
				return err
			}
		}
	}
	if v.Pending == nil {
		e.buf = append(e.buf, 0)
	} else {
		e.buf = append(e.buf, 1)
		e.buf = binary.AppendUvarint(e.buf, uint64(len(v.Pending)))
		for x3 := range v.Pending {
			if err := e.encview_PendingView(&v.Pending[x3]); err != nil {
				return err
			}
		}
	}
	if v.Decision == nil {
		e.buf = append(e.buf, 0)
	} else {
		e.buf = append(e.buf, 1)
		if v.Decision == nil {
			e.buf = append(e.buf, 0)
		} else {
			e.buf = append(e.buf, 1)
			if err := e.encdecision_Decision(v.Decision); err != nil {
				return err
			}
		}
	}
	return nil
}

func (e *canonEncoder) encdeck_Manifest(v *deck.Manifest) error {
	e.appendString(string(v.Name))
	if len(v.Archetype) == 0 {
		e.buf = append(e.buf, 0)
	} else {
		e.buf = append(e.buf, 1)
		e.appendString(string(v.Archetype))
	}
	if v.Main == nil {
		e.buf = append(e.buf, 0)
	} else {
		e.buf = append(e.buf, 1)
		e.buf = binary.AppendUvarint(e.buf, uint64(len(v.Main)))
		for x4 := range v.Main {
			if err := e.encdeck_ManifestRow(&v.Main[x4]); err != nil {
				return err
			}
		}
	}
	if len(v.Sideboard) == 0 {
		e.buf = append(e.buf, 0)
	} else {
		e.buf = append(e.buf, 1)
		if v.Sideboard == nil {
			e.buf = append(e.buf, 0)
		} else {
			e.buf = append(e.buf, 1)
			e.buf = binary.AppendUvarint(e.buf, uint64(len(v.Sideboard)))
			for x5 := range v.Sideboard {
				if err := e.encdeck_ManifestRow(&v.Sideboard[x5]); err != nil {
					return err
				}
			}
		}
	}
	if len(v.Commanders) == 0 {
		e.buf = append(e.buf, 0)
	} else {
		e.buf = append(e.buf, 1)
		if v.Commanders == nil {
			e.buf = append(e.buf, 0)
		} else {
			e.buf = append(e.buf, 1)
			e.buf = binary.AppendUvarint(e.buf, uint64(len(v.Commanders)))
			for x6 := range v.Commanders {
				e.appendString(string(v.Commanders[x6]))
			}
		}
	}
	if len(v.Curve) == 0 {
		e.buf = append(e.buf, 0)
	} else {
		e.buf = append(e.buf, 1)
		if v.Curve == nil {
			e.buf = append(e.buf, 0)
		} else {
			e.buf = append(e.buf, 1)
			e.buf = binary.AppendUvarint(e.buf, uint64(len(v.Curve)))
			for x7 := range v.Curve {
				if err := e.encdeck_CurveRow(&v.Curve[x7]); err != nil {
					return err
				}
			}
		}
	}
	return nil
}

func (e *canonEncoder) encview_PlayerView(v *view.PlayerView) error {
	e.buf = binary.AppendUvarint(e.buf, uint64(v.ID))
	e.appendString(string(v.Name))
	e.buf = binary.AppendVarint(e.buf, int64(v.Life))
	if v.Lost {
		e.buf = append(e.buf, 1)
	} else {
		e.buf = append(e.buf, 0)
	}
	e.buf = binary.AppendVarint(e.buf, int64(v.LibrarySize))
	e.buf = binary.AppendVarint(e.buf, int64(v.HandSize))
	if len(v.PlanarDeck) == 0 {
		e.buf = append(e.buf, 0)
	} else {
		e.buf = append(e.buf, 1)
		if v.PlanarDeck == nil {
			e.buf = append(e.buf, 0)
		} else {
			e.buf = append(e.buf, 1)
			e.buf = binary.AppendUvarint(e.buf, uint64(len(v.PlanarDeck)))
			for x8 := range v.PlanarDeck {
				if err := e.encview_CardView(&v.PlanarDeck[x8]); err != nil {
					return err
				}
			}
		}
	}
	e.buf = binary.AppendVarint(e.buf, int64(v.GraveyardSize))
	if v.LibraryTop == nil {
		e.buf = append(e.buf, 0)
	} else {
		e.buf = append(e.buf, 1)
		if v.LibraryTop == nil {
			e.buf = append(e.buf, 0)
		} else {
			e.buf = append(e.buf, 1)
			if err := e.encview_CardView(v.LibraryTop); err != nil {
				return err
			}
		}
	}
	if len(v.Library) == 0 {
		e.buf = append(e.buf, 0)
	} else {
		e.buf = append(e.buf, 1)
		if v.Library == nil {
			e.buf = append(e.buf, 0)
		} else {
			e.buf = append(e.buf, 1)
			e.buf = binary.AppendUvarint(e.buf, uint64(len(v.Library)))
			for x9 := range v.Library {
				if err := e.encview_CardView(&v.Library[x9]); err != nil {
					return err
				}
			}
		}
	}
	if v.Hand == nil {
		e.buf = append(e.buf, 0)
	} else {
		e.buf = append(e.buf, 1)
		e.buf = binary.AppendUvarint(e.buf, uint64(len(v.Hand)))
		for x10 := range v.Hand {
			if err := e.encview_CardView(&v.Hand[x10]); err != nil {
				return err
			}
		}
	}
	if v.Battlefield == nil {
		e.buf = append(e.buf, 0)
	} else {
		e.buf = append(e.buf, 1)
		e.buf = binary.AppendUvarint(e.buf, uint64(len(v.Battlefield)))
		for x11 := range v.Battlefield {
			if err := e.encview_CardView(&v.Battlefield[x11]); err != nil {
				return err
			}
		}
	}
	if v.Graveyard == nil {
		e.buf = append(e.buf, 0)
	} else {
		e.buf = append(e.buf, 1)
		e.buf = binary.AppendUvarint(e.buf, uint64(len(v.Graveyard)))
		for x12 := range v.Graveyard {
			if err := e.encview_CardView(&v.Graveyard[x12]); err != nil {
				return err
			}
		}
	}
	if v.Exile == nil {
		e.buf = append(e.buf, 0)
	} else {
		e.buf = append(e.buf, 1)
		e.buf = binary.AppendUvarint(e.buf, uint64(len(v.Exile)))
		for x13 := range v.Exile {
			if err := e.encview_CardView(&v.Exile[x13]); err != nil {
				return err
			}
		}
	}
	if v.Pool == nil {
		e.buf = append(e.buf, 0)
	} else {
		e.buf = append(e.buf, 1)
		e.buf = binary.AppendUvarint(e.buf, uint64(len(v.Pool)))
		x14 := len(e.strKeys)
		for x16 := range v.Pool {
			e.strKeys = append(e.strKeys, string(x16))
		}
		x15 := len(e.strKeys)
		slices.Sort(e.strKeys[x14:x15])
		for x17 := x14; x17 < x15; x17++ {
			x16 := e.strKeys[x17]
			e.appendString(x16)
			x18 := v.Pool[string(x16)]
			e.buf = binary.AppendVarint(e.buf, int64(x18))
		}
		clear(e.strKeys[x14:x15])
		e.strKeys = e.strKeys[:x14]
	}
	if len(v.PoolRestrictions) == 0 {
		e.buf = append(e.buf, 0)
	} else {
		e.buf = append(e.buf, 1)
		if v.PoolRestrictions == nil {
			e.buf = append(e.buf, 0)
		} else {
			e.buf = append(e.buf, 1)
			e.buf = binary.AppendUvarint(e.buf, uint64(len(v.PoolRestrictions)))
			for x19 := range v.PoolRestrictions {
				if err := e.encview_PoolRestrictionView(&v.PoolRestrictions[x19]); err != nil {
					return err
				}
			}
		}
	}
	if len(v.PotentialActions) == 0 {
		e.buf = append(e.buf, 0)
	} else {
		e.buf = append(e.buf, 1)
		if v.PotentialActions == nil {
			e.buf = append(e.buf, 0)
		} else {
			e.buf = append(e.buf, 1)
			e.buf = binary.AppendUvarint(e.buf, uint64(len(v.PotentialActions)))
			for x20 := range v.PotentialActions {
				if err := e.encdecision_PotentialAction(&v.PotentialActions[x20]); err != nil {
					return err
				}
			}
		}
	}
	if len(v.Available) == 0 {
		e.buf = append(e.buf, 0)
	} else {
		e.buf = append(e.buf, 1)
		if v.Available == nil {
			e.buf = append(e.buf, 0)
		} else {
			e.buf = append(e.buf, 1)
			e.buf = binary.AppendUvarint(e.buf, uint64(len(v.Available)))
			x21 := len(e.strKeys)
			for x23 := range v.Available {
				e.strKeys = append(e.strKeys, string(x23))
			}
			x22 := len(e.strKeys)
			slices.Sort(e.strKeys[x21:x22])
			for x24 := x21; x24 < x22; x24++ {
				x23 := e.strKeys[x24]
				e.appendString(x23)
				x25 := v.Available[string(x23)]
				e.buf = binary.AppendVarint(e.buf, int64(x25))
			}
			clear(e.strKeys[x21:x22])
			e.strKeys = e.strKeys[:x21]
		}
	}
	if v.Command == nil {
		e.buf = append(e.buf, 0)
	} else {
		e.buf = append(e.buf, 1)
		e.buf = binary.AppendUvarint(e.buf, uint64(len(v.Command)))
		for x26 := range v.Command {
			if err := e.encview_CardView(&v.Command[x26]); err != nil {
				return err
			}
		}
	}
	if v.Commanders == nil {
		e.buf = append(e.buf, 0)
	} else {
		e.buf = append(e.buf, 1)
		e.buf = binary.AppendUvarint(e.buf, uint64(len(v.Commanders)))
		for x27 := range v.Commanders {
			if err := e.encview_CardView(&v.Commanders[x27]); err != nil {
				return err
			}
		}
	}
	if v.Dungeon == nil {
		e.buf = append(e.buf, 0)
	} else {
		e.buf = append(e.buf, 1)
		if v.Dungeon == nil {
			e.buf = append(e.buf, 0)
		} else {
			e.buf = append(e.buf, 1)
			if err := e.encview_DungeonView(v.Dungeon); err != nil {
				return err
			}
		}
	}
	e.buf = binary.AppendVarint(e.buf, int64(v.CompletedDungeons))
	if len(v.Counters) == 0 {
		e.buf = append(e.buf, 0)
	} else {
		e.buf = append(e.buf, 1)
		if v.Counters == nil {
			e.buf = append(e.buf, 0)
		} else {
			e.buf = append(e.buf, 1)
			e.buf = binary.AppendUvarint(e.buf, uint64(len(v.Counters)))
			x28 := len(e.strKeys)
			for x30 := range v.Counters {
				e.strKeys = append(e.strKeys, string(x30))
			}
			x29 := len(e.strKeys)
			slices.Sort(e.strKeys[x28:x29])
			for x31 := x28; x31 < x29; x31++ {
				x30 := e.strKeys[x31]
				e.appendString(x30)
				x32 := v.Counters[string(x30)]
				e.buf = binary.AppendVarint(e.buf, int64(x32))
			}
			clear(e.strKeys[x28:x29])
			e.strKeys = e.strKeys[:x28]
		}
	}
	if !v.LandDropSpent {
		e.buf = append(e.buf, 0)
	} else {
		e.buf = append(e.buf, 1)
		if v.LandDropSpent {
			e.buf = append(e.buf, 1)
		} else {
			e.buf = append(e.buf, 0)
		}
	}
	if !v.HasInitiative {
		e.buf = append(e.buf, 0)
	} else {
		e.buf = append(e.buf, 1)
		if v.HasInitiative {
			e.buf = append(e.buf, 1)
		} else {
			e.buf = append(e.buf, 0)
		}
	}
	if v.CommanderCasts == nil {
		e.buf = append(e.buf, 0)
	} else {
		e.buf = append(e.buf, 1)
		e.buf = binary.AppendUvarint(e.buf, uint64(len(v.CommanderCasts)))
		for x33 := range v.CommanderCasts {
			e.buf = binary.AppendVarint(e.buf, int64(v.CommanderCasts[x33]))
		}
	}
	if len(v.CmdDamage) == 0 {
		e.buf = append(e.buf, 0)
	} else {
		e.buf = append(e.buf, 1)
		if v.CmdDamage == nil {
			e.buf = append(e.buf, 0)
		} else {
			e.buf = append(e.buf, 1)
			e.buf = binary.AppendUvarint(e.buf, uint64(len(v.CmdDamage)))
			x34 := len(e.uKeys)
			for x36 := range v.CmdDamage {
				e.uKeys = append(e.uKeys, uint64(x36))
			}
			x35 := len(e.uKeys)
			slices.Sort(e.uKeys[x34:x35])
			for x37 := x34; x37 < x35; x37++ {
				x36 := e.uKeys[x37]
				e.buf = binary.AppendUvarint(e.buf, x36)
				x38 := v.CmdDamage[state.ObjID(x36)]
				e.buf = binary.AppendVarint(e.buf, int64(x38))
			}
			e.uKeys = e.uKeys[:x34]
		}
	}
	if v.Archetype == nil {
		e.buf = append(e.buf, 0)
	} else {
		e.buf = append(e.buf, 1)
		if v.Archetype == nil {
			e.buf = append(e.buf, 0)
		} else {
			e.buf = append(e.buf, 1)
			if err := e.encview_ArchetypePosterior(v.Archetype); err != nil {
				return err
			}
		}
	}
	return nil
}

func (e *canonEncoder) encview_StackView(v *view.StackView) error {
	e.buf = binary.AppendUvarint(e.buf, uint64(v.ID))
	e.appendString(string(v.Kind))
	e.appendString(string(v.Name))
	e.appendString(string(v.Text))
	e.buf = binary.AppendUvarint(e.buf, uint64(v.Controller))
	if v.Source == 0 {
		e.buf = append(e.buf, 0)
	} else {
		e.buf = append(e.buf, 1)
		e.buf = binary.AppendUvarint(e.buf, uint64(v.Source))
	}
	if v.Targets == nil {
		e.buf = append(e.buf, 0)
	} else {
		e.buf = append(e.buf, 1)
		e.buf = binary.AppendUvarint(e.buf, uint64(len(v.Targets)))
		for x39 := range v.Targets {
			if err := e.encview_TargetView(&v.Targets[x39]); err != nil {
				return err
			}
		}
	}
	if v.Card == nil {
		e.buf = append(e.buf, 0)
	} else {
		e.buf = append(e.buf, 1)
		if v.Card == nil {
			e.buf = append(e.buf, 0)
		} else {
			e.buf = append(e.buf, 1)
			if err := e.encview_CardView(v.Card); err != nil {
				return err
			}
		}
	}
	if v.Optional {
		e.buf = append(e.buf, 1)
	} else {
		e.buf = append(e.buf, 0)
	}
	if v.Decider == nil {
		e.buf = append(e.buf, 0)
	} else {
		e.buf = append(e.buf, 1)
		if v.Decider == nil {
			e.buf = append(e.buf, 0)
		} else {
			e.buf = append(e.buf, 1)
			e.buf = binary.AppendUvarint(e.buf, uint64((*v.Decider)))
		}
	}
	if v.X == 0 {
		e.buf = append(e.buf, 0)
	} else {
		e.buf = append(e.buf, 1)
		e.buf = binary.AppendVarint(e.buf, int64(v.X))
	}
	if v.Kicks == 0 {
		e.buf = append(e.buf, 0)
	} else {
		e.buf = append(e.buf, 1)
		e.buf = binary.AppendVarint(e.buf, int64(v.Kicks))
	}
	if len(v.Modes) == 0 {
		e.buf = append(e.buf, 0)
	} else {
		e.buf = append(e.buf, 1)
		if v.Modes == nil {
			e.buf = append(e.buf, 0)
		} else {
			e.buf = append(e.buf, 1)
			e.buf = binary.AppendUvarint(e.buf, uint64(len(v.Modes)))
			for x40 := range v.Modes {
				e.appendString(string(v.Modes[x40]))
			}
		}
	}
	return nil
}

func (e *canonEncoder) encview_PendingView(v *view.PendingView) error {
	e.buf = binary.AppendUvarint(e.buf, uint64(v.Source))
	e.buf = binary.AppendUvarint(e.buf, uint64(v.Controller))
	e.appendString(string(v.Label))
	if v.Optional {
		e.buf = append(e.buf, 1)
	} else {
		e.buf = append(e.buf, 0)
	}
	if v.Decider == nil {
		e.buf = append(e.buf, 0)
	} else {
		e.buf = append(e.buf, 1)
		if v.Decider == nil {
			e.buf = append(e.buf, 0)
		} else {
			e.buf = append(e.buf, 1)
			e.buf = binary.AppendUvarint(e.buf, uint64((*v.Decider)))
		}
	}
	return nil
}

func (e *canonEncoder) encdecision_Decision(v *decision.Decision) error {
	e.buf = binary.AppendUvarint(e.buf, uint64(v.Seq))
	e.buf = binary.AppendUvarint(e.buf, uint64(v.Player))
	e.appendString(string(v.Kind))
	e.appendString(string(v.Prompt))
	e.buf = binary.AppendVarint(e.buf, int64(v.Min))
	e.buf = binary.AppendVarint(e.buf, int64(v.Max))
	if v.Options == nil {
		e.buf = append(e.buf, 0)
	} else {
		e.buf = append(e.buf, 1)
		e.buf = binary.AppendUvarint(e.buf, uint64(len(v.Options)))
		for x41 := range v.Options {
			if err := e.encdecision_Option(&v.Options[x41]); err != nil {
				return err
			}
		}
	}
	if len(v.WindowReasons) == 0 {
		e.buf = append(e.buf, 0)
	} else {
		e.buf = append(e.buf, 1)
		if v.WindowReasons == nil {
			e.buf = append(e.buf, 0)
		} else {
			e.buf = append(e.buf, 1)
			e.buf = binary.AppendUvarint(e.buf, uint64(len(v.WindowReasons)))
			for x42 := range v.WindowReasons {
				if err := e.encdecision_WindowReason(&v.WindowReasons[x42]); err != nil {
					return err
				}
			}
		}
	}
	if len(v.PaymentActions) == 0 {
		e.buf = append(e.buf, 0)
	} else {
		e.buf = append(e.buf, 1)
		if v.PaymentActions == nil {
			e.buf = append(e.buf, 0)
		} else {
			e.buf = append(e.buf, 1)
			e.buf = binary.AppendUvarint(e.buf, uint64(len(v.PaymentActions)))
			for x43 := range v.PaymentActions {
				if err := e.encdecision_PaymentAction(&v.PaymentActions[x43]); err != nil {
					return err
				}
			}
		}
	}
	if v.PaymentFallback == nil {
		e.buf = append(e.buf, 0)
	} else {
		e.buf = append(e.buf, 1)
		if v.PaymentFallback == nil {
			e.buf = append(e.buf, 0)
		} else {
			e.buf = append(e.buf, 1)
			if err := e.encdecision_PaymentFallback(v.PaymentFallback); err != nil {
				return err
			}
		}
	}
	if v.ManaPayment == nil {
		e.buf = append(e.buf, 0)
	} else {
		e.buf = append(e.buf, 1)
		if v.ManaPayment == nil {
			e.buf = append(e.buf, 0)
		} else {
			e.buf = append(e.buf, 1)
			if err := e.encdecision_ManaPaymentWindow(v.ManaPayment); err != nil {
				return err
			}
		}
	}
	if v.MaxSum == 0 {
		e.buf = append(e.buf, 0)
	} else {
		e.buf = append(e.buf, 1)
		e.buf = binary.AppendVarint(e.buf, int64(v.MaxSum))
	}
	if !v.Budgeted {
		e.buf = append(e.buf, 0)
	} else {
		e.buf = append(e.buf, 1)
		if v.Budgeted {
			e.buf = append(e.buf, 1)
		} else {
			e.buf = append(e.buf, 0)
		}
	}
	if v.MaxSum2 == 0 {
		e.buf = append(e.buf, 0)
	} else {
		e.buf = append(e.buf, 1)
		e.buf = binary.AppendVarint(e.buf, int64(v.MaxSum2))
	}
	if !v.Budgeted2 {
		e.buf = append(e.buf, 0)
	} else {
		e.buf = append(e.buf, 1)
		if v.Budgeted2 {
			e.buf = append(e.buf, 1)
		} else {
			e.buf = append(e.buf, 0)
		}
	}
	if v.PayerLife == 0 {
		e.buf = append(e.buf, 0)
	} else {
		e.buf = append(e.buf, 1)
		e.buf = binary.AppendVarint(e.buf, int64(v.PayerLife))
	}
	if v.ChargeTapPool == 0 {
		e.buf = append(e.buf, 0)
	} else {
		e.buf = append(e.buf, 1)
		e.buf = binary.AppendVarint(e.buf, int64(v.ChargeTapPool))
	}
	if v.MinSum == 0 {
		e.buf = append(e.buf, 0)
	} else {
		e.buf = append(e.buf, 1)
		e.buf = binary.AppendVarint(e.buf, int64(v.MinSum))
	}
	if v.GroupLimit == 0 {
		e.buf = append(e.buf, 0)
	} else {
		e.buf = append(e.buf, 1)
		e.buf = binary.AppendVarint(e.buf, int64(v.GroupLimit))
	}
	if len(v.GroupLimits) == 0 {
		e.buf = append(e.buf, 0)
	} else {
		e.buf = append(e.buf, 1)
		if v.GroupLimits == nil {
			e.buf = append(e.buf, 0)
		} else {
			e.buf = append(e.buf, 1)
			e.buf = binary.AppendUvarint(e.buf, uint64(len(v.GroupLimits)))
			x44 := len(e.strKeys)
			for x46 := range v.GroupLimits {
				e.strKeys = append(e.strKeys, string(x46))
			}
			x45 := len(e.strKeys)
			slices.Sort(e.strKeys[x44:x45])
			for x47 := x44; x47 < x45; x47++ {
				x46 := e.strKeys[x47]
				e.appendString(x46)
				x48 := v.GroupLimits[string(x46)]
				e.buf = binary.AppendVarint(e.buf, int64(x48))
			}
			clear(e.strKeys[x44:x45])
			e.strKeys = e.strKeys[:x44]
		}
	}
	if !v.Repeatable {
		e.buf = append(e.buf, 0)
	} else {
		e.buf = append(e.buf, 1)
		if v.Repeatable {
			e.buf = append(e.buf, 1)
		} else {
			e.buf = append(e.buf, 0)
		}
	}
	if !v.DistinctTypePicks {
		e.buf = append(e.buf, 0)
	} else {
		e.buf = append(e.buf, 1)
		if v.DistinctTypePicks {
			e.buf = append(e.buf, 1)
		} else {
			e.buf = append(e.buf, 0)
		}
	}
	if !v.AllowNone {
		e.buf = append(e.buf, 0)
	} else {
		e.buf = append(e.buf, 1)
		if v.AllowNone {
			e.buf = append(e.buf, 1)
		} else {
			e.buf = append(e.buf, 0)
		}
	}
	if v.Source == 0 {
		e.buf = append(e.buf, 0)
	} else {
		e.buf = append(e.buf, 1)
		e.buf = binary.AppendUvarint(e.buf, uint64(v.Source))
	}
	if v.TargetEffect == nil {
		e.buf = append(e.buf, 0)
	} else {
		e.buf = append(e.buf, 1)
		if v.TargetEffect == nil {
			e.buf = append(e.buf, 0)
		} else {
			e.buf = append(e.buf, 1)
			if err := e.encdecision_TargetEffect(v.TargetEffect); err != nil {
				return err
			}
		}
	}
	if !v.Restable {
		e.buf = append(e.buf, 0)
	} else {
		e.buf = append(e.buf, 1)
		if v.Restable {
			e.buf = append(e.buf, 1)
		} else {
			e.buf = append(e.buf, 0)
		}
	}
	return nil
}

func (e *canonEncoder) encdeck_ManifestRow(v *deck.ManifestRow) error {
	e.appendString(string(v.Name))
	e.buf = binary.AppendVarint(e.buf, int64(v.Count))
	if !v.Land {
		e.buf = append(e.buf, 0)
	} else {
		e.buf = append(e.buf, 1)
		if v.Land {
			e.buf = append(e.buf, 1)
		} else {
			e.buf = append(e.buf, 0)
		}
	}
	return nil
}

func (e *canonEncoder) encdeck_CurveRow(v *deck.CurveRow) error {
	e.buf = binary.AppendVarint(e.buf, int64(v.CMC))
	e.buf = binary.AppendVarint(e.buf, int64(v.Count))
	return nil
}

func (e *canonEncoder) encview_CardView(v *view.CardView) error {
	e.buf = binary.AppendUvarint(e.buf, uint64(v.ID))
	e.appendString(string(v.Name))
	if len(v.CardName) == 0 {
		e.buf = append(e.buf, 0)
	} else {
		e.buf = append(e.buf, 1)
		e.appendString(string(v.CardName))
	}
	if !v.FaceDown {
		e.buf = append(e.buf, 0)
	} else {
		e.buf = append(e.buf, 1)
		if v.FaceDown {
			e.buf = append(e.buf, 1)
		} else {
			e.buf = append(e.buf, 0)
		}
	}
	e.appendString(string(v.Types))
	if len(v.ManaCost) == 0 {
		e.buf = append(e.buf, 0)
	} else {
		e.buf = append(e.buf, 1)
		e.appendString(string(v.ManaCost))
	}
	if len(v.EffectiveManaCost) == 0 {
		e.buf = append(e.buf, 0)
	} else {
		e.buf = append(e.buf, 1)
		e.appendString(string(v.EffectiveManaCost))
	}
	if len(v.SpellAPI) == 0 {
		e.buf = append(e.buf, 0)
	} else {
		e.buf = append(e.buf, 1)
		e.appendString(string(v.SpellAPI))
	}
	if err := e.encview_Printing(&v.Printing); err != nil {
		return err
	}
	e.appendString(string(v.Token))
	if !v.IsToken {
		e.buf = append(e.buf, 0)
	} else {
		e.buf = append(e.buf, 1)
		if v.IsToken {
			e.buf = append(e.buf, 1)
		} else {
			e.buf = append(e.buf, 0)
		}
	}
	if !v.IsCopy {
		e.buf = append(e.buf, 0)
	} else {
		e.buf = append(e.buf, 1)
		if v.IsCopy {
			e.buf = append(e.buf, 1)
		} else {
			e.buf = append(e.buf, 0)
		}
	}
	if v.AttackingPlayer == nil {
		e.buf = append(e.buf, 0)
	} else {
		e.buf = append(e.buf, 1)
		if v.AttackingPlayer == nil {
			e.buf = append(e.buf, 0)
		} else {
			e.buf = append(e.buf, 1)
			e.buf = binary.AppendUvarint(e.buf, uint64((*v.AttackingPlayer)))
		}
	}
	if len(v.BlockedBy) == 0 {
		e.buf = append(e.buf, 0)
	} else {
		e.buf = append(e.buf, 1)
		if v.BlockedBy == nil {
			e.buf = append(e.buf, 0)
		} else {
			e.buf = append(e.buf, 1)
			e.buf = binary.AppendUvarint(e.buf, uint64(len(v.BlockedBy)))
			for x49 := range v.BlockedBy {
				e.buf = binary.AppendUvarint(e.buf, uint64(v.BlockedBy[x49]))
			}
		}
	}
	if v.Tapped {
		e.buf = append(e.buf, 1)
	} else {
		e.buf = append(e.buf, 0)
	}
	e.buf = binary.AppendVarint(e.buf, int64(v.Power))
	e.buf = binary.AppendVarint(e.buf, int64(v.Toughness))
	e.buf = binary.AppendVarint(e.buf, int64(v.Damage))
	if v.Attacking {
		e.buf = append(e.buf, 1)
	} else {
		e.buf = append(e.buf, 0)
	}
	if len(v.Counters) == 0 {
		e.buf = append(e.buf, 0)
	} else {
		e.buf = append(e.buf, 1)
		if v.Counters == nil {
			e.buf = append(e.buf, 0)
		} else {
			e.buf = append(e.buf, 1)
			e.buf = binary.AppendUvarint(e.buf, uint64(len(v.Counters)))
			x50 := len(e.strKeys)
			for x52 := range v.Counters {
				e.strKeys = append(e.strKeys, string(x52))
			}
			x51 := len(e.strKeys)
			slices.Sort(e.strKeys[x50:x51])
			for x53 := x50; x53 < x51; x53++ {
				x52 := e.strKeys[x53]
				e.appendString(x52)
				x54 := v.Counters[string(x52)]
				e.buf = binary.AppendVarint(e.buf, int64(x54))
			}
			clear(e.strKeys[x50:x51])
			e.strKeys = e.strKeys[:x50]
		}
	}
	if len(v.Keywords) == 0 {
		e.buf = append(e.buf, 0)
	} else {
		e.buf = append(e.buf, 1)
		if v.Keywords == nil {
			e.buf = append(e.buf, 0)
		} else {
			e.buf = append(e.buf, 1)
			e.buf = binary.AppendUvarint(e.buf, uint64(len(v.Keywords)))
			for x55 := range v.Keywords {
				e.appendString(string(v.Keywords[x55]))
			}
		}
	}
	e.buf = binary.AppendUvarint(e.buf, uint64(v.Controller))
	e.buf = binary.AppendUvarint(e.buf, uint64(v.Owner))
	if v.SummonSick {
		e.buf = append(e.buf, 1)
	} else {
		e.buf = append(e.buf, 0)
	}
	if v.AttachedTo == 0 {
		e.buf = append(e.buf, 0)
	} else {
		e.buf = append(e.buf, 1)
		e.buf = binary.AppendUvarint(e.buf, uint64(v.AttachedTo))
	}
	if v.ActivatedThisTurn == 0 {
		e.buf = append(e.buf, 0)
	} else {
		e.buf = append(e.buf, 1)
		e.buf = binary.AppendVarint(e.buf, int64(v.ActivatedThisTurn))
	}
	if len(v.AbilityCosts) == 0 {
		e.buf = append(e.buf, 0)
	} else {
		e.buf = append(e.buf, 1)
		if v.AbilityCosts == nil {
			e.buf = append(e.buf, 0)
		} else {
			e.buf = append(e.buf, 1)
			e.buf = binary.AppendUvarint(e.buf, uint64(len(v.AbilityCosts)))
			for x56 := range v.AbilityCosts {
				e.appendString(string(v.AbilityCosts[x56]))
			}
		}
	}
	if v.Produces == nil {
		e.buf = append(e.buf, 0)
	} else {
		e.buf = append(e.buf, 1)
		if v.Produces == nil {
			e.buf = append(e.buf, 0)
		} else {
			e.buf = append(e.buf, 1)
			if err := e.enccards_ManaProduction(v.Produces); err != nil {
				return err
			}
		}
	}
	if v.Flags == 0 {
		e.buf = append(e.buf, 0)
	} else {
		e.buf = append(e.buf, 1)
		e.buf = binary.AppendUvarint(e.buf, uint64(v.Flags))
	}
	if len(v.Imprinted) == 0 {
		e.buf = append(e.buf, 0)
	} else {
		e.buf = append(e.buf, 1)
		if v.Imprinted == nil {
			e.buf = append(e.buf, 0)
		} else {
			e.buf = append(e.buf, 1)
			e.buf = binary.AppendUvarint(e.buf, uint64(len(v.Imprinted)))
			for x57 := range v.Imprinted {
				e.buf = binary.AppendUvarint(e.buf, uint64(v.Imprinted[x57]))
			}
		}
	}
	if v.Paired == 0 {
		e.buf = append(e.buf, 0)
	} else {
		e.buf = append(e.buf, 1)
		e.buf = binary.AppendUvarint(e.buf, uint64(v.Paired))
	}
	if len(v.ExiledCards) == 0 {
		e.buf = append(e.buf, 0)
	} else {
		e.buf = append(e.buf, 1)
		if v.ExiledCards == nil {
			e.buf = append(e.buf, 0)
		} else {
			e.buf = append(e.buf, 1)
			e.buf = binary.AppendUvarint(e.buf, uint64(len(v.ExiledCards)))
			for x58 := range v.ExiledCards {
				e.buf = binary.AppendUvarint(e.buf, uint64(v.ExiledCards[x58]))
			}
		}
	}
	if !v.AttachedToPlayer {
		e.buf = append(e.buf, 0)
	} else {
		e.buf = append(e.buf, 1)
		if v.AttachedToPlayer {
			e.buf = append(e.buf, 1)
		} else {
			e.buf = append(e.buf, 0)
		}
	}
	if v.AttachedPlayer == 0 {
		e.buf = append(e.buf, 0)
	} else {
		e.buf = append(e.buf, 1)
		e.buf = binary.AppendUvarint(e.buf, uint64(v.AttachedPlayer))
	}
	return nil
}

func (e *canonEncoder) encview_PoolRestrictionView(v *view.PoolRestrictionView) error {
	e.appendString(string(v.Color))
	e.buf = binary.AppendVarint(e.buf, int64(v.Amount))
	e.appendString(string(v.Text))
	return nil
}

func (e *canonEncoder) encdecision_PotentialAction(v *decision.PotentialAction) error {
	e.appendString(string(v.Kind))
	if v.Obj == 0 {
		e.buf = append(e.buf, 0)
	} else {
		e.buf = append(e.buf, 1)
		e.buf = binary.AppendUvarint(e.buf, uint64(v.Obj))
	}
	if v.Ability == 0 {
		e.buf = append(e.buf, 0)
	} else {
		e.buf = append(e.buf, 1)
		e.buf = binary.AppendVarint(e.buf, int64(v.Ability))
	}
	if len(v.Mode) == 0 {
		e.buf = append(e.buf, 0)
	} else {
		e.buf = append(e.buf, 1)
		e.appendString(string(v.Mode))
	}
	if len(v.Label) == 0 {
		e.buf = append(e.buf, 0)
	} else {
		e.buf = append(e.buf, 1)
		e.appendString(string(v.Label))
	}
	if v.Payable == nil {
		e.buf = append(e.buf, 0)
	} else {
		e.buf = append(e.buf, 1)
		if v.Payable == nil {
			e.buf = append(e.buf, 0)
		} else {
			e.buf = append(e.buf, 1)
			if *v.Payable {
				e.buf = append(e.buf, 1)
			} else {
				e.buf = append(e.buf, 0)
			}
		}
	}
	return nil
}

func (e *canonEncoder) encview_DungeonView(v *view.DungeonView) error {
	e.appendString(string(v.Name))
	e.appendString(string(v.Room))
	return nil
}

func (e *canonEncoder) encview_ArchetypePosterior(v *view.ArchetypePosterior) error {
	if v.Known {
		e.buf = append(e.buf, 1)
	} else {
		e.buf = append(e.buf, 0)
	}
	e.buf = binary.AppendVarint(e.buf, int64(v.Seen))
	if len(v.Top) == 0 {
		e.buf = append(e.buf, 0)
	} else {
		e.buf = append(e.buf, 1)
		e.appendString(string(v.Top))
	}
	if v.TopScore == 0 {
		e.buf = append(e.buf, 0)
	} else {
		e.buf = append(e.buf, 1)
		if err := e.appendFloat(float64(v.TopScore)); err != nil {
			return err
		}
	}
	if len(v.Scores) == 0 {
		e.buf = append(e.buf, 0)
	} else {
		e.buf = append(e.buf, 1)
		if v.Scores == nil {
			e.buf = append(e.buf, 0)
		} else {
			e.buf = append(e.buf, 1)
			e.buf = binary.AppendUvarint(e.buf, uint64(len(v.Scores)))
			x59 := len(e.strKeys)
			for x61 := range v.Scores {
				e.strKeys = append(e.strKeys, string(x61))
			}
			x60 := len(e.strKeys)
			slices.Sort(e.strKeys[x59:x60])
			for x62 := x59; x62 < x60; x62++ {
				x61 := e.strKeys[x62]
				e.appendString(x61)
				x63 := v.Scores[string(x61)]
				if err := e.appendFloat(float64(x63)); err != nil {
					return err
				}
			}
			clear(e.strKeys[x59:x60])
			e.strKeys = e.strKeys[:x59]
		}
	}
	return nil
}

func (e *canonEncoder) encview_TargetView(v *view.TargetView) error {
	if v.Obj == 0 {
		e.buf = append(e.buf, 0)
	} else {
		e.buf = append(e.buf, 1)
		e.buf = binary.AppendUvarint(e.buf, uint64(v.Obj))
	}
	e.buf = binary.AppendUvarint(e.buf, uint64(v.Player))
	if v.IsPlayer {
		e.buf = append(e.buf, 1)
	} else {
		e.buf = append(e.buf, 0)
	}
	if len(v.Label) == 0 {
		e.buf = append(e.buf, 0)
	} else {
		e.buf = append(e.buf, 1)
		e.appendString(string(v.Label))
	}
	return nil
}

func (e *canonEncoder) encdecision_Option(v *decision.Option) error {
	e.buf = binary.AppendVarint(e.buf, int64(v.Index))
	e.appendString(string(v.Kind))
	e.appendString(string(v.Label))
	if v.Obj == 0 {
		e.buf = append(e.buf, 0)
	} else {
		e.buf = append(e.buf, 1)
		e.buf = binary.AppendUvarint(e.buf, uint64(v.Obj))
	}
	if len(v.ManaSymbol) == 0 {
		e.buf = append(e.buf, 0)
	} else {
		e.buf = append(e.buf, 1)
		e.appendString(string(v.ManaSymbol))
	}
	if len(v.Counter) == 0 {
		e.buf = append(e.buf, 0)
	} else {
		e.buf = append(e.buf, 1)
		e.appendString(string(v.Counter))
	}
	e.buf = binary.AppendUvarint(e.buf, uint64(v.Player))
	if v.Attacker == 0 {
		e.buf = append(e.buf, 0)
	} else {
		e.buf = append(e.buf, 1)
		e.buf = binary.AppendUvarint(e.buf, uint64(v.Attacker))
	}
	if v.Battle == 0 {
		e.buf = append(e.buf, 0)
	} else {
		e.buf = append(e.buf, 1)
		e.buf = binary.AppendUvarint(e.buf, uint64(v.Battle))
	}
	if !v.Required {
		e.buf = append(e.buf, 0)
	} else {
		e.buf = append(e.buf, 1)
		if v.Required {
			e.buf = append(e.buf, 1)
		} else {
			e.buf = append(e.buf, 0)
		}
	}
	if v.MinBlockers == 0 {
		e.buf = append(e.buf, 0)
	} else {
		e.buf = append(e.buf, 1)
		e.buf = binary.AppendVarint(e.buf, int64(v.MinBlockers))
	}
	if v.MaxBlockers == 0 {
		e.buf = append(e.buf, 0)
	} else {
		e.buf = append(e.buf, 1)
		e.buf = binary.AppendVarint(e.buf, int64(v.MaxBlockers))
	}
	if len(v.Group) == 0 {
		e.buf = append(e.buf, 0)
	} else {
		e.buf = append(e.buf, 1)
		e.appendString(string(v.Group))
	}
	if v.AltCostIndex == 0 {
		e.buf = append(e.buf, 0)
	} else {
		e.buf = append(e.buf, 1)
		e.buf = binary.AppendVarint(e.buf, int64(v.AltCostIndex))
	}
	if v.CostLife == 0 {
		e.buf = append(e.buf, 0)
	} else {
		e.buf = append(e.buf, 1)
		e.buf = binary.AppendVarint(e.buf, int64(v.CostLife))
	}
	if v.CostTaps == 0 {
		e.buf = append(e.buf, 0)
	} else {
		e.buf = append(e.buf, 1)
		e.buf = binary.AppendVarint(e.buf, int64(v.CostTaps))
	}
	if v.CostPhyrexian == 0 {
		e.buf = append(e.buf, 0)
	} else {
		e.buf = append(e.buf, 1)
		e.buf = binary.AppendVarint(e.buf, int64(v.CostPhyrexian))
	}
	if v.TapPoolCost == 0 {
		e.buf = append(e.buf, 0)
	} else {
		e.buf = append(e.buf, 1)
		e.buf = binary.AppendVarint(e.buf, int64(v.TapPoolCost))
	}
	if len(v.Mode) == 0 {
		e.buf = append(e.buf, 0)
	} else {
		e.buf = append(e.buf, 1)
		e.appendString(string(v.Mode))
	}
	if v.Amount == 0 {
		e.buf = append(e.buf, 0)
	} else {
		e.buf = append(e.buf, 1)
		e.buf = binary.AppendVarint(e.buf, int64(v.Amount))
	}
	if v.Ability == 0 {
		e.buf = append(e.buf, 0)
	} else {
		e.buf = append(e.buf, 1)
		e.buf = binary.AppendVarint(e.buf, int64(v.Ability))
	}
	if len(v.SVar) == 0 {
		e.buf = append(e.buf, 0)
	} else {
		e.buf = append(e.buf, 1)
		e.appendString(string(v.SVar))
	}
	if len(v.Keyword) == 0 {
		e.buf = append(e.buf, 0)
	} else {
		e.buf = append(e.buf, 1)
		e.appendString(string(v.Keyword))
	}
	if len(v.Cost) == 0 {
		e.buf = append(e.buf, 0)
	} else {
		e.buf = append(e.buf, 1)
		e.appendString(string(v.Cost))
	}
	if v.Value == 0 {
		e.buf = append(e.buf, 0)
	} else {
		e.buf = append(e.buf, 1)
		e.buf = binary.AppendVarint(e.buf, int64(v.Value))
	}
	if v.Value2 == 0 {
		e.buf = append(e.buf, 0)
	} else {
		e.buf = append(e.buf, 1)
		e.buf = binary.AppendVarint(e.buf, int64(v.Value2))
	}
	return nil
}

func (e *canonEncoder) encdecision_WindowReason(v *decision.WindowReason) error {
	e.buf = binary.AppendUvarint(e.buf, uint64(v.Obj))
	e.appendString(string(v.Kind))
	e.appendString(string(v.Reason))
	return nil
}

func (e *canonEncoder) encdecision_PaymentAction(v *decision.PaymentAction) error {
	e.appendString(string(v.ID))
	if err := e.encdecision_PlannedCast(&v.Cast); err != nil {
		return err
	}
	if v.BaseOptionIndex == nil {
		e.buf = append(e.buf, 0)
	} else {
		e.buf = append(e.buf, 1)
		if v.BaseOptionIndex == nil {
			e.buf = append(e.buf, 0)
		} else {
			e.buf = append(e.buf, 1)
			e.buf = binary.AppendVarint(e.buf, int64((*v.BaseOptionIndex)))
		}
	}
	e.appendString(string(v.Label))
	if v.Plans == nil {
		e.buf = append(e.buf, 0)
	} else {
		e.buf = append(e.buf, 1)
		e.buf = binary.AppendUvarint(e.buf, uint64(len(v.Plans)))
		for x64 := range v.Plans {
			if err := e.encdecision_PaymentPlan(&v.Plans[x64]); err != nil {
				return err
			}
		}
	}
	return nil
}

func (e *canonEncoder) encdecision_PaymentFallback(v *decision.PaymentFallback) error {
	e.appendString(string(v.PlanID))
	e.appendString(string(v.Reason))
	return nil
}

func (e *canonEncoder) encdecision_ManaPaymentWindow(v *decision.ManaPaymentWindow) error {
	e.buf = binary.AppendUvarint(e.buf, uint64(v.Card))
	if err := e.encdecision_PaymentCost(&v.Cost); err != nil {
		return err
	}
	if err := e.encdecision_PaymentCost(&v.Owed); err != nil {
		return err
	}
	e.buf = binary.AppendUvarint(e.buf, uint64(len(v.Pool)))
	for x65 := range v.Pool {
		e.buf = binary.AppendUvarint(e.buf, uint64(v.Pool[x65]))
	}
	if len(v.AutoFill) == 0 {
		e.buf = append(e.buf, 0)
	} else {
		e.buf = append(e.buf, 1)
		if v.AutoFill == nil {
			e.buf = append(e.buf, 0)
		} else {
			e.buf = append(e.buf, 1)
			e.buf = binary.AppendUvarint(e.buf, uint64(len(v.AutoFill)))
			for x66 := range v.AutoFill {
				e.buf = binary.AppendUvarint(e.buf, uint64(v.AutoFill[x66]))
			}
		}
	}
	return nil
}

func (e *canonEncoder) encdecision_TargetEffect(v *decision.TargetEffect) error {
	e.appendString(string(v.API))
	if v.Damage == nil {
		e.buf = append(e.buf, 0)
	} else {
		e.buf = append(e.buf, 1)
		if v.Damage == nil {
			e.buf = append(e.buf, 0)
		} else {
			e.buf = append(e.buf, 1)
			if err := e.encdecision_DamageEffect(v.Damage); err != nil {
				return err
			}
		}
	}
	if v.Removal == nil {
		e.buf = append(e.buf, 0)
	} else {
		e.buf = append(e.buf, 1)
		if v.Removal == nil {
			e.buf = append(e.buf, 0)
		} else {
			e.buf = append(e.buf, 1)
			if err := e.encdecision_RemovalEffect(v.Removal); err != nil {
				return err
			}
		}
	}
	if len(v.Statics) == 0 {
		e.buf = append(e.buf, 0)
	} else {
		e.buf = append(e.buf, 1)
		if v.Statics == nil {
			e.buf = append(e.buf, 0)
		} else {
			e.buf = append(e.buf, 1)
			e.buf = binary.AppendUvarint(e.buf, uint64(len(v.Statics)))
			for x67 := range v.Statics {
				e.appendString(string(v.Statics[x67]))
			}
		}
	}
	return nil
}

func (e *canonEncoder) encview_Printing(v *view.Printing) error {
	e.appendString(string(v.Name))
	if len(v.Set) == 0 {
		e.buf = append(e.buf, 0)
	} else {
		e.buf = append(e.buf, 1)
		e.appendString(string(v.Set))
	}
	if len(v.Number) == 0 {
		e.buf = append(e.buf, 0)
	} else {
		e.buf = append(e.buf, 1)
		e.appendString(string(v.Number))
	}
	return nil
}

func (e *canonEncoder) enccards_ManaProduction(v *cards.ManaProduction) error {
	e.buf = binary.AppendUvarint(e.buf, uint64(len(v.Colour)))
	for x68 := range v.Colour {
		e.buf = binary.AppendVarint(e.buf, int64(v.Colour[x68]))
	}
	if v.Any {
		e.buf = append(e.buf, 1)
	} else {
		e.buf = append(e.buf, 0)
	}
	return nil
}

func (e *canonEncoder) encdecision_PlannedCast(v *decision.PlannedCast) error {
	e.buf = binary.AppendUvarint(e.buf, uint64(v.Object))
	e.buf = binary.AppendVarint(e.buf, int64(v.Face))
	e.appendString(string(v.Origin))
	return nil
}

func (e *canonEncoder) encdecision_PaymentPlan(v *decision.PaymentPlan) error {
	e.buf = binary.AppendUvarint(e.buf, uint64(v.Version))
	e.appendString(string(v.ID))
	if err := e.encdecision_PaymentCost(&v.Cost); err != nil {
		return err
	}
	if v.Activations == nil {
		e.buf = append(e.buf, 0)
	} else {
		e.buf = append(e.buf, 1)
		e.buf = binary.AppendUvarint(e.buf, uint64(len(v.Activations)))
		for x69 := range v.Activations {
			if err := e.encdecision_PaymentActivation(&v.Activations[x69]); err != nil {
				return err
			}
		}
	}
	e.buf = binary.AppendUvarint(e.buf, uint64(len(v.PoolSpend)))
	for x70 := range v.PoolSpend {
		e.buf = binary.AppendUvarint(e.buf, uint64(v.PoolSpend[x70]))
	}
	e.buf = binary.AppendUvarint(e.buf, uint64(len(v.PoolAfter)))
	for x71 := range v.PoolAfter {
		e.buf = binary.AppendUvarint(e.buf, uint64(v.PoolAfter[x71]))
	}
	return nil
}

func (e *canonEncoder) encdecision_PaymentCost(v *decision.PaymentCost) error {
	e.buf = binary.AppendUvarint(e.buf, uint64(v.Generic))
	e.buf = binary.AppendUvarint(e.buf, uint64(len(v.Mana)))
	for x72 := range v.Mana {
		e.buf = binary.AppendUvarint(e.buf, uint64(v.Mana[x72]))
	}
	return nil
}

func (e *canonEncoder) encdecision_DamageEffect(v *decision.DamageEffect) error {
	if v.Amount == nil {
		e.buf = append(e.buf, 0)
	} else {
		e.buf = append(e.buf, 1)
		e.buf = binary.AppendVarint(e.buf, int64((*v.Amount)))
	}
	return nil
}

func (e *canonEncoder) encdecision_RemovalEffect(v *decision.RemovalEffect) error {
	e.appendString(string(v.Kind))
	if len(v.Destination) == 0 {
		e.buf = append(e.buf, 0)
	} else {
		e.buf = append(e.buf, 1)
		e.appendString(string(v.Destination))
	}
	return nil
}

func (e *canonEncoder) encdecision_PaymentActivation(v *decision.PaymentActivation) error {
	e.buf = binary.AppendUvarint(e.buf, uint64(v.Source))
	e.buf = binary.AppendUvarint(e.buf, uint64(v.SourceZoneSeq))
	if err := e.encdecision_PaymentAbility(&v.Ability); err != nil {
		return err
	}
	e.buf = binary.AppendUvarint(e.buf, uint64(len(v.Produces)))
	for x73 := range v.Produces {
		e.buf = binary.AppendUvarint(e.buf, uint64(v.Produces[x73]))
	}
	if v.Consequence == nil {
		e.buf = append(e.buf, 0)
	} else {
		e.buf = append(e.buf, 1)
		if v.Consequence == nil {
			e.buf = append(e.buf, 0)
		} else {
			e.buf = append(e.buf, 1)
			if err := e.encdecision_PaymentConsequence(v.Consequence); err != nil {
				return err
			}
		}
	}
	return nil
}

func (e *canonEncoder) encdecision_PaymentAbility(v *decision.PaymentAbility) error {
	e.appendString(string(v.Kind))
	if v.Face == 0 {
		e.buf = append(e.buf, 0)
	} else {
		e.buf = append(e.buf, 1)
		e.buf = binary.AppendUvarint(e.buf, uint64(v.Face))
	}
	if v.Index == 0 {
		e.buf = append(e.buf, 0)
	} else {
		e.buf = append(e.buf, 1)
		e.buf = binary.AppendUvarint(e.buf, uint64(v.Index))
	}
	if len(v.Intrinsic) == 0 {
		e.buf = append(e.buf, 0)
	} else {
		e.buf = append(e.buf, 1)
		e.appendString(string(v.Intrinsic))
	}
	return nil
}

func (e *canonEncoder) encdecision_PaymentConsequence(v *decision.PaymentConsequence) error {
	if !v.Sacrifice {
		e.buf = append(e.buf, 0)
	} else {
		e.buf = append(e.buf, 1)
		if v.Sacrifice {
			e.buf = append(e.buf, 1)
		} else {
			e.buf = append(e.buf, 0)
		}
	}
	if v.Life == 0 {
		e.buf = append(e.buf, 0)
	} else {
		e.buf = append(e.buf, 1)
		e.buf = binary.AppendUvarint(e.buf, uint64(v.Life))
	}
	if v.Damage == 0 {
		e.buf = append(e.buf, 0)
	} else {
		e.buf = append(e.buf, 1)
		e.buf = binary.AppendUvarint(e.buf, uint64(v.Damage))
	}
	if !v.NoUntap {
		e.buf = append(e.buf, 0)
	} else {
		e.buf = append(e.buf, 1)
		if v.NoUntap {
			e.buf = append(e.buf, 1)
		} else {
			e.buf = append(e.buf, 0)
		}
	}
	if !v.ReturnToHand {
		e.buf = append(e.buf, 0)
	} else {
		e.buf = append(e.buf, 1)
		if v.ReturnToHand {
			e.buf = append(e.buf, 1)
		} else {
			e.buf = append(e.buf, 0)
		}
	}
	return nil
}
