// Code generated by TestCloneGenIsUpToDate (GORGE_GEN_CLONE=1 go generate ./rules); DO NOT EDIT.

package rules

import (
	cards "github.com/adams-shaun/gorge/cards"
	decision "github.com/adams-shaun/gorge/decision"
	effects "github.com/adams-shaun/gorge/effects"
	events "github.com/adams-shaun/gorge/events"
	pay "github.com/adams-shaun/gorge/rules/pay"
	state "github.com/adams-shaun/gorge/state"
)

// cloneEngineFields copies every `deep` and `share` Engine field not named
// in cloneHandFields, and hands the clone its pooled Spare storage
// (clone_gen_test.go).
func cloneEngineFields(c, e *Engine, sp *Spare, remap *cloneRemap) {
	cloneSpareFields(c, sp)
	cloneFieldsEngine(c, e, sp, remap)
	cloneFieldsEngineTurnLedger(c, e, sp, remap)
	cloneFieldsEngineLayerCaches(c, e, sp, remap)
	cloneFieldsEngineRounds(c, e, sp, remap)
	cloneFieldsEngineDerivedTables(c, e, sp, remap)
	cloneFieldsEngineScratch(c, e, sp, remap)
	cloneFieldsEngineTriggerMaps(c, e, sp, remap)
	cloneFieldsEngineResolution(c, e, sp, remap)
	cloneFieldsEngineDrain(c, e, sp, remap)
	cloneFieldsEngineTokenMint(c, e, sp, remap)
	cloneFieldsEngineTriggerBatches(c, e, sp, remap)
	cloneFieldsEngineContinuation(c, e, sp, remap)
	cloneFieldsEngineContinuation2(c, e, sp, remap)
	cloneFieldsEngineParked(c, e, sp, remap)
	cloneFieldsEngineParked2(c, e, sp, remap)
	cloneFieldsEngineCastWindows(c, e, sp, remap)
	cloneFieldsEngineResolveKernel(c, e, sp, remap)
	cloneFieldsPaySession(c, e, sp, remap)
}

// cloneSpareFields gives the clone its pooled storage from sp: a reset
// field adopts it, a deep one is emptied for its copy.
func cloneSpareFields(c *Engine, sp *Spare) {
	c.staticContinuous = sp.static[:0]
	c.staticGates = sp.gates[:0]
	c.activeBuf = sp.activeBuf
	c.activeSrc = sp.activeSrc
	c.activeBufAlt = sp.activeBufAlt
	c.typesProbe = sp.probe[:0]
	c.derivedMemo = sp.memo
	c.derivedMemoStack = sp.memoStack
	c.legalOptBuf = sp.legalOpts
	c.manaAbBuf = sp.manaAb
	c.lossMemo = sp.lossMemo
	c.castFree = sp.cast
}

func cloneFieldsEngine(c, e *Engine, sp *Spare, remap *cloneRemap) {
	c.deckManifests = e.deckManifests
	c.compiledText = e.compiledText
	c.landTypeWords = e.landTypeWords
	c.format = e.format
	if e.pending != nil {
		c.pending = cloneDecision(e.pending)
	}
	if e.continuous != nil {
		c.continuous = make([]state.ContinuousEffect, len(e.continuous))
		for i0 := range e.continuous {
			c.continuous[i0] = e.continuous[i0]
			if e.continuous[i0].SVars != nil {
				c.continuous[i0].SVars = make(map[string]string, len(e.continuous[i0].SVars))
				for k1, v1 := range e.continuous[i0].SVars {
					c.continuous[i0].SVars[k1] = v1
				}
			}
			c.continuous[i0].AddKeywords = append([]string(nil), e.continuous[i0].AddKeywords...)
			c.continuous[i0].AddTypes = append([]string(nil), e.continuous[i0].AddTypes...)
			c.continuous[i0].AddColors = append([]string(nil), e.continuous[i0].AddColors...)
			c.continuous[i0].RemoveTypes = append([]string(nil), e.continuous[i0].RemoveTypes...)
			c.continuous[i0].AddAbilities = append([]string(nil), e.continuous[i0].AddAbilities...)
			c.continuous[i0].GainedFaces = append([]state.GainedFace(nil), e.continuous[i0].GainedFaces...)
			c.continuous[i0].GainedTriggerFaces = append([]state.GainedFace(nil), e.continuous[i0].GainedTriggerFaces...)
			if e.continuous[i0].RestrictParams != nil {
				c.continuous[i0].RestrictParams = make(map[string]string, len(e.continuous[i0].RestrictParams))
				for k1, v1 := range e.continuous[i0].RestrictParams {
					c.continuous[i0].RestrictParams[k1] = v1
				}
			}
			if e.continuous[i0].RestrictSVars != nil {
				c.continuous[i0].RestrictSVars = make(map[string]string, len(e.continuous[i0].RestrictSVars))
				for k1, v1 := range e.continuous[i0].RestrictSVars {
					c.continuous[i0].RestrictSVars[k1] = v1
				}
			}
			c.continuous[i0].Remembered = append([]state.ObjID(nil), e.continuous[i0].Remembered...)
			c.continuous[i0].RememberedPlayers = append([]state.PlayerID(nil), e.continuous[i0].RememberedPlayers...)
			c.continuous[i0].Chosen = append([]state.ObjID(nil), e.continuous[i0].Chosen...)
			if e.continuous[i0].ReplacementParams != nil {
				c.continuous[i0].ReplacementParams = make(map[string]string, len(e.continuous[i0].ReplacementParams))
				for k1, v1 := range e.continuous[i0].ReplacementParams {
					c.continuous[i0].ReplacementParams[k1] = v1
				}
			}
			c.continuous[i0].RemoveKeywords = append([]string(nil), e.continuous[i0].RemoveKeywords...)
			c.continuous[i0].CantHaveKeywords = append([]string(nil), e.continuous[i0].CantHaveKeywords...)
			c.continuous[i0].ShieldTargets = append([]state.ObjID(nil), e.continuous[i0].ShieldTargets...)
			c.continuous[i0].ShieldTargetPlayers = append([]state.PlayerID(nil), e.continuous[i0].ShieldTargetPlayers...)
			if e.continuous[i0].AddSVars != nil {
				c.continuous[i0].AddSVars = make(map[string]string, len(e.continuous[i0].AddSVars))
				for k1, v1 := range e.continuous[i0].AddSVars {
					c.continuous[i0].AddSVars[k1] = v1
				}
			}
			if e.continuous[i0].AssignmentStaticParams != nil {
				c.continuous[i0].AssignmentStaticParams = make(map[string]string, len(e.continuous[i0].AssignmentStaticParams))
				for k1, v1 := range e.continuous[i0].AssignmentStaticParams {
					c.continuous[i0].AssignmentStaticParams[k1] = v1
				}
			}
			if e.continuous[i0].AssignmentStaticSVars != nil {
				c.continuous[i0].AssignmentStaticSVars = make(map[string]string, len(e.continuous[i0].AssignmentStaticSVars))
				for k1, v1 := range e.continuous[i0].AssignmentStaticSVars {
					c.continuous[i0].AssignmentStaticSVars[k1] = v1
				}
			}
			if e.continuous[i0].CostStaticSVars != nil {
				c.continuous[i0].CostStaticSVars = make(map[string]string, len(e.continuous[i0].CostStaticSVars))
				for k1, v1 := range e.continuous[i0].CostStaticSVars {
					c.continuous[i0].CostStaticSVars[k1] = v1
				}
			}
			if e.continuous[i0].CostStaticParams != nil {
				c.continuous[i0].CostStaticParams = make(map[string]string, len(e.continuous[i0].CostStaticParams))
				for k1, v1 := range e.continuous[i0].CostStaticParams {
					c.continuous[i0].CostStaticParams[k1] = v1
				}
			}
			c.continuous[i0].CloneStaticBodies = append([]string(nil), e.continuous[i0].CloneStaticBodies...)
		}
	}
	c.pendingLifeExchange = remap.lifeExchange(e.pendingLifeExchange)
	c.controlGrants = append([]controlGrant(nil), e.controlGrants...)
	c.mulligans = e.mulligans
	c.windowDiagnostics = e.windowDiagnostics
	c.startingLife = e.startingLife
	c.setNameInPool = e.setNameInPool
	c.layer4InPool = e.layer4InPool
	c.controlStaticInPool = e.controlStaticInPool
}

func cloneFieldsEngineTurnLedger(c, e *Engine, sp *Spare, remap *cloneRemap) {
	c.turnsTaken = append([]int32(nil), e.turnsTaken...)
	c.turnsTakenEpoch = e.turnsTakenEpoch
	if e.turnStartTurns != nil {
		c.turnStartTurns = make([][]int32, len(e.turnStartTurns))
		for i0 := range e.turnStartTurns {
			c.turnStartTurns[i0] = append([]int32(nil), e.turnStartTurns[i0]...)
		}
	}
	c.turnStartEpoch = e.turnStartEpoch
	c.combatHitsThisTurn = append([]effects.CombatDamageHit(nil), e.combatHitsThisTurn...)
	c.counterAddsThisTurn = append([]counterAddedThisTurn(nil), e.counterAddsThisTurn...)
	if e.activationsThisTurn != nil {
		c.activationsThisTurn = make([]activationThisTurn, len(e.activationsThisTurn))
		for i0 := range e.activationsThisTurn {
			c.activationsThisTurn[i0] = e.activationsThisTurn[i0]
			c.activationsThisTurn[i0].targets = append([]state.Target(nil), e.activationsThisTurn[i0].targets...)
		}
	}
	c.crimeSeatsThisTurn = e.crimeSeatsThisTurn
	c.bendSeatsThisTurn = e.bendSeatsThisTurn
	c.noncombatDamagedSeats = e.noncombatDamagedSeats
	c.noncombatDamagedSeatsLast = e.noncombatDamagedSeatsLast
}

func cloneFieldsEngineLayerCaches(c, e *Engine, sp *Spare, remap *cloneRemap) {
	if cloneCarriesStaticMemo(e) {
		c.staticContinuous = append(c.staticContinuous, e.staticContinuous...)
		c.staticEpoch = e.staticEpoch
		c.staticVersion = c.continuousVersion
		c.staticObjs = e.staticObjs
		c.staticMemoGated = e.staticMemoGated
		c.staticMemoStateRead = e.staticMemoStateRead
	}
	if cloneCarriesStaticMemo(e) && e.staticGatesKnown {
		c.staticGates = append(c.staticGates, e.staticGates...)
	}
	if cloneCarriesStaticMemo(e) {
		c.staticGatesKnown = e.staticGatesKnown
	}
}

func cloneFieldsEngineRounds(c, e *Engine, sp *Spare, remap *cloneRemap) {
	c.pregame = e.pregame
	c.coloring = e.coloring
	c.colorRound = e.colorRound
	c.tossChoice = e.tossChoice
	c.mulligan = e.mulligan
	c.mulligan.seats = append([]state.PlayerID(nil), e.mulligan.seats...)
	c.mulligan.kept = append([]bool(nil), e.mulligan.kept...)
	c.mulligan.taken = append([]int(nil), e.mulligan.taken...)
	c.opening = e.opening
	c.opening.effects = append([]openingEffect(nil), e.opening.effects...)
	if e.opening.exileAsk != nil {
		c.opening.exileAsk = cloneDecision(e.opening.exileAsk)
	}
	c.blockerRound = e.blockerRound
	c.exertAskState = e.exertAskState
	c.enlistAskState = e.enlistAskState
	c.stationing = e.stationing
	c.combatRound = e.combatRound
	c.combatRound.queue = append([]state.ObjID(nil), e.combatRound.queue...)
	if e.combatRound.done != nil {
		c.combatRound.done = make([]divChoice, len(e.combatRound.done))
		for i0 := range e.combatRound.done {
			c.combatRound.done[i0] = e.combatRound.done[i0]
			c.combatRound.done[i0].amounts = append([]int32(nil), e.combatRound.done[i0].amounts...)
		}
	}
	if e.combatRound.askOptions != nil {
		c.combatRound.askOptions = make([][]int32, len(e.combatRound.askOptions))
		for i0 := range e.combatRound.askOptions {
			c.combatRound.askOptions[i0] = append([]int32(nil), e.combatRound.askOptions[i0]...)
		}
	}
	c.combatRound.electQueue = append([]state.ObjID(nil), e.combatRound.electQueue...)
	c.combatRound.doneElect = append([]state.ObjID(nil), e.combatRound.doneElect...)
	c.combatRound.assignments = append([]assignment(nil), e.combatRound.assignments...)
	c.combatRound.initCtrls = append([]state.PlayerID(nil), e.combatRound.initCtrls...)
}

func cloneFieldsEngineDerivedTables(c, e *Engine, sp *Spare, remap *cloneRemap) {
	c.renames = append([]effects.ObjectName(nil), e.renames...)
	c.renameEpoch = e.renameEpoch
	c.renameVersion = rekeyVersion(e.renameVersion, e.continuousVersion)
	c.renameObjs = e.renameObjs
	c.layer4Types = append([]effects.ObjectTypes(nil), e.layer4Types...)
	c.typesEpoch = e.typesEpoch
	c.typesVersion = rekeyVersion(e.typesVersion, e.continuousVersion)
	c.typesObjs = e.typesObjs
	if e.typesIncrReady {
		c.typesIncrReady = e.typesIncrReady
		c.typesSelfOnly = e.typesSelfOnly
		c.typesSrcs = append([]state.ObjID(nil), e.typesSrcs...)
		c.typesMayDiffer = append([]state.ObjID(nil), e.typesMayDiffer...)
	}
	if e.typesProbeReady {
		c.typesProbe = append(c.typesProbe, e.typesProbe...)
		c.typesProbeReady = e.typesProbeReady
		c.typesProbeTrue = e.typesProbeTrue
		c.typesProbeEpoch = e.typesProbeEpoch
		c.typesProbeVersion = c.continuousVersion
		c.typesProbeObjs = e.typesProbeObjs
	}
}

func cloneFieldsEngineScratch(c, e *Engine, sp *Spare, remap *cloneRemap) {
	if cloneCarriesAtkOffers(e) {
		c.atkOffers = e.atkOffers
		c.atkOffersEp = e.atkOffersEp
		c.atkOffersVer = c.continuousVersion
		c.atkOffersObjs = e.atkOffersObjs
		c.atkOffersActive = e.atkOffersActive
	}
	c.legalScratch = cloneLegalWalkScratch(e.legalScratch)
	c.lossProof = e.lossProof.forClone()
}

func cloneFieldsEngineTriggerMaps(c, e *Engine, sp *Spare, remap *cloneRemap) {
	if e.triggerContexts != nil {
		c.triggerContexts = make(map[state.ObjID]effects.TriggerContext, len(e.triggerContexts))
		for k0, v0 := range e.triggerContexts {
			c.triggerContexts[k0] = v0
		}
	}
	if e.triggerEffectFrames != nil {
		c.triggerEffectFrames = make(map[state.ObjID]effects.EffectFrame, len(e.triggerEffectFrames))
		for k0, v0 := range e.triggerEffectFrames {
			c.triggerEffectFrames[k0] = v0
		}
	}
	if e.triggerLines != nil {
		c.triggerLines = make(map[state.ObjID]cards.Trigger, len(e.triggerLines))
		for k0, v0 := range e.triggerLines {
			var nv0 cards.Trigger
			nv0 = cloneTrigger(v0)
			c.triggerLines[k0] = nv0
		}
	}
	if e.triggerLineSVars != nil {
		c.triggerLineSVars = make(map[state.ObjID]map[string]string, len(e.triggerLineSVars))
		for k0, v0 := range e.triggerLineSVars {
			var nv0 map[string]string
			if v0 != nil {
				nv0 = make(map[string]string, len(v0))
				for k1, v1 := range v0 {
					nv0[k1] = v1
				}
			}
			c.triggerLineSVars[k0] = nv0
		}
	}
	if e.triggerLKI != nil {
		c.triggerLKI = make(map[state.ObjID]triggerObjectLKI, len(e.triggerLKI))
		for k0, v0 := range e.triggerLKI {
			var nv0 triggerObjectLKI
			nv0 = v0
			if v0.object != nil {
				cp := v0.object.CloneDeep()
				nv0.object = &cp
			}
			c.triggerLKI[k0] = nv0
		}
	}
	if e.sacrificedLKI != nil {
		c.sacrificedLKI = make(map[state.ObjID][]state.SacrificedInfo, len(e.sacrificedLKI))
		for k0, v0 := range e.sacrificedLKI {
			var nv0 []state.SacrificedInfo
			nv0 = append([]state.SacrificedInfo(nil), v0...)
			c.sacrificedLKI[k0] = nv0
		}
	}
	if e.castExiled != nil {
		c.castExiled = make(map[state.ObjID][]state.ObjID, len(e.castExiled))
		for k0, v0 := range e.castExiled {
			var nv0 []state.ObjID
			nv0 = append([]state.ObjID(nil), v0...)
			c.castExiled[k0] = nv0
		}
	}
	if e.castRevealed != nil {
		c.castRevealed = make(map[state.ObjID][]state.ObjID, len(e.castRevealed))
		for k0, v0 := range e.castRevealed {
			var nv0 []state.ObjID
			nv0 = append([]state.ObjID(nil), v0...)
			c.castRevealed[k0] = nv0
		}
	}
	if e.fuseTargets != nil {
		c.fuseTargets = make(map[state.ObjID][][]state.Target, len(e.fuseTargets))
		for k0, v0 := range e.fuseTargets {
			var nv0 [][]state.Target
			if v0 != nil {
				nv0 = make([][]state.Target, len(v0))
				for i1 := range v0 {
					nv0[i1] = append([]state.Target(nil), v0[i1]...)
				}
			}
			c.fuseTargets[k0] = nv0
		}
	}
	if e.copyTargetStage != nil {
		c.copyTargetStage = make(map[state.ObjID]int, len(e.copyTargetStage))
		for k0, v0 := range e.copyTargetStage {
			c.copyTargetStage[k0] = v0
		}
	}
	if e.copyAnswerTargets != nil {
		c.copyAnswerTargets = make(map[state.ObjID][][]decision.Option, len(e.copyAnswerTargets))
		for k0, v0 := range e.copyAnswerTargets {
			var nv0 [][]decision.Option
			if v0 != nil {
				nv0 = make([][]decision.Option, len(v0))
				for i1 := range v0 {
					nv0[i1] = append([]decision.Option(nil), v0[i1]...)
				}
			}
			c.copyAnswerTargets[k0] = nv0
		}
	}
	if e.castSubTargets != nil {
		c.castSubTargets = make(map[state.ObjID]map[string][]state.Target, len(e.castSubTargets))
		for k0, v0 := range e.castSubTargets {
			var nv0 map[string][]state.Target
			if v0 != nil {
				nv0 = make(map[string][]state.Target, len(v0))
				for k1, v1 := range v0 {
					var nv1 []state.Target
					nv1 = append([]state.Target(nil), v1...)
					nv0[k1] = nv1
				}
			}
			c.castSubTargets[k0] = nv0
		}
	}
	if e.resolutionTargets != nil {
		c.resolutionTargets = make(resolutionTargetMap, len(e.resolutionTargets))
		for k0, v0 := range e.resolutionTargets {
			var nv0 resolutionTargetSet
			nv0 = v0
			nv0.flat = append([]state.Target(nil), v0.flat...)
			if v0.modes != nil {
				nv0.modes = make([][]state.Target, len(v0.modes))
				for i1 := range v0.modes {
					nv0.modes[i1] = append([]state.Target(nil), v0.modes[i1]...)
				}
			}
			c.resolutionTargets[k0] = nv0
		}
	}
	c.trigSub = e.trigSub.clone()
	if e.charmTargets != nil {
		c.charmTargets = make(map[state.ObjID][][]state.Target, len(e.charmTargets))
		for k0, v0 := range e.charmTargets {
			var nv0 [][]state.Target
			if v0 != nil {
				nv0 = make([][]state.Target, len(v0))
				for i1 := range v0 {
					nv0[i1] = append([]state.Target(nil), v0[i1]...)
				}
			}
			c.charmTargets[k0] = nv0
		}
	}
}

func cloneFieldsEngineResolution(c, e *Engine, sp *Spare, remap *cloneRemap) {
	if e.exploitedLKI != nil {
		c.exploitedLKI = make(map[state.ObjID]state.SacrificedInfo, len(e.exploitedLKI))
		for k0, v0 := range e.exploitedLKI {
			c.exploitedLKI[k0] = v0
		}
	}
	if e.sourceLifelinkLKI != nil {
		c.sourceLifelinkLKI = make(map[state.ObjID]bool, len(e.sourceLifelinkLKI))
		for k0, v0 := range e.sourceLifelinkLKI {
			c.sourceLifelinkLKI[k0] = v0
		}
	}
	if e.sourceControllerLKI != nil {
		c.sourceControllerLKI = make(map[state.ObjID]state.PlayerID, len(e.sourceControllerLKI))
		for k0, v0 := range e.sourceControllerLKI {
			c.sourceControllerLKI[k0] = v0
		}
	}
	if e.sourceCharLKI != nil {
		c.sourceCharLKI = make(map[state.ObjID]sourceCharSnapshot, len(e.sourceCharLKI))
		for k0, v0 := range e.sourceCharLKI {
			var nv0 sourceCharSnapshot
			nv0 = v0
			nv0.counters = append([]state.Counter(nil), v0.counters...)
			c.sourceCharLKI[k0] = nv0
		}
	}
	if e.damageSourceLKI != nil {
		c.damageSourceLKI = make(map[state.ObjID]map[state.ObjID]effects.DamageSourceLKI, len(e.damageSourceLKI))
		for k0, v0 := range e.damageSourceLKI {
			var nv0 map[state.ObjID]effects.DamageSourceLKI
			if v0 != nil {
				nv0 = make(map[state.ObjID]effects.DamageSourceLKI, len(v0))
				for k1, v1 := range v0 {
					nv0[k1] = v1
				}
			}
			c.damageSourceLKI[k0] = nv0
		}
	}
}

func cloneFieldsEngineDrain(c, e *Engine, sp *Spare, remap *cloneRemap) {
	c.orderedTriggers = e.orderedTriggers
	c.applyingReplacement = e.applyingReplacement
}

func cloneFieldsEngineTokenMint(c, e *Engine, sp *Spare, remap *cloneRemap) {
	c.copyMintsPending = append([]state.ObjID(nil), e.copyMintsPending...)
}

func cloneFieldsEngineTriggerBatches(c, e *Engine, sp *Spare, remap *cloneRemap) {
	if e.triggerFireCount != nil {
		c.triggerFireCount = make(map[triggerKey]int32, len(e.triggerFireCount))
		for k0, v0 := range e.triggerFireCount {
			c.triggerFireCount[k0] = v0
		}
	}
	if e.unblockedOnceFired != nil {
		c.unblockedOnceFired = make(map[triggerKey]combatFires, len(e.unblockedOnceFired))
		for k0, v0 := range e.unblockedOnceFired {
			c.unblockedOnceFired[k0] = v0
		}
	}
	c.unblockedRoundChecked = e.unblockedRoundChecked
	if e.attackersDeclaredFired != nil {
		c.attackersDeclaredFired = make(map[triggerKey]combatFires, len(e.attackersDeclaredFired))
		for k0, v0 := range e.attackersDeclaredFired {
			c.attackersDeclaredFired[k0] = v0
		}
	}
	if e.damageBatchOpen {
		c.damageBatchOpen = e.damageBatchOpen
		c.damageBatchDepth = e.damageBatchDepth
		if e.damageBatchIdx != nil {
			c.damageBatchIdx = make(map[damageBatchKey]int, len(e.damageBatchIdx))
			for k0, v0 := range e.damageBatchIdx {
				c.damageBatchIdx[k0] = v0
			}
		}
		if e.damageBatchLog != nil {
			c.damageBatchLog = make([]damageBatchEntry, len(e.damageBatchLog))
			for i0 := range e.damageBatchLog {
				c.damageBatchLog[i0] = e.damageBatchLog[i0]
				c.damageBatchLog[i0].sources = append([]state.ObjID(nil), e.damageBatchLog[i0].sources...)
				c.damageBatchLog[i0].targets = append([]state.Target(nil), e.damageBatchLog[i0].targets...)
			}
		}
	}
	if e.zoneBatchOpen {
		c.zoneBatchOpen = e.zoneBatchOpen
		c.zoneBatchDepth = e.zoneBatchDepth
		if e.zoneBatchIdx != nil {
			c.zoneBatchIdx = make(map[zoneBatchKey]int, len(e.zoneBatchIdx))
			for k0, v0 := range e.zoneBatchIdx {
				c.zoneBatchIdx[k0] = v0
			}
		}
		if e.zoneBatchLog != nil {
			c.zoneBatchLog = make([]zoneBatchEntry, len(e.zoneBatchLog))
			for i0 := range e.zoneBatchLog {
				c.zoneBatchLog[i0] = e.zoneBatchLog[i0]
				c.zoneBatchLog[i0].moved = append([]state.Target(nil), e.zoneBatchLog[i0].moved...)
			}
		}
	}
	c.millBatchOpen = e.millBatchOpen
	c.millBatchDepth = e.millBatchDepth
	if e.millBatchIdx != nil {
		c.millBatchIdx = make(map[triggerKey]int, len(e.millBatchIdx))
		for k0, v0 := range e.millBatchIdx {
			c.millBatchIdx[k0] = v0
		}
	}
	if e.millBatchLog != nil {
		c.millBatchLog = make([]millBatchEntry, len(e.millBatchLog))
		for i0 := range e.millBatchLog {
			c.millBatchLog[i0] = e.millBatchLog[i0]
			c.millBatchLog[i0].milled = append([]state.Target(nil), e.millBatchLog[i0].milled...)
		}
	}
	if e.discardBatchOpen {
		c.discardBatchOpen = e.discardBatchOpen
		c.discardBatchDepth = e.discardBatchDepth
		if e.discardBatchIdx != nil {
			c.discardBatchIdx = make(map[triggerKey]int, len(e.discardBatchIdx))
			for k0, v0 := range e.discardBatchIdx {
				c.discardBatchIdx[k0] = v0
			}
		}
		if e.discardBatchLog != nil {
			c.discardBatchLog = make([]discardBatchEntry, len(e.discardBatchLog))
			for i0 := range e.discardBatchLog {
				c.discardBatchLog[i0] = e.discardBatchLog[i0]
				c.discardBatchLog[i0].discarded = append([]state.Target(nil), e.discardBatchLog[i0].discarded...)
			}
		}
	}
	if e.discardAllTurn != nil {
		c.discardAllTurn = make(map[triggerKey]int32, len(e.discardAllTurn))
		for k0, v0 := range e.discardAllTurn {
			c.discardAllTurn[k0] = v0
		}
	}
	if e.phaseUnknownNoted != nil {
		c.phaseUnknownNoted = make(map[string]bool, len(e.phaseUnknownNoted))
		for k0, v0 := range e.phaseUnknownNoted {
			c.phaseUnknownNoted[k0] = v0
		}
	}
	if e.disableTriggersNoted != nil {
		c.disableTriggersNoted = make(map[string]bool, len(e.disableTriggersNoted))
		for k0, v0 := range e.disableTriggersNoted {
			c.disableTriggersNoted[k0] = v0
		}
	}
	c.trigZones = copyTrigZones(sp.trigZones, e.trigZones)
	c.trigZonesEp = e.trigZonesEp
	c.trigGrant = e.trigGrant.forClone()
	c.replZones = copyReplZones(sp.replZones, e.replZones)
	c.replZonesEp = e.replZonesEp
	c.replArena = e.replArena
	if e.tappedTurn != nil {
		c.tappedTurn = make(map[state.ObjID]int32, len(e.tappedTurn))
		for k0, v0 := range e.tappedTurn {
			c.tappedTurn[k0] = v0
		}
	}
	if e.triggerTurnFires != nil {
		c.triggerTurnFires = make(map[triggerKey]turnFires, len(e.triggerTurnFires))
		for k0, v0 := range e.triggerTurnFires {
			c.triggerTurnFires[k0] = v0
		}
	}
	if e.triggerGameFires != nil {
		c.triggerGameFires = make(map[triggerKey]gameFires, len(e.triggerGameFires))
		for k0, v0 := range e.triggerGameFires {
			c.triggerGameFires[k0] = v0
		}
	}
	if e.triggerTurnResolved != nil {
		c.triggerTurnResolved = make(map[state.ObjID]turnFires, len(e.triggerTurnResolved))
		for k0, v0 := range e.triggerTurnResolved {
			c.triggerTurnResolved[k0] = v0
		}
	}
	if e.triggerTurnDice != nil {
		c.triggerTurnDice = make(map[triggerKey]turnFires, len(e.triggerTurnDice))
		for k0, v0 := range e.triggerTurnDice {
			c.triggerTurnDice[k0] = v0
		}
	}
	c.triggerTurnDiceTurn = e.triggerTurnDiceTurn
}

func cloneFieldsEngineContinuation(c, e *Engine, sp *Spare, remap *cloneRemap) {
	c.choosing = e.choosing
	c.oppSel = e.oppSel
	if e.oppPicksMid != nil {
		c.oppPicksMid = make(map[string]state.PlayerID, len(e.oppPicksMid))
		for k0, v0 := range e.oppPicksMid {
			c.oppPicksMid[k0] = v0
		}
	}
	if e.tpCtlChooser != nil {
		c.tpCtlChooser = make(map[state.ObjID]tpCtlAnswer, len(e.tpCtlChooser))
		for k0, v0 := range e.tpCtlChooser {
			c.tpCtlChooser[k0] = v0
		}
	}
	if e.cast != nil {
		p0 := *e.cast
		if e.cast.CastPayment.Payment != nil {
			p2 := *e.cast.CastPayment.Payment
			p2.Plan = decision.ClonePaymentPlan(e.cast.CastPayment.Payment.Plan)
			p0.CastPayment.Payment = &p2
		}
		if e.cast.CastPayment.PaymentFallback != nil {
			v := *e.cast.CastPayment.PaymentFallback
			p0.CastPayment.PaymentFallback = &v
		}
		p0.CastPayment.WindowTaps = pay.CloneWindowTaps(e.cast.CastPayment.WindowTaps)
		p0.CastPayment.SubCounterPays = append([]pay.SubCounterPay(nil), e.cast.CastPayment.SubCounterPays...)
		p0.CastPayment.Convoke = append([]pay.ConvokePayment(nil), e.cast.CastPayment.Convoke...)
		p0.cost = cloneCost(e.cast.cost)
		if e.cast.mayPlayRemembered != nil {
			p0.mayPlayRemembered = make(map[state.ObjID][]state.ObjID, len(e.cast.mayPlayRemembered))
			for k1, v1 := range e.cast.mayPlayRemembered {
				var nv1 []state.ObjID
				nv1 = append([]state.ObjID(nil), v1...)
				p0.mayPlayRemembered[k1] = nv1
			}
		}
		p0.mayPlayHosts = append([]state.ObjID(nil), e.cast.mayPlayHosts...)
		if e.cast.costRemembered != nil {
			p0.costRemembered = make([]costRememberedEntry, len(e.cast.costRemembered))
			for i1 := range e.cast.costRemembered {
				p0.costRemembered[i1] = e.cast.costRemembered[i1]
				p0.costRemembered[i1].ids = append([]state.ObjID(nil), e.cast.costRemembered[i1].ids...)
			}
		}
		p0.delve = append([]state.ObjID(nil), e.cast.delve...)
		p0.PaidCost.Sacs = append([]state.ObjID(nil), e.cast.PaidCost.Sacs...)
		p0.PaidCost.Discards = append([]state.ObjID(nil), e.cast.PaidCost.Discards...)
		p0.PaidCost.Exiles = append([]state.ObjID(nil), e.cast.PaidCost.Exiles...)
		p0.PaidCost.Reveals = append([]state.ObjID(nil), e.cast.PaidCost.Reveals...)
		p0.PaidCost.Beholds = append([]state.ObjID(nil), e.cast.PaidCost.Beholds...)
		p0.PaidCost.Taps = append([]state.ObjID(nil), e.cast.PaidCost.Taps...)
		p0.PaidCost.Blights = append([]state.ObjID(nil), e.cast.PaidCost.Blights...)
		p0.PaidCost.RevealHandArm = append([]bool(nil), e.cast.PaidCost.RevealHandArm...)
		p0.mods = cloneCastMods(e.cast.mods)
		p0.preModes = append([]string(nil), e.cast.preModes...)
		p0.targets = append([]state.Target(nil), e.cast.targets...)
		if e.cast.stageTargets != nil {
			p0.stageTargets = make([][]state.Target, len(e.cast.stageTargets))
			for i1 := range e.cast.stageTargets {
				p0.stageTargets[i1] = append([]state.Target(nil), e.cast.stageTargets[i1]...)
			}
		}
		if e.cast.charmTargets != nil {
			p0.charmTargets = make([][]state.Target, len(e.cast.charmTargets))
			for i1 := range e.cast.charmTargets {
				p0.charmTargets[i1] = append([]state.Target(nil), e.cast.charmTargets[i1]...)
			}
		}
		p0.subAsks = append([]*cards.SA(nil), e.cast.subAsks...)
		if e.cast.subAns != nil {
			p0.subAns = make([][]state.Target, len(e.cast.subAns))
			for i1 := range e.cast.subAns {
				p0.subAns[i1] = append([]state.Target(nil), e.cast.subAns[i1]...)
			}
		}
		p0.rootOpts = append([]decision.Option(nil), e.cast.rootOpts...)
		p0.evidence = append([]state.ObjID(nil), e.cast.evidence...)
		if e.cast.preSuppress != nil {
			p0.preSuppress = make(map[state.ObjID]bool, len(e.cast.preSuppress))
			for k1, v1 := range e.cast.preSuppress {
				p0.preSuppress[k1] = v1
			}
		}
		if e.cast.preAborts != nil {
			p0.preAborts = make(map[state.ObjID]int32, len(e.cast.preAborts))
			for k1, v1 := range e.cast.preAborts {
				p0.preAborts[k1] = v1
			}
		}
		p0.proposalTriggers = append([][2]int(nil), e.cast.proposalTriggers...)
		p0.returns = append([]state.ObjID(nil), e.cast.returns...)
		p0.moveGraves = append([]state.ObjID(nil), e.cast.moveGraves...)
		p0.putToLibs = append([]state.ObjID(nil), e.cast.putToLibs...)
		c.cast = &p0
	}
	if e.turnUp != nil {
		p0 := *e.turnUp
		p0.cost = cloneCost(e.turnUp.cost)
		p0.mods.Raises = append([]int32(nil), e.turnUp.mods.Raises...)
		p0.mods.Extra = cloneCost(e.turnUp.mods.Extra)
		p0.mods.Reduces = append([]pay.CostMod(nil), e.turnUp.mods.Reduces...)
		p0.sacs = append([]state.ObjID(nil), e.turnUp.sacs...)
		p0.discs = append([]state.ObjID(nil), e.turnUp.discs...)
		p0.reveal = append([]state.ObjID(nil), e.turnUp.reveal...)
		p0.returns = append([]state.ObjID(nil), e.turnUp.returns...)
		c.turnUp = &p0
	}
	if e.etbMove != nil {
		p0 := *e.etbMove
		p0.IDs = append([]state.ObjID(nil), e.etbMove.IDs...)
		p0.Pairs = append([][2]state.ObjID(nil), e.etbMove.Pairs...)
		c.etbMove = &p0
	}
	c.etbNext = e.etbNext
	c.auraEntry = e.auraEntry
	c.etbLandPlay = e.etbLandPlay
	c.etbLandObj = e.etbLandObj
	c.etbLandPlayer = e.etbLandPlayer
	if e.riotMove != nil {
		p0 := *e.riotMove
		p0.IDs = append([]state.ObjID(nil), e.riotMove.IDs...)
		p0.Pairs = append([][2]state.ObjID(nil), e.riotMove.Pairs...)
		c.riotMove = &p0
	}
	if e.unleashMove != nil {
		p0 := *e.unleashMove
		p0.IDs = append([]state.ObjID(nil), e.unleashMove.IDs...)
		p0.Pairs = append([][2]state.ObjID(nil), e.unleashMove.Pairs...)
		c.unleashMove = &p0
	}
	if e.siegeMove != nil {
		p0 := *e.siegeMove
		p0.IDs = append([]state.ObjID(nil), e.siegeMove.IDs...)
		p0.Pairs = append([][2]state.ObjID(nil), e.siegeMove.Pairs...)
		c.siegeMove = &p0
	}
}

func cloneFieldsEngineContinuation2(c, e *Engine, sp *Spare, remap *cloneRemap) {
	if e.entryStageDone != nil {
		p0 := *e.entryStageDone
		p0.grants = append([]entryGrant(nil), e.entryStageDone.grants...)
		p0.placed = append([]events.EntryCounterGrant(nil), e.entryStageDone.placed...)
		if e.entryStageDone.cands != nil {
			p0.cands = make([]replMatch, len(e.entryStageDone.cands))
			for i1 := range e.entryStageDone.cands {
				p0.cands[i1] = e.entryStageDone.cands[i1]
				p0.cands[i1].remembered = append([]state.ObjID(nil), e.entryStageDone.cands[i1].remembered...)
				p0.cands[i1].rememberedPlayers = append([]state.PlayerID(nil), e.entryStageDone.cands[i1].rememberedPlayers...)
			}
		}
		if e.entryStageDone.applied != nil {
			p0.applied = make([]replMatch, len(e.entryStageDone.applied))
			for i1 := range e.entryStageDone.applied {
				p0.applied[i1] = e.entryStageDone.applied[i1]
				p0.applied[i1].remembered = append([]state.ObjID(nil), e.entryStageDone.applied[i1].remembered...)
				p0.applied[i1].rememberedPlayers = append([]state.PlayerID(nil), e.entryStageDone.applied[i1].rememberedPlayers...)
			}
		}
		p0.bodyIDs = append([]string(nil), e.entryStageDone.bodyIDs...)
		if e.entryStageDone.tokenPlan != nil {
			p1 := *e.entryStageDone.tokenPlan
			p1.plan = append([]tokenPlanMint(nil), e.entryStageDone.tokenPlan.plan...)
			p0.tokenPlan = &p1
		}
		c.entryStageDone = &p0
	}
	if e.attachedChoice != nil {
		p0 := *e.attachedChoice
		c.attachedChoice = &p0
	}
	c.attachedApplying = e.attachedApplying
	if e.tokenChoice != nil {
		p0 := *e.tokenChoice
		if e.tokenChoice.matches != nil {
			p0.matches = make([]replMatch, len(e.tokenChoice.matches))
			for i1 := range e.tokenChoice.matches {
				p0.matches[i1] = e.tokenChoice.matches[i1]
				p0.matches[i1].remembered = append([]state.ObjID(nil), e.tokenChoice.matches[i1].remembered...)
				p0.matches[i1].rememberedPlayers = append([]state.PlayerID(nil), e.tokenChoice.matches[i1].rememberedPlayers...)
			}
		}
		p0.plan = append([]tokenPlanMint(nil), e.tokenChoice.plan...)
		p0.match.remembered = append([]state.ObjID(nil), e.tokenChoice.match.remembered...)
		p0.match.rememberedPlayers = append([]state.PlayerID(nil), e.tokenChoice.match.rememberedPlayers...)
		c.tokenChoice = &p0
	}
}

func cloneFieldsEngineParked(c, e *Engine, sp *Spare, remap *cloneRemap) {
	c.suspendedCasts = append([]state.ObjID(nil), e.suspendedCasts...)
	c.defeatedCasts = append([]state.ObjID(nil), e.defeatedCasts...)
	c.queuedPlays = e.queuedPlays.clone(remap)
	if e.manaActivation != nil {
		p0 := *e.manaActivation
		p0.abilities = append([]*cards.SA(nil), e.manaActivation.abilities...)
		p0.gained = append([]pay.GainedManaRef(nil), e.manaActivation.gained...)
		c.manaActivation = &p0
	}
	if e.manaColorActivation != nil {
		p0 := *e.manaColorActivation
		p0.triggers = clonePendingTriggers(e.manaColorActivation.triggers)
		if e.manaColorActivation.trigger != nil {
			p1 := *e.manaColorActivation.trigger
			p1.sourceCharLKI.counters = append([]state.Counter(nil), e.manaColorActivation.trigger.sourceCharLKI.counters...)
			p1.Trigger = cloneTrigger(e.manaColorActivation.trigger.Trigger)
			if e.manaColorActivation.trigger.TriggerSVars != nil {
				p1.TriggerSVars = make(map[string]string, len(e.manaColorActivation.trigger.TriggerSVars))
				for k2, v2 := range e.manaColorActivation.trigger.TriggerSVars {
					p1.TriggerSVars[k2] = v2
				}
			}
			p1.Ctx = remap.unlessCtx(e.manaColorActivation.trigger.Ctx)
			p0.trigger = &p1
		}
		p0.sacs = append([]state.ObjID(nil), e.manaColorActivation.sacs...)
		c.manaColorActivation = &p0
	}
	if e.manaUnlessActivation != nil {
		p0 := *e.manaUnlessActivation
		p0.triggers = clonePendingTriggers(e.manaUnlessActivation.triggers)
		p0.sacs = append([]state.ObjID(nil), e.manaUnlessActivation.sacs...)
		p0.payers = append([]state.PlayerID(nil), e.manaUnlessActivation.payers...)
		c.manaUnlessActivation = &p0
	}
	if e.manaAfterCost != nil {
		p0 := *e.manaAfterCost
		p0.triggers = clonePendingTriggers(e.manaAfterCost.triggers)
		p0.sacs = append([]state.ObjID(nil), e.manaAfterCost.sacs...)
		p0.untaps = append([]state.ObjID(nil), e.manaAfterCost.untaps...)
		c.manaAfterCost = &p0
	}
	if e.deferredAsks != nil {
		c.deferredAsks = make([]*decision.Decision, len(e.deferredAsks))
		for i0 := range e.deferredAsks {
			if e.deferredAsks[i0] != nil {
				c.deferredAsks[i0] = cloneDecision(e.deferredAsks[i0])
			}
		}
	}
	if e.cumulative != nil {
		p0 := *e.cumulative
		p0.amount = cloneCost(e.cumulative.amount)
		if e.cumulative.action != nil {
			p1 := *e.cumulative.action
			p0.action = &p1
		}
		c.cumulative = &p0
	}
	if e.triggerCost != nil {
		p0 := *e.triggerCost
		p0.resume = remap.resume(e.triggerCost.resume)
		p0.amount = cloneCost(e.triggerCost.amount)
		p0.costRemembered = append([]state.Target(nil), e.triggerCost.costRemembered...)
		p0.sacs = append([]state.ObjID(nil), e.triggerCost.sacs...)
		p0.exiles = append([]state.ObjID(nil), e.triggerCost.exiles...)
		p0.discards = append([]state.ObjID(nil), e.triggerCost.discards...)
		p0.moveGraves = append([]state.ObjID(nil), e.triggerCost.moveGraves...)
		p0.evidence = append([]state.ObjID(nil), e.triggerCost.evidence...)
		c.triggerCost = &p0
	}
	if e.echo != nil {
		p0 := *e.echo
		p0.amount = cloneCost(e.echo.amount)
		if e.echo.action != nil {
			p1 := *e.echo.action
			p0.action = &p1
		}
		c.echo = &p0
	}
	if e.attackPay != nil {
		p0 := *e.attackPay
		p0.chosen = append([]decision.Option(nil), e.attackPay.chosen...)
		if e.attackPay.plan != nil {
			p1 := *e.attackPay.plan
			p1.charge.taps = append([]blockTapReq(nil), e.attackPay.plan.charge.taps...)
			p1.charge.sacs = append([]chargeObjReq(nil), e.attackPay.plan.charge.sacs...)
			p1.charge.returns = append([]chargeObjReq(nil), e.attackPay.plan.charge.returns...)
			p1.charge.phyrexian = append([]uint8(nil), e.attackPay.plan.charge.phyrexian...)
			p1.taps = append([]state.ObjID(nil), e.attackPay.plan.taps...)
			p1.sacs = append([]state.ObjID(nil), e.attackPay.plan.sacs...)
			p1.returns = append([]state.ObjID(nil), e.attackPay.plan.returns...)
			p0.plan = &p1
		}
		p0.sources = append([]attackManaSource(nil), e.attackPay.sources...)
		c.attackPay = &p0
	}
	if e.blockPay != nil {
		p0 := *e.blockPay
		p0.chosen = append([]decision.Option(nil), e.blockPay.chosen...)
		if e.blockPay.plan != nil {
			p1 := *e.blockPay.plan
			p1.charge.taps = append([]blockTapReq(nil), e.blockPay.plan.charge.taps...)
			p1.charge.sacs = append([]chargeObjReq(nil), e.blockPay.plan.charge.sacs...)
			p1.charge.returns = append([]chargeObjReq(nil), e.blockPay.plan.charge.returns...)
			p1.charge.phyrexian = append([]uint8(nil), e.blockPay.plan.charge.phyrexian...)
			p1.taps = append([]state.ObjID(nil), e.blockPay.plan.taps...)
			p1.sacs = append([]state.ObjID(nil), e.blockPay.plan.sacs...)
			p1.returns = append([]state.ObjID(nil), e.blockPay.plan.returns...)
			p0.plan = &p1
		}
		p0.sources = append([]attackManaSource(nil), e.blockPay.sources...)
		c.blockPay = &p0
	}
	c.cmdZone = append([]cmdZoneMove(nil), e.cmdZone...)
	if e.legendBatch != nil {
		p0 := *e.legendBatch
		p0.group.ids = append([]state.ObjID(nil), e.legendBatch.group.ids...)
		p0.dead = append([]casualty(nil), e.legendBatch.dead...)
		c.legendBatch = &p0
	}
}

func cloneFieldsEngineParked2(c, e *Engine, sp *Spare, remap *cloneRemap) {
	if e.replChoices != nil {
		c.replChoices = make([]replChoice, len(e.replChoices))
		for i0 := range e.replChoices {
			c.replChoices[i0] = e.replChoices[i0]
			if e.replChoices[i0].cands != nil {
				c.replChoices[i0].cands = make([]replMatch, len(e.replChoices[i0].cands))
				for i1 := range e.replChoices[i0].cands {
					c.replChoices[i0].cands[i1] = e.replChoices[i0].cands[i1]
					c.replChoices[i0].cands[i1].remembered = append([]state.ObjID(nil), e.replChoices[i0].cands[i1].remembered...)
					c.replChoices[i0].cands[i1].rememberedPlayers = append([]state.PlayerID(nil), e.replChoices[i0].cands[i1].rememberedPlayers...)
				}
			}
			c.replChoices[i0].applied = append([]bool(nil), e.replChoices[i0].applied...)
			c.replChoices[i0].applicable = append([]int(nil), e.replChoices[i0].applicable...)
			if e.replChoices[i0].untap != nil {
				p1 := *e.replChoices[i0].untap
				c.replChoices[i0].untap = &p1
			}
			c.replChoices[i0].exchange = remap.lifeExchange(e.replChoices[i0].exchange)
			if e.replChoices[i0].appliedRepls != nil {
				c.replChoices[i0].appliedRepls = make([]replMatch, len(e.replChoices[i0].appliedRepls))
				for i1 := range e.replChoices[i0].appliedRepls {
					c.replChoices[i0].appliedRepls[i1] = e.replChoices[i0].appliedRepls[i1]
					c.replChoices[i0].appliedRepls[i1].remembered = append([]state.ObjID(nil), e.replChoices[i0].appliedRepls[i1].remembered...)
					c.replChoices[i0].appliedRepls[i1].rememberedPlayers = append([]state.PlayerID(nil), e.replChoices[i0].appliedRepls[i1].rememberedPlayers...)
				}
			}
			if e.replChoices[i0].used != nil {
				c.replChoices[i0].used = make([]replMatch, len(e.replChoices[i0].used))
				for i1 := range e.replChoices[i0].used {
					c.replChoices[i0].used[i1] = e.replChoices[i0].used[i1]
					c.replChoices[i0].used[i1].remembered = append([]state.ObjID(nil), e.replChoices[i0].used[i1].remembered...)
					c.replChoices[i0].used[i1].rememberedPlayers = append([]state.PlayerID(nil), e.replChoices[i0].used[i1].rememberedPlayers...)
				}
			}
			c.replChoices[i0].tokenPlan = append([]tokenPlanMint(nil), e.replChoices[i0].tokenPlan...)
			c.replChoices[i0].absorbed = append([]string(nil), e.replChoices[i0].absorbed...)
			if e.replChoices[i0].stage != nil {
				p1 := *e.replChoices[i0].stage
				p1.grants = append([]entryGrant(nil), e.replChoices[i0].stage.grants...)
				p1.placed = append([]events.EntryCounterGrant(nil), e.replChoices[i0].stage.placed...)
				if e.replChoices[i0].stage.cands != nil {
					p1.cands = make([]replMatch, len(e.replChoices[i0].stage.cands))
					for i2 := range e.replChoices[i0].stage.cands {
						p1.cands[i2] = e.replChoices[i0].stage.cands[i2]
						p1.cands[i2].remembered = append([]state.ObjID(nil), e.replChoices[i0].stage.cands[i2].remembered...)
						p1.cands[i2].rememberedPlayers = append([]state.PlayerID(nil), e.replChoices[i0].stage.cands[i2].rememberedPlayers...)
					}
				}
				if e.replChoices[i0].stage.applied != nil {
					p1.applied = make([]replMatch, len(e.replChoices[i0].stage.applied))
					for i2 := range e.replChoices[i0].stage.applied {
						p1.applied[i2] = e.replChoices[i0].stage.applied[i2]
						p1.applied[i2].remembered = append([]state.ObjID(nil), e.replChoices[i0].stage.applied[i2].remembered...)
						p1.applied[i2].rememberedPlayers = append([]state.PlayerID(nil), e.replChoices[i0].stage.applied[i2].rememberedPlayers...)
					}
				}
				p1.bodyIDs = append([]string(nil), e.replChoices[i0].stage.bodyIDs...)
				if e.replChoices[i0].stage.tokenPlan != nil {
					p2 := *e.replChoices[i0].stage.tokenPlan
					p2.plan = append([]tokenPlanMint(nil), e.replChoices[i0].stage.tokenPlan.plan...)
					p1.tokenPlan = &p2
				}
				c.replChoices[i0].stage = &p1
			}
			c.replChoices[i0].resumeAtPose = remap.resume(e.replChoices[i0].resumeAtPose)
		}
	}
}

func cloneFieldsEngineCastWindows(c, e *Engine, sp *Spare, remap *cloneRemap) {
	if e.untapResume != nil {
		p0 := *e.untapResume
		c.untapResume = &p0
	}
	c.untapChoiceObj = e.untapChoiceObj
	c.madnessChoices = append([]events.Event(nil), e.madnessChoices...)
	c.madnessSuspended = e.madnessSuspended
	if e.suppressedCast != nil {
		c.suppressedCast = make(map[state.ObjID]bool, len(e.suppressedCast))
		for k0, v0 := range e.suppressedCast {
			c.suppressedCast[k0] = v0
		}
	}
	if e.castAborts != nil {
		c.castAborts = make(map[state.ObjID]int32, len(e.castAborts))
		for k0, v0 := range e.castAborts {
			c.castAborts[k0] = v0
		}
	}
	if e.inertHeldOut != nil {
		c.inertHeldOut = make(map[inertKey]bool, len(e.inertHeldOut))
		for k0, v0 := range e.inertHeldOut {
			c.inertHeldOut[k0] = v0
		}
	}
	c.drainAwaitsTarget = e.drainAwaitsTarget
	c.drainAwaitsModes = e.drainAwaitsModes
	c.deferCastTrigger = e.deferCastTrigger
	if cloneCarriesCast(e) {
		c.deferredPush = cloneHeldEvent(e.deferredPush)
		c.deferredPushLKI = e.deferredPushLKI
	}
	c.manaExpended = append([]int32(nil), e.manaExpended...)
	c.manaExpendedTurn = e.manaExpendedTurn
}

func cloneFieldsEngineResolveKernel(c, e *Engine, sp *Spare, remap *cloneRemap) {
	c.tape = e.tape.ForClone()
}

func cloneFieldsPaySession(c, e *Engine, sp *Spare, remap *cloneRemap) {
	if e.UnlessPayment != nil {
		p0 := *e.UnlessPayment
		p0.Cost = cloneCost(e.UnlessPayment.Cost)
		p0.Ctx = remap.unlessCtx(e.UnlessPayment.Ctx)
		p0.Sacs = append([]state.ObjID(nil), e.UnlessPayment.Sacs...)
		p0.Discards = append([]state.ObjID(nil), e.UnlessPayment.Discards...)
		p0.Reveals = append([]state.ObjID(nil), e.UnlessPayment.Reveals...)
		p0.Beholds = append([]state.ObjID(nil), e.UnlessPayment.Beholds...)
		p0.Returns = append([]state.ObjID(nil), e.UnlessPayment.Returns...)
		p0.Exiles = append([]state.ObjID(nil), e.UnlessPayment.Exiles...)
		c.UnlessPayment = &p0
	}
	if e.ManaCost != nil {
		p0 := *e.ManaCost
		p0.Cost = cloneCost(e.ManaCost.Cost)
		p0.Sacs = append([]state.ObjID(nil), e.ManaCost.Sacs...)
		p0.Discards = append([]state.ObjID(nil), e.ManaCost.Discards...)
		p0.Exiles = append([]state.ObjID(nil), e.ManaCost.Exiles...)
		p0.Taps = append([]state.ObjID(nil), e.ManaCost.Taps...)
		p0.SubCounterPays = append([]pay.SubCounterPay(nil), e.ManaCost.SubCounterPays...)
		p0.Untaps = append([]state.ObjID(nil), e.ManaCost.Untaps...)
		c.ManaCost = &p0
	}
}

// sparePools is the Spare storage of every `pool=` Engine field, embedded
// in Spare: Release fills it (releasePools), a clone or genesis adopts it.
type sparePools struct {
	// static recycles Engine.staticContinuous.
	static []state.ContinuousEffect
	// gates recycles Engine.staticGates.
	gates []staticGateRec
	// activeBuf recycles Engine.activeBuf.
	activeBuf []state.ContinuousEffect
	// activeSrc recycles Engine.activeSrc.
	activeSrc []*state.ContinuousEffect
	// activeBufAlt recycles Engine.activeBufAlt.
	activeBufAlt []state.ContinuousEffect
	// probe recycles Engine.typesProbe.
	probe []uint8
	// memo recycles Engine.derivedMemo.
	memo derivedMemoTable
	// memoStack recycles Engine.derivedMemoStack.
	memoStack derivedMemoTable
	// legalOpts recycles Engine.legalOptBuf.
	legalOpts []decision.Option
	// manaAb recycles Engine.manaAbBuf.
	manaAb []*cards.SA
	// lossMemo recycles Engine.lossMemo.
	lossMemo abilityLossMemo
	// pending recycles Engine.pendingTriggers.
	pending []pendingTrigger
	// trigZones recycles Engine.trigZones.
	trigZones []trigZoneSummary
	// replZones recycles Engine.replZones.
	replZones []replZoneSummary
	// cast recycles Engine.castFree.
	cast *pendingCast
}

// releasePools hands every `pool=` field's storage to sp and drops it
// from e.
func releasePools(e *Engine, sp *Spare) {
	sp.static, e.staticContinuous = recycledSlice(e.staticContinuous), nil
	sp.gates, e.staticGates = recycledSlice(e.staticGates), nil
	sp.activeBuf, e.activeBuf = recycledSlice(e.activeBuf), nil
	sp.activeSrc, e.activeSrc = e.activeSrc[:0], nil
	sp.activeBufAlt, e.activeBufAlt = recycledSlice(e.activeBufAlt), nil
	sp.probe, e.typesProbe = e.typesProbe[:0], nil
	sp.memo, e.derivedMemo = e.derivedMemo.release(), derivedMemoTable{}
	sp.memoStack, e.derivedMemoStack = e.derivedMemoStack.release(), derivedMemoTable{}
	sp.legalOpts, e.legalOptBuf = e.legalOptBuf[:0], nil
	sp.manaAb, e.manaAbBuf = e.manaAbBuf[:0], nil
	sp.lossMemo, e.lossMemo = e.lossMemo.recycled(), abilityLossMemo{}
	sp.pending, e.pendingTriggers = recycledSlice(e.pendingTriggers), nil
	sp.trigZones, e.trigZones = releasedTrigZones(e.trigZones), nil
	sp.replZones, e.replZones = releasedReplZones(e.replZones), nil
	sp.cast, e.castFree = releaseCastFree(e), nil
}

// resumeFields deepens the reference fields of the resume frame cp, a value
// copy of rp.
func (remap *cloneRemap) resumeFields(cp, rp *resumePoint) {
}
