// Code generated by TestCloneGenIsUpToDate (GORGE_GEN_CLONE=1 go generate ./rules); DO NOT EDIT.

package rules

import (
	cards "github.com/adams-shaun/gorge/cards"
	decision "github.com/adams-shaun/gorge/decision"
	effects "github.com/adams-shaun/gorge/effects"
	events "github.com/adams-shaun/gorge/events"
	state "github.com/adams-shaun/gorge/state"
)

// cloneEngineFields copies every `deep` Engine field not named in
// cloneHandFields (clone_gen_test.go).
func cloneEngineFields(c, e *Engine, remap *cloneRemap) {
	cloneFieldsEngine(c, e, remap)
	cloneFieldsEngineTurnLedger(c, e, remap)
	cloneFieldsEngineRounds(c, e, remap)
	cloneFieldsEngineTriggerMaps(c, e, remap)
	cloneFieldsEngineResolution(c, e, remap)
	cloneFieldsEngineDrain(c, e, remap)
	cloneFieldsEngineTokenMint(c, e, remap)
	cloneFieldsEngineTriggerBatches(c, e, remap)
	cloneFieldsEngineContinuation(c, e, remap)
	cloneFieldsEngineParked(c, e, remap)
	cloneFieldsEngineParked2(c, e, remap)
	cloneFieldsEngineCastWindows(c, e, remap)
}

func cloneFieldsEngine(c, e *Engine, remap *cloneRemap) {
	c.format = e.format
	if e.pending != nil {
		c.pending = cloneDecision(e.pending)
	}
	if e.continuous != nil {
		c.continuous = make([]state.ContinuousEffect, len(e.continuous))
		for i0 := range e.continuous {
			c.continuous[i0] = e.continuous[i0]
			if e.continuous[i0].SVars != nil {
				c.continuous[i0].SVars = make(map[string]string, len(e.continuous[i0].SVars))
				for k1, v1 := range e.continuous[i0].SVars {
					c.continuous[i0].SVars[k1] = v1
				}
			}
			c.continuous[i0].AddKeywords = append([]string(nil), e.continuous[i0].AddKeywords...)
			c.continuous[i0].AddTypes = append([]string(nil), e.continuous[i0].AddTypes...)
			c.continuous[i0].AddColors = append([]string(nil), e.continuous[i0].AddColors...)
			c.continuous[i0].RemoveTypes = append([]string(nil), e.continuous[i0].RemoveTypes...)
			c.continuous[i0].AddAbilities = append([]string(nil), e.continuous[i0].AddAbilities...)
			c.continuous[i0].GainedFaces = append([]state.GainedFace(nil), e.continuous[i0].GainedFaces...)
			c.continuous[i0].GainedTriggerFaces = append([]state.GainedFace(nil), e.continuous[i0].GainedTriggerFaces...)
			if e.continuous[i0].RestrictParams != nil {
				c.continuous[i0].RestrictParams = make(map[string]string, len(e.continuous[i0].RestrictParams))
				for k1, v1 := range e.continuous[i0].RestrictParams {
					c.continuous[i0].RestrictParams[k1] = v1
				}
			}
			if e.continuous[i0].RestrictSVars != nil {
				c.continuous[i0].RestrictSVars = make(map[string]string, len(e.continuous[i0].RestrictSVars))
				for k1, v1 := range e.continuous[i0].RestrictSVars {
					c.continuous[i0].RestrictSVars[k1] = v1
				}
			}
			c.continuous[i0].Remembered = append([]state.ObjID(nil), e.continuous[i0].Remembered...)
			c.continuous[i0].RememberedPlayers = append([]state.PlayerID(nil), e.continuous[i0].RememberedPlayers...)
			c.continuous[i0].Chosen = append([]state.ObjID(nil), e.continuous[i0].Chosen...)
			if e.continuous[i0].ReplacementParams != nil {
				c.continuous[i0].ReplacementParams = make(map[string]string, len(e.continuous[i0].ReplacementParams))
				for k1, v1 := range e.continuous[i0].ReplacementParams {
					c.continuous[i0].ReplacementParams[k1] = v1
				}
			}
			c.continuous[i0].RemoveKeywords = append([]string(nil), e.continuous[i0].RemoveKeywords...)
			c.continuous[i0].CantHaveKeywords = append([]string(nil), e.continuous[i0].CantHaveKeywords...)
			c.continuous[i0].ShieldTargets = append([]state.ObjID(nil), e.continuous[i0].ShieldTargets...)
			c.continuous[i0].ShieldTargetPlayers = append([]state.PlayerID(nil), e.continuous[i0].ShieldTargetPlayers...)
			if e.continuous[i0].AddSVars != nil {
				c.continuous[i0].AddSVars = make(map[string]string, len(e.continuous[i0].AddSVars))
				for k1, v1 := range e.continuous[i0].AddSVars {
					c.continuous[i0].AddSVars[k1] = v1
				}
			}
			if e.continuous[i0].AssignmentStaticParams != nil {
				c.continuous[i0].AssignmentStaticParams = make(map[string]string, len(e.continuous[i0].AssignmentStaticParams))
				for k1, v1 := range e.continuous[i0].AssignmentStaticParams {
					c.continuous[i0].AssignmentStaticParams[k1] = v1
				}
			}
			if e.continuous[i0].AssignmentStaticSVars != nil {
				c.continuous[i0].AssignmentStaticSVars = make(map[string]string, len(e.continuous[i0].AssignmentStaticSVars))
				for k1, v1 := range e.continuous[i0].AssignmentStaticSVars {
					c.continuous[i0].AssignmentStaticSVars[k1] = v1
				}
			}
			if e.continuous[i0].CostStaticSVars != nil {
				c.continuous[i0].CostStaticSVars = make(map[string]string, len(e.continuous[i0].CostStaticSVars))
				for k1, v1 := range e.continuous[i0].CostStaticSVars {
					c.continuous[i0].CostStaticSVars[k1] = v1
				}
			}
			if e.continuous[i0].CostStaticParams != nil {
				c.continuous[i0].CostStaticParams = make(map[string]string, len(e.continuous[i0].CostStaticParams))
				for k1, v1 := range e.continuous[i0].CostStaticParams {
					c.continuous[i0].CostStaticParams[k1] = v1
				}
			}
			c.continuous[i0].CloneStaticBodies = append([]string(nil), e.continuous[i0].CloneStaticBodies...)
		}
	}
	c.pendingLifeExchange = remap.lifeExchange(e.pendingLifeExchange)
	c.controlGrants = append([]controlGrant(nil), e.controlGrants...)
	c.mulligans = e.mulligans
	c.windowDiagnostics = e.windowDiagnostics
	c.startingLife = e.startingLife
	c.setNameInPool = e.setNameInPool
	c.layer4InPool = e.layer4InPool
	c.controlStaticInPool = e.controlStaticInPool
}

func cloneFieldsEngineTurnLedger(c, e *Engine, remap *cloneRemap) {
	c.turnsTaken = append([]int32(nil), e.turnsTaken...)
	c.turnsTakenEpoch = e.turnsTakenEpoch
	if e.turnStartTurns != nil {
		c.turnStartTurns = make([][]int32, len(e.turnStartTurns))
		for i0 := range e.turnStartTurns {
			c.turnStartTurns[i0] = append([]int32(nil), e.turnStartTurns[i0]...)
		}
	}
	c.turnStartEpoch = e.turnStartEpoch
	c.combatHitsThisTurn = append([]effects.CombatDamageHit(nil), e.combatHitsThisTurn...)
	c.counterAddsThisTurn = append([]counterAddedThisTurn(nil), e.counterAddsThisTurn...)
	if e.activationsThisTurn != nil {
		c.activationsThisTurn = make([]activationThisTurn, len(e.activationsThisTurn))
		for i0 := range e.activationsThisTurn {
			c.activationsThisTurn[i0] = e.activationsThisTurn[i0]
			c.activationsThisTurn[i0].targets = append([]state.Target(nil), e.activationsThisTurn[i0].targets...)
		}
	}
	c.crimeSeatsThisTurn = e.crimeSeatsThisTurn
	c.bendSeatsThisTurn = e.bendSeatsThisTurn
	c.noncombatDamagedSeats = e.noncombatDamagedSeats
	c.noncombatDamagedSeatsLast = e.noncombatDamagedSeatsLast
}

func cloneFieldsEngineRounds(c, e *Engine, remap *cloneRemap) {
	c.pregame = e.pregame
	c.coloring = e.coloring
	c.tossChoice = e.tossChoice
	c.mulligan = e.mulligan
	c.mulligan.seats = append([]state.PlayerID(nil), e.mulligan.seats...)
	c.mulligan.kept = append([]bool(nil), e.mulligan.kept...)
	c.mulligan.taken = append([]int(nil), e.mulligan.taken...)
	c.opening = e.opening
	c.opening.effects = append([]openingEffect(nil), e.opening.effects...)
	if e.opening.exileAsk != nil {
		c.opening.exileAsk = cloneDecision(e.opening.exileAsk)
	}
	c.stationing = e.stationing
	c.combatRound = e.combatRound
	c.combatRound.queue = append([]state.ObjID(nil), e.combatRound.queue...)
	if e.combatRound.done != nil {
		c.combatRound.done = make([]divChoice, len(e.combatRound.done))
		for i0 := range e.combatRound.done {
			c.combatRound.done[i0] = e.combatRound.done[i0]
			c.combatRound.done[i0].amounts = append([]int32(nil), e.combatRound.done[i0].amounts...)
		}
	}
	if e.combatRound.askOptions != nil {
		c.combatRound.askOptions = make([][]int32, len(e.combatRound.askOptions))
		for i0 := range e.combatRound.askOptions {
			c.combatRound.askOptions[i0] = append([]int32(nil), e.combatRound.askOptions[i0]...)
		}
	}
	c.combatRound.electQueue = append([]state.ObjID(nil), e.combatRound.electQueue...)
	c.combatRound.doneElect = append([]state.ObjID(nil), e.combatRound.doneElect...)
	c.combatRound.assignments = append([]assignment(nil), e.combatRound.assignments...)
	c.combatRound.initCtrls = append([]state.PlayerID(nil), e.combatRound.initCtrls...)
}

func cloneFieldsEngineTriggerMaps(c, e *Engine, remap *cloneRemap) {
	if e.triggerContexts != nil {
		c.triggerContexts = make(map[state.ObjID]effects.TriggerContext, len(e.triggerContexts))
		for k0, v0 := range e.triggerContexts {
			c.triggerContexts[k0] = v0
		}
	}
	if e.triggerEffectFrames != nil {
		c.triggerEffectFrames = make(map[state.ObjID]effects.EffectFrame, len(e.triggerEffectFrames))
		for k0, v0 := range e.triggerEffectFrames {
			c.triggerEffectFrames[k0] = v0
		}
	}
	if e.triggerLines != nil {
		c.triggerLines = make(map[state.ObjID]cards.Trigger, len(e.triggerLines))
		for k0, v0 := range e.triggerLines {
			var nv0 cards.Trigger
			nv0 = cloneTrigger(v0)
			c.triggerLines[k0] = nv0
		}
	}
	if e.triggerLineSVars != nil {
		c.triggerLineSVars = make(map[state.ObjID]map[string]string, len(e.triggerLineSVars))
		for k0, v0 := range e.triggerLineSVars {
			var nv0 map[string]string
			if v0 != nil {
				nv0 = make(map[string]string, len(v0))
				for k1, v1 := range v0 {
					nv0[k1] = v1
				}
			}
			c.triggerLineSVars[k0] = nv0
		}
	}
	if e.triggerLKI != nil {
		c.triggerLKI = make(map[state.ObjID]triggerObjectLKI, len(e.triggerLKI))
		for k0, v0 := range e.triggerLKI {
			var nv0 triggerObjectLKI
			nv0 = v0
			if v0.object != nil {
				cp := v0.object.CloneDeep()
				nv0.object = &cp
			}
			c.triggerLKI[k0] = nv0
		}
	}
	if e.sacrificedLKI != nil {
		c.sacrificedLKI = make(map[state.ObjID][]state.SacrificedInfo, len(e.sacrificedLKI))
		for k0, v0 := range e.sacrificedLKI {
			var nv0 []state.SacrificedInfo
			nv0 = append([]state.SacrificedInfo(nil), v0...)
			c.sacrificedLKI[k0] = nv0
		}
	}
	if e.castExiled != nil {
		c.castExiled = make(map[state.ObjID][]state.ObjID, len(e.castExiled))
		for k0, v0 := range e.castExiled {
			var nv0 []state.ObjID
			nv0 = append([]state.ObjID(nil), v0...)
			c.castExiled[k0] = nv0
		}
	}
	if e.castRevealed != nil {
		c.castRevealed = make(map[state.ObjID][]state.ObjID, len(e.castRevealed))
		for k0, v0 := range e.castRevealed {
			var nv0 []state.ObjID
			nv0 = append([]state.ObjID(nil), v0...)
			c.castRevealed[k0] = nv0
		}
	}
	if e.fuseTargets != nil {
		c.fuseTargets = make(map[state.ObjID][][]state.Target, len(e.fuseTargets))
		for k0, v0 := range e.fuseTargets {
			var nv0 [][]state.Target
			if v0 != nil {
				nv0 = make([][]state.Target, len(v0))
				for i1 := range v0 {
					nv0[i1] = append([]state.Target(nil), v0[i1]...)
				}
			}
			c.fuseTargets[k0] = nv0
		}
	}
	if e.copyTargetStage != nil {
		c.copyTargetStage = make(map[state.ObjID]int, len(e.copyTargetStage))
		for k0, v0 := range e.copyTargetStage {
			c.copyTargetStage[k0] = v0
		}
	}
	if e.copyAnswerTargets != nil {
		c.copyAnswerTargets = make(map[state.ObjID][][]decision.Option, len(e.copyAnswerTargets))
		for k0, v0 := range e.copyAnswerTargets {
			var nv0 [][]decision.Option
			if v0 != nil {
				nv0 = make([][]decision.Option, len(v0))
				for i1 := range v0 {
					nv0[i1] = append([]decision.Option(nil), v0[i1]...)
				}
			}
			c.copyAnswerTargets[k0] = nv0
		}
	}
	if e.castSubTargets != nil {
		c.castSubTargets = make(map[state.ObjID]map[string][]state.Target, len(e.castSubTargets))
		for k0, v0 := range e.castSubTargets {
			var nv0 map[string][]state.Target
			if v0 != nil {
				nv0 = make(map[string][]state.Target, len(v0))
				for k1, v1 := range v0 {
					var nv1 []state.Target
					nv1 = append([]state.Target(nil), v1...)
					nv0[k1] = nv1
				}
			}
			c.castSubTargets[k0] = nv0
		}
	}
	if e.resolutionTargets != nil {
		c.resolutionTargets = make(resolutionTargetMap, len(e.resolutionTargets))
		for k0, v0 := range e.resolutionTargets {
			var nv0 resolutionTargetSet
			nv0 = v0
			nv0.flat = append([]state.Target(nil), v0.flat...)
			if v0.modes != nil {
				nv0.modes = make([][]state.Target, len(v0.modes))
				for i1 := range v0.modes {
					nv0.modes[i1] = append([]state.Target(nil), v0.modes[i1]...)
				}
			}
			c.resolutionTargets[k0] = nv0
		}
	}
	if e.charmTargets != nil {
		c.charmTargets = make(map[state.ObjID][][]state.Target, len(e.charmTargets))
		for k0, v0 := range e.charmTargets {
			var nv0 [][]state.Target
			if v0 != nil {
				nv0 = make([][]state.Target, len(v0))
				for i1 := range v0 {
					nv0[i1] = append([]state.Target(nil), v0[i1]...)
				}
			}
			c.charmTargets[k0] = nv0
		}
	}
}

func cloneFieldsEngineResolution(c, e *Engine, remap *cloneRemap) {
	if e.resolvingTargetControllerLKI != nil {
		c.resolvingTargetControllerLKI = make(map[state.ObjID]state.PlayerID, len(e.resolvingTargetControllerLKI))
		for k0, v0 := range e.resolvingTargetControllerLKI {
			c.resolvingTargetControllerLKI[k0] = v0
		}
	}
	if e.exploitedLKI != nil {
		c.exploitedLKI = make(map[state.ObjID]state.SacrificedInfo, len(e.exploitedLKI))
		for k0, v0 := range e.exploitedLKI {
			c.exploitedLKI[k0] = v0
		}
	}
	if e.sourceLifelinkLKI != nil {
		c.sourceLifelinkLKI = make(map[state.ObjID]bool, len(e.sourceLifelinkLKI))
		for k0, v0 := range e.sourceLifelinkLKI {
			c.sourceLifelinkLKI[k0] = v0
		}
	}
	if e.sourceControllerLKI != nil {
		c.sourceControllerLKI = make(map[state.ObjID]state.PlayerID, len(e.sourceControllerLKI))
		for k0, v0 := range e.sourceControllerLKI {
			c.sourceControllerLKI[k0] = v0
		}
	}
	if e.sourceCharLKI != nil {
		c.sourceCharLKI = make(map[state.ObjID]sourceCharSnapshot, len(e.sourceCharLKI))
		for k0, v0 := range e.sourceCharLKI {
			var nv0 sourceCharSnapshot
			nv0 = v0
			nv0.counters = append([]state.Counter(nil), v0.counters...)
			c.sourceCharLKI[k0] = nv0
		}
	}
	if e.damageSourceLKI != nil {
		c.damageSourceLKI = make(map[state.ObjID]map[state.ObjID]effects.DamageSourceLKI, len(e.damageSourceLKI))
		for k0, v0 := range e.damageSourceLKI {
			var nv0 map[state.ObjID]effects.DamageSourceLKI
			if v0 != nil {
				nv0 = make(map[state.ObjID]effects.DamageSourceLKI, len(v0))
				for k1, v1 := range v0 {
					nv0[k1] = v1
				}
			}
			c.damageSourceLKI[k0] = nv0
		}
	}
}

func cloneFieldsEngineDrain(c, e *Engine, remap *cloneRemap) {
	c.orderedTriggers = e.orderedTriggers
	c.applyingReplacement = e.applyingReplacement
}

func cloneFieldsEngineTokenMint(c, e *Engine, remap *cloneRemap) {
	c.mintParkFrom = e.mintParkFrom
	c.mintParkElection = e.mintParkElection
	if e.mintSinks != nil {
		c.mintSinks = make([]mintSink, len(e.mintSinks))
		for i0 := range e.mintSinks {
			c.mintSinks[i0] = e.mintSinks[i0]
			c.mintSinks[i0].ids = append([]state.ObjID(nil), e.mintSinks[i0].ids...)
		}
	}
	c.mintSinkSeq = e.mintSinkSeq
	c.tokenMintSinkID = e.tokenMintSinkID
	c.pendingMintSink = e.pendingMintSink
	c.copyMintsPending = append([]state.ObjID(nil), e.copyMintsPending...)
}

func cloneFieldsEngineTriggerBatches(c, e *Engine, remap *cloneRemap) {
	if e.triggerFireCount != nil {
		c.triggerFireCount = make(map[triggerKey]int32, len(e.triggerFireCount))
		for k0, v0 := range e.triggerFireCount {
			c.triggerFireCount[k0] = v0
		}
	}
	if e.unblockedOnceFired != nil {
		c.unblockedOnceFired = make(map[triggerKey]combatFires, len(e.unblockedOnceFired))
		for k0, v0 := range e.unblockedOnceFired {
			c.unblockedOnceFired[k0] = v0
		}
	}
	c.unblockedRoundChecked = e.unblockedRoundChecked
	if e.attackersDeclaredFired != nil {
		c.attackersDeclaredFired = make(map[triggerKey]combatFires, len(e.attackersDeclaredFired))
		for k0, v0 := range e.attackersDeclaredFired {
			c.attackersDeclaredFired[k0] = v0
		}
	}
	if e.damageBatchOpen {
		c.damageBatchOpen = e.damageBatchOpen
		c.damageBatchDepth = e.damageBatchDepth
		if e.damageBatchIdx != nil {
			c.damageBatchIdx = make(map[damageBatchKey]int, len(e.damageBatchIdx))
			for k0, v0 := range e.damageBatchIdx {
				c.damageBatchIdx[k0] = v0
			}
		}
		if e.damageBatchLog != nil {
			c.damageBatchLog = make([]damageBatchEntry, len(e.damageBatchLog))
			for i0 := range e.damageBatchLog {
				c.damageBatchLog[i0] = e.damageBatchLog[i0]
				c.damageBatchLog[i0].sources = append([]state.ObjID(nil), e.damageBatchLog[i0].sources...)
				c.damageBatchLog[i0].targets = append([]state.Target(nil), e.damageBatchLog[i0].targets...)
			}
		}
	}
	if e.zoneBatchOpen {
		c.zoneBatchOpen = e.zoneBatchOpen
		c.zoneBatchDepth = e.zoneBatchDepth
		if e.zoneBatchIdx != nil {
			c.zoneBatchIdx = make(map[zoneBatchKey]int, len(e.zoneBatchIdx))
			for k0, v0 := range e.zoneBatchIdx {
				c.zoneBatchIdx[k0] = v0
			}
		}
		if e.zoneBatchLog != nil {
			c.zoneBatchLog = make([]zoneBatchEntry, len(e.zoneBatchLog))
			for i0 := range e.zoneBatchLog {
				c.zoneBatchLog[i0] = e.zoneBatchLog[i0]
				c.zoneBatchLog[i0].moved = append([]state.Target(nil), e.zoneBatchLog[i0].moved...)
			}
		}
	}
	if e.discardBatchOpen {
		c.discardBatchOpen = e.discardBatchOpen
		c.discardBatchDepth = e.discardBatchDepth
		if e.discardBatchIdx != nil {
			c.discardBatchIdx = make(map[triggerKey]int, len(e.discardBatchIdx))
			for k0, v0 := range e.discardBatchIdx {
				c.discardBatchIdx[k0] = v0
			}
		}
		if e.discardBatchLog != nil {
			c.discardBatchLog = make([]discardBatchEntry, len(e.discardBatchLog))
			for i0 := range e.discardBatchLog {
				c.discardBatchLog[i0] = e.discardBatchLog[i0]
				c.discardBatchLog[i0].discarded = append([]state.Target(nil), e.discardBatchLog[i0].discarded...)
			}
		}
	}
	if e.discardAllTurn != nil {
		c.discardAllTurn = make(map[triggerKey]int32, len(e.discardAllTurn))
		for k0, v0 := range e.discardAllTurn {
			c.discardAllTurn[k0] = v0
		}
	}
	if e.phaseUnknownNoted != nil {
		c.phaseUnknownNoted = make(map[string]bool, len(e.phaseUnknownNoted))
		for k0, v0 := range e.phaseUnknownNoted {
			c.phaseUnknownNoted[k0] = v0
		}
	}
	if e.disableTriggersNoted != nil {
		c.disableTriggersNoted = make(map[string]bool, len(e.disableTriggersNoted))
		for k0, v0 := range e.disableTriggersNoted {
			c.disableTriggersNoted[k0] = v0
		}
	}
	if e.tappedTurn != nil {
		c.tappedTurn = make(map[state.ObjID]int32, len(e.tappedTurn))
		for k0, v0 := range e.tappedTurn {
			c.tappedTurn[k0] = v0
		}
	}
	if e.triggerTurnFires != nil {
		c.triggerTurnFires = make(map[triggerKey]turnFires, len(e.triggerTurnFires))
		for k0, v0 := range e.triggerTurnFires {
			c.triggerTurnFires[k0] = v0
		}
	}
	if e.triggerGameFires != nil {
		c.triggerGameFires = make(map[triggerKey]gameFires, len(e.triggerGameFires))
		for k0, v0 := range e.triggerGameFires {
			c.triggerGameFires[k0] = v0
		}
	}
	if e.triggerTurnResolved != nil {
		c.triggerTurnResolved = make(map[state.ObjID]turnFires, len(e.triggerTurnResolved))
		for k0, v0 := range e.triggerTurnResolved {
			c.triggerTurnResolved[k0] = v0
		}
	}
	if e.triggerTurnDice != nil {
		c.triggerTurnDice = make(map[triggerKey]turnFires, len(e.triggerTurnDice))
		for k0, v0 := range e.triggerTurnDice {
			c.triggerTurnDice[k0] = v0
		}
	}
	c.triggerTurnDiceTurn = e.triggerTurnDiceTurn
}

func cloneFieldsEngineContinuation(c, e *Engine, remap *cloneRemap) {
	c.choosing = e.choosing
	c.oppSel = e.oppSel
	if e.oppPicksMid != nil {
		c.oppPicksMid = make(map[string]state.PlayerID, len(e.oppPicksMid))
		for k0, v0 := range e.oppPicksMid {
			c.oppPicksMid[k0] = v0
		}
	}
	if e.tpCtlChooser != nil {
		c.tpCtlChooser = make(map[state.ObjID]tpCtlAnswer, len(e.tpCtlChooser))
		for k0, v0 := range e.tpCtlChooser {
			c.tpCtlChooser[k0] = v0
		}
	}
	if e.turnUp != nil {
		p0 := *e.turnUp
		p0.cost = cloneCost(e.turnUp.cost)
		p0.mods.raises = append([]int32(nil), e.turnUp.mods.raises...)
		p0.mods.extra = cloneCost(e.turnUp.mods.extra)
		p0.mods.reduces = append([]costMod(nil), e.turnUp.mods.reduces...)
		p0.sacs = append([]state.ObjID(nil), e.turnUp.sacs...)
		p0.discs = append([]state.ObjID(nil), e.turnUp.discs...)
		p0.reveal = append([]state.ObjID(nil), e.turnUp.reveal...)
		p0.returns = append([]state.ObjID(nil), e.turnUp.returns...)
		c.turnUp = &p0
	}
	if e.etbMove != nil {
		p0 := *e.etbMove
		p0.IDs = append([]state.ObjID(nil), e.etbMove.IDs...)
		p0.Pairs = append([][2]state.ObjID(nil), e.etbMove.Pairs...)
		c.etbMove = &p0
	}
	c.etbNext = e.etbNext
	c.auraEntry = e.auraEntry
	c.etbLandPlay = e.etbLandPlay
	c.etbLandObj = e.etbLandObj
	c.etbLandPlayer = e.etbLandPlayer
	if e.riotMove != nil {
		p0 := *e.riotMove
		p0.IDs = append([]state.ObjID(nil), e.riotMove.IDs...)
		p0.Pairs = append([][2]state.ObjID(nil), e.riotMove.Pairs...)
		c.riotMove = &p0
	}
	if e.unleashMove != nil {
		p0 := *e.unleashMove
		p0.IDs = append([]state.ObjID(nil), e.unleashMove.IDs...)
		p0.Pairs = append([][2]state.ObjID(nil), e.unleashMove.Pairs...)
		c.unleashMove = &p0
	}
	if e.siegeMove != nil {
		p0 := *e.siegeMove
		p0.IDs = append([]state.ObjID(nil), e.siegeMove.IDs...)
		p0.Pairs = append([][2]state.ObjID(nil), e.siegeMove.Pairs...)
		c.siegeMove = &p0
	}
	if e.entryStageDone != nil {
		p0 := *e.entryStageDone
		p0.grants = append([]entryGrant(nil), e.entryStageDone.grants...)
		p0.placed = append([]events.EntryCounterGrant(nil), e.entryStageDone.placed...)
		if e.entryStageDone.cands != nil {
			p0.cands = make([]replMatch, len(e.entryStageDone.cands))
			for i1 := range e.entryStageDone.cands {
				p0.cands[i1] = e.entryStageDone.cands[i1]
				p0.cands[i1].remembered = append([]state.ObjID(nil), e.entryStageDone.cands[i1].remembered...)
				p0.cands[i1].rememberedPlayers = append([]state.PlayerID(nil), e.entryStageDone.cands[i1].rememberedPlayers...)
			}
		}
		if e.entryStageDone.applied != nil {
			p0.applied = make([]replMatch, len(e.entryStageDone.applied))
			for i1 := range e.entryStageDone.applied {
				p0.applied[i1] = e.entryStageDone.applied[i1]
				p0.applied[i1].remembered = append([]state.ObjID(nil), e.entryStageDone.applied[i1].remembered...)
				p0.applied[i1].rememberedPlayers = append([]state.PlayerID(nil), e.entryStageDone.applied[i1].rememberedPlayers...)
			}
		}
		p0.bodyIDs = append([]string(nil), e.entryStageDone.bodyIDs...)
		if e.entryStageDone.tokenPlan != nil {
			p1 := *e.entryStageDone.tokenPlan
			p1.plan = append([]tokenPlanMint(nil), e.entryStageDone.tokenPlan.plan...)
			p0.tokenPlan = &p1
		}
		c.entryStageDone = &p0
	}
	if e.attachedChoice != nil {
		p0 := *e.attachedChoice
		c.attachedChoice = &p0
	}
	c.attachedApplying = e.attachedApplying
	if e.tokenChoice != nil {
		p0 := *e.tokenChoice
		if e.tokenChoice.matches != nil {
			p0.matches = make([]replMatch, len(e.tokenChoice.matches))
			for i1 := range e.tokenChoice.matches {
				p0.matches[i1] = e.tokenChoice.matches[i1]
				p0.matches[i1].remembered = append([]state.ObjID(nil), e.tokenChoice.matches[i1].remembered...)
				p0.matches[i1].rememberedPlayers = append([]state.PlayerID(nil), e.tokenChoice.matches[i1].rememberedPlayers...)
			}
		}
		p0.plan = append([]tokenPlanMint(nil), e.tokenChoice.plan...)
		p0.match.remembered = append([]state.ObjID(nil), e.tokenChoice.match.remembered...)
		p0.match.rememberedPlayers = append([]state.PlayerID(nil), e.tokenChoice.match.rememberedPlayers...)
		c.tokenChoice = &p0
	}
}

func cloneFieldsEngineParked(c, e *Engine, remap *cloneRemap) {
	c.suspendedCasts = append([]state.ObjID(nil), e.suspendedCasts...)
	c.defeatedCasts = append([]state.ObjID(nil), e.defeatedCasts...)
	if e.manaActivation != nil {
		p0 := *e.manaActivation
		p0.abilities = append([]*cards.SA(nil), e.manaActivation.abilities...)
		p0.gained = append([]gainedManaRef(nil), e.manaActivation.gained...)
		c.manaActivation = &p0
	}
	if e.manaColorActivation != nil {
		p0 := *e.manaColorActivation
		p0.triggers = clonePendingTriggers(e.manaColorActivation.triggers)
		if e.manaColorActivation.trigger != nil {
			p1 := *e.manaColorActivation.trigger
			p1.sourceCharLKI.counters = append([]state.Counter(nil), e.manaColorActivation.trigger.sourceCharLKI.counters...)
			p1.Trigger = cloneTrigger(e.manaColorActivation.trigger.Trigger)
			if e.manaColorActivation.trigger.TriggerSVars != nil {
				p1.TriggerSVars = make(map[string]string, len(e.manaColorActivation.trigger.TriggerSVars))
				for k2, v2 := range e.manaColorActivation.trigger.TriggerSVars {
					p1.TriggerSVars[k2] = v2
				}
			}
			p1.Ctx = remap.unlessCtx(e.manaColorActivation.trigger.Ctx)
			p0.trigger = &p1
		}
		p0.sacs = append([]state.ObjID(nil), e.manaColorActivation.sacs...)
		c.manaColorActivation = &p0
	}
	if e.manaDiscardActivation != nil {
		p0 := *e.manaDiscardActivation
		p0.cost = cloneCost(e.manaDiscardActivation.cost)
		p0.sacs = append([]state.ObjID(nil), e.manaDiscardActivation.sacs...)
		p0.discards = append([]state.ObjID(nil), e.manaDiscardActivation.discards...)
		p0.exiles = append([]state.ObjID(nil), e.manaDiscardActivation.exiles...)
		p0.taps = append([]state.ObjID(nil), e.manaDiscardActivation.taps...)
		p0.subCounterPays = append([]subCounterPay(nil), e.manaDiscardActivation.subCounterPays...)
		p0.untaps = append([]state.ObjID(nil), e.manaDiscardActivation.untaps...)
		c.manaDiscardActivation = &p0
	}
	if e.manaUnlessActivation != nil {
		p0 := *e.manaUnlessActivation
		p0.triggers = clonePendingTriggers(e.manaUnlessActivation.triggers)
		p0.sacs = append([]state.ObjID(nil), e.manaUnlessActivation.sacs...)
		p0.payers = append([]state.PlayerID(nil), e.manaUnlessActivation.payers...)
		c.manaUnlessActivation = &p0
	}
	if e.manaAfterCost != nil {
		p0 := *e.manaAfterCost
		p0.triggers = clonePendingTriggers(e.manaAfterCost.triggers)
		p0.sacs = append([]state.ObjID(nil), e.manaAfterCost.sacs...)
		p0.untaps = append([]state.ObjID(nil), e.manaAfterCost.untaps...)
		c.manaAfterCost = &p0
	}
	if e.deferredAsks != nil {
		c.deferredAsks = make([]*decision.Decision, len(e.deferredAsks))
		for i0 := range e.deferredAsks {
			if e.deferredAsks[i0] != nil {
				c.deferredAsks[i0] = cloneDecision(e.deferredAsks[i0])
			}
		}
	}
	if e.unlessPayment != nil {
		p0 := *e.unlessPayment
		p0.cost = cloneCost(e.unlessPayment.cost)
		p0.ctx = remap.unlessCtx(e.unlessPayment.ctx)
		p0.sacs = append([]state.ObjID(nil), e.unlessPayment.sacs...)
		p0.discards = append([]state.ObjID(nil), e.unlessPayment.discards...)
		p0.reveals = append([]state.ObjID(nil), e.unlessPayment.reveals...)
		p0.beholds = append([]state.ObjID(nil), e.unlessPayment.beholds...)
		p0.returns = append([]state.ObjID(nil), e.unlessPayment.returns...)
		p0.exiles = append([]state.ObjID(nil), e.unlessPayment.exiles...)
		c.unlessPayment = &p0
	}
	if e.cumulative != nil {
		p0 := *e.cumulative
		p0.amount = cloneCost(e.cumulative.amount)
		if e.cumulative.action != nil {
			p1 := *e.cumulative.action
			p0.action = &p1
		}
		c.cumulative = &p0
	}
	if e.triggerCost != nil {
		p0 := *e.triggerCost
		p0.resume = remap.resume(e.triggerCost.resume)
		p0.amount = cloneCost(e.triggerCost.amount)
		p0.sacs = append([]state.ObjID(nil), e.triggerCost.sacs...)
		p0.exiles = append([]state.ObjID(nil), e.triggerCost.exiles...)
		p0.discards = append([]state.ObjID(nil), e.triggerCost.discards...)
		p0.moveGraves = append([]state.ObjID(nil), e.triggerCost.moveGraves...)
		c.triggerCost = &p0
	}
	if e.echo != nil {
		p0 := *e.echo
		p0.amount = cloneCost(e.echo.amount)
		if e.echo.action != nil {
			p1 := *e.echo.action
			p0.action = &p1
		}
		c.echo = &p0
	}
	if e.attackPay != nil {
		p0 := *e.attackPay
		p0.chosen = append([]decision.Option(nil), e.attackPay.chosen...)
		if e.attackPay.plan != nil {
			p1 := *e.attackPay.plan
			p1.charge.taps = append([]blockTapReq(nil), e.attackPay.plan.charge.taps...)
			p1.charge.sacs = append([]chargeObjReq(nil), e.attackPay.plan.charge.sacs...)
			p1.charge.returns = append([]chargeObjReq(nil), e.attackPay.plan.charge.returns...)
			p1.charge.phyrexian = append([]uint8(nil), e.attackPay.plan.charge.phyrexian...)
			p1.taps = append([]state.ObjID(nil), e.attackPay.plan.taps...)
			p1.sacs = append([]state.ObjID(nil), e.attackPay.plan.sacs...)
			p1.returns = append([]state.ObjID(nil), e.attackPay.plan.returns...)
			p0.plan = &p1
		}
		p0.sources = append([]attackManaSource(nil), e.attackPay.sources...)
		c.attackPay = &p0
	}
	if e.blockPay != nil {
		p0 := *e.blockPay
		p0.chosen = append([]decision.Option(nil), e.blockPay.chosen...)
		if e.blockPay.plan != nil {
			p1 := *e.blockPay.plan
			p1.charge.taps = append([]blockTapReq(nil), e.blockPay.plan.charge.taps...)
			p1.charge.sacs = append([]chargeObjReq(nil), e.blockPay.plan.charge.sacs...)
			p1.charge.returns = append([]chargeObjReq(nil), e.blockPay.plan.charge.returns...)
			p1.charge.phyrexian = append([]uint8(nil), e.blockPay.plan.charge.phyrexian...)
			p1.taps = append([]state.ObjID(nil), e.blockPay.plan.taps...)
			p1.sacs = append([]state.ObjID(nil), e.blockPay.plan.sacs...)
			p1.returns = append([]state.ObjID(nil), e.blockPay.plan.returns...)
			p0.plan = &p1
		}
		p0.sources = append([]attackManaSource(nil), e.blockPay.sources...)
		c.blockPay = &p0
	}
	c.cmdZone = append([]cmdZoneMove(nil), e.cmdZone...)
	if e.legendBatch != nil {
		p0 := *e.legendBatch
		p0.group.ids = append([]state.ObjID(nil), e.legendBatch.group.ids...)
		p0.dead = append([]casualty(nil), e.legendBatch.dead...)
		c.legendBatch = &p0
	}
}

func cloneFieldsEngineParked2(c, e *Engine, remap *cloneRemap) {
	if e.replChoices != nil {
		c.replChoices = make([]replChoice, len(e.replChoices))
		for i0 := range e.replChoices {
			c.replChoices[i0] = e.replChoices[i0]
			if e.replChoices[i0].cands != nil {
				c.replChoices[i0].cands = make([]replMatch, len(e.replChoices[i0].cands))
				for i1 := range e.replChoices[i0].cands {
					c.replChoices[i0].cands[i1] = e.replChoices[i0].cands[i1]
					c.replChoices[i0].cands[i1].remembered = append([]state.ObjID(nil), e.replChoices[i0].cands[i1].remembered...)
					c.replChoices[i0].cands[i1].rememberedPlayers = append([]state.PlayerID(nil), e.replChoices[i0].cands[i1].rememberedPlayers...)
				}
			}
			c.replChoices[i0].applied = append([]bool(nil), e.replChoices[i0].applied...)
			c.replChoices[i0].applicable = append([]int(nil), e.replChoices[i0].applicable...)
			if e.replChoices[i0].untap != nil {
				p1 := *e.replChoices[i0].untap
				c.replChoices[i0].untap = &p1
			}
			c.replChoices[i0].exchange = remap.lifeExchange(e.replChoices[i0].exchange)
			if e.replChoices[i0].appliedRepls != nil {
				c.replChoices[i0].appliedRepls = make([]replMatch, len(e.replChoices[i0].appliedRepls))
				for i1 := range e.replChoices[i0].appliedRepls {
					c.replChoices[i0].appliedRepls[i1] = e.replChoices[i0].appliedRepls[i1]
					c.replChoices[i0].appliedRepls[i1].remembered = append([]state.ObjID(nil), e.replChoices[i0].appliedRepls[i1].remembered...)
					c.replChoices[i0].appliedRepls[i1].rememberedPlayers = append([]state.PlayerID(nil), e.replChoices[i0].appliedRepls[i1].rememberedPlayers...)
				}
			}
			if e.replChoices[i0].used != nil {
				c.replChoices[i0].used = make([]replMatch, len(e.replChoices[i0].used))
				for i1 := range e.replChoices[i0].used {
					c.replChoices[i0].used[i1] = e.replChoices[i0].used[i1]
					c.replChoices[i0].used[i1].remembered = append([]state.ObjID(nil), e.replChoices[i0].used[i1].remembered...)
					c.replChoices[i0].used[i1].rememberedPlayers = append([]state.PlayerID(nil), e.replChoices[i0].used[i1].rememberedPlayers...)
				}
			}
			c.replChoices[i0].tokenPlan = append([]tokenPlanMint(nil), e.replChoices[i0].tokenPlan...)
			c.replChoices[i0].absorbed = append([]string(nil), e.replChoices[i0].absorbed...)
			if e.replChoices[i0].stage != nil {
				p1 := *e.replChoices[i0].stage
				p1.grants = append([]entryGrant(nil), e.replChoices[i0].stage.grants...)
				p1.placed = append([]events.EntryCounterGrant(nil), e.replChoices[i0].stage.placed...)
				if e.replChoices[i0].stage.cands != nil {
					p1.cands = make([]replMatch, len(e.replChoices[i0].stage.cands))
					for i2 := range e.replChoices[i0].stage.cands {
						p1.cands[i2] = e.replChoices[i0].stage.cands[i2]
						p1.cands[i2].remembered = append([]state.ObjID(nil), e.replChoices[i0].stage.cands[i2].remembered...)
						p1.cands[i2].rememberedPlayers = append([]state.PlayerID(nil), e.replChoices[i0].stage.cands[i2].rememberedPlayers...)
					}
				}
				if e.replChoices[i0].stage.applied != nil {
					p1.applied = make([]replMatch, len(e.replChoices[i0].stage.applied))
					for i2 := range e.replChoices[i0].stage.applied {
						p1.applied[i2] = e.replChoices[i0].stage.applied[i2]
						p1.applied[i2].remembered = append([]state.ObjID(nil), e.replChoices[i0].stage.applied[i2].remembered...)
						p1.applied[i2].rememberedPlayers = append([]state.PlayerID(nil), e.replChoices[i0].stage.applied[i2].rememberedPlayers...)
					}
				}
				p1.bodyIDs = append([]string(nil), e.replChoices[i0].stage.bodyIDs...)
				if e.replChoices[i0].stage.tokenPlan != nil {
					p2 := *e.replChoices[i0].stage.tokenPlan
					p2.plan = append([]tokenPlanMint(nil), e.replChoices[i0].stage.tokenPlan.plan...)
					p1.tokenPlan = &p2
				}
				c.replChoices[i0].stage = &p1
			}
			c.replChoices[i0].resumeAtPose = remap.resume(e.replChoices[i0].resumeAtPose)
		}
	}
}

func cloneFieldsEngineCastWindows(c, e *Engine, remap *cloneRemap) {
	if e.untapResume != nil {
		p0 := *e.untapResume
		c.untapResume = &p0
	}
	c.untapChoiceObj = e.untapChoiceObj
	c.madnessChoices = append([]events.Event(nil), e.madnessChoices...)
	c.madnessSuspended = e.madnessSuspended
	if e.suppressedCast != nil {
		c.suppressedCast = make(map[state.ObjID]bool, len(e.suppressedCast))
		for k0, v0 := range e.suppressedCast {
			c.suppressedCast[k0] = v0
		}
	}
	if e.castAborts != nil {
		c.castAborts = make(map[state.ObjID]int32, len(e.castAborts))
		for k0, v0 := range e.castAborts {
			c.castAborts[k0] = v0
		}
	}
	if e.inertHeldOut != nil {
		c.inertHeldOut = make(map[inertKey]bool, len(e.inertHeldOut))
		for k0, v0 := range e.inertHeldOut {
			c.inertHeldOut[k0] = v0
		}
	}
	c.drainAwaitsTarget = e.drainAwaitsTarget
	c.drainAwaitsModes = e.drainAwaitsModes
	c.deferCastTrigger = e.deferCastTrigger
	c.manaExpended = append([]int32(nil), e.manaExpended...)
	c.manaExpendedTurn = e.manaExpendedTurn
}

// resumeFields deepens the reference fields of the resume frame cp, a value
// copy of rp.
func (remap *cloneRemap) resumeFields(cp, rp *resumePoint) {
}
