package rules

// setAuditTMTNames returns the card names of the TMT set under audit.
func setAuditTMTNames() []string {
	return []string{
		"Action News Crew",
		"Agent Bishop, Man in Black",
		"April O'Neil, Kunoichi Trainee",
		"Dimensional Exile",
		"East Wind Avatar",
		"Featherbrained Filcher",
		"Grounded for Life",
		"Hamato Guardian Stance",
		"High-Flying Ace",
		"Jennika, Bad Apple Big Sister",
		"Koya, Death from Above",
		"The Last Ronin's Technique",
		"Leader's Talent",
		"Leonardo, Big Brother",
		"Leonardo, Cutting Edge",
		"Leonardo, Leader in Blue",
		"Leonardo, Sewer Samurai",
		"Leonardo's Technique",
		"Lita, Little Orphan Amphibian",
		"Make Your Move",
		"Mighty Mutanimals",
		"Prehistoric Pet",
		"Quintessential Katana",
		"Sally Pride, Lioness Leader",
		"Triceraton Commander",
		"Turncoat Kunoichi",
		"Turtles Forever",
		"Uneasy Alliance",
		"April O'Neil, Hacktivist",
		"April, Reporter of the Weird",
		"Bespoke B\u014d",
		"Buzz Bots",
		"Crustacean Commando",
		"Does Machines",
		"Donatello, Gadget Master",
		"Donatello, Mutant Mechanic",
		"Donatello, Turtle Techie",
		"Donatello, Way with Machines",
		"Donatello's Technique",
		"Fugitive Droid",
		"Kitsune, Dragon's Daughter",
		"Kitsune's Technique",
		"Krang, Master Mind",
		"Metalhead",
		"Mind Transfer Protocol",
		"Mondo Gecko",
		"Negate",
		"Ooze Spill",
		"Ray Fillet, Man Ray",
		"Renet, Temporal Apprentice",
		"Retro-Mutation",
		"Return to the Sewers",
		"Sewer-veillance Cam",
		"Stockman, Mad Fly-entist",
		"Turtles in Time",
		"Utrom Scientists",
		"Anchovy & Banana Pizza",
		"Armaggon, Future Shark",
		"Bebop, Warthog Warrior",
		"The Cloning of Shredder",
		"Death in the Family",
		"Dream Beavers",
		"Foot Mystic",
		"Insectoid Exterminator",
		"Lord Dregg, Insect Invader",
		"Madame Null, Power Broker",
		"Ninja Teen",
		"Oroku Saki, Shredder Rising",
		"Pain 101",
		"Paramecia Coloniex",
		"Rat King, Verminister",
		"Savanti Romero, Time's Exile",
		"Shark Shredder, Killer Clone",
		"Shredder, Unrelenting",
		"Shredder's Armor",
		"Shredder's Revenge",
		"Shredder's Technique",
		"South Wind Avatar",
		"Splinter, Hamato Yoshi",
		"Splinter's Technique",
		"Squirrelanoids",
		"Stomped by the Foot",
		"Super Shredder",
		"Tunnel Rats",
		"Bot Bashing Time",
		"Broadcast Takeover",
		"Casey Jones, Jury-Rig Justiciar",
		"Casey Jones, Vigilante",
		"Cool but Rude",
		"General Traag, Heart of Stone",
		"Hard-Won Jitte",
		"Improvised Arsenal",
		"Jennika's Technique",
		"Manhole Missile",
		"Mouser Attack!",
		"Mouser Foundry",
		"Mutant Town Musicians",
		"Null Group Biological Assets",
		"Old Hob, Alleycat Blues",
		"Purple Dragon Punks",
		"Raphael, Most Attitude",
		"Raphael, Ninja Destroyer",
		"Raphael, the Nightwatcher",
		"Raphael, Tough Turtle",
		"Raphael's Technique",
		"Ravenous Robots",
		"Rock Soldiers",
		"Slash, Reptile Rampager",
		"Spicy Oatmeal Pizza",
		"Wingnut, Bat on the Belfry",
		"Zog, Triceraton Castaway",
		"Courier of Comestibles",
		"Cowabunga!",
		"Frog Butler",
		"Groundchuck & Dirtbag",
		"Guac & Marshmallow Pizza",
		"Leatherhead, Swamp Stalker",
		"Michelangelo, Game Master",
		"Michelangelo, Improviser",
		"Michelangelo, Mutant BFF",
		"Michelangelo, Weirdness to 11",
		"Michelangelo's Technique",
		"Mona Lisa, Science Geek",
		"Mutagen Man, Living Ooze",
		"Mutant Chain Reaction",
		"New Generation's Technique",
		"Novel Nunchaku",
		"Party Dude",
		"Primordial Pachyderm",
		"Ragamuffin Raptor",
		"Rocksteady, Crash Courser",
		"Saved by the Shell",
		"Tenderize",
		"Transdimensional Bovine",
		"Turtle Power!",
		"Venus, Torn Between Worlds",
		"West Wind Avatar",
		"Zoo Escapees",
		"Baxter Stockman",
		"Bebop & Rocksteady",
		"Brilliance Unleashed",
		"Dark Leo & Shredder",
		"Don & Leo, Problem Solvers",
		"Don & Raph, Hard Science",
		"EPF Point Squad",
		"Foot Elite",
		"Foot Ninjas",
		"Genghis Frog",
		"Go Ninja Go",
		"Ice Cream Kitty",
		"Karai, Future of the Foot",
		"Karai's Technique",
		"Krang & Shredder",
		"The Last Ronin",
		"Lessons from Life",
		"Mechanized Ninja Cavalry",
		"Mikey & Don, Party Planners",
		"Mikey & Leo, Chaos & Order",
		"Mouser Mark III",
		"The Neutrinos",
		"Nobody",
		"North Wind Avatar",
		"Pizza Face, Gastromancer",
		"Punk Frogs",
		"Putrid Pals",
		"Raph & Leo, Sibling Rivals",
		"Raph & Mikey, Troublemakers",
		"Slithering Cryptid",
		"Splinter, Radical Rat",
		"Tainted Treats",
		"Tokka & Rahzar, Terrible Twos",
		"Chrome Dome",
		"Everything Pizza",
		"Henchbots",
		"Krang, Utrom Warlord",
		"Omni-Cheese Pizza",
		"The Ooze",
		"Skateboard",
		"Technodrome",
		"Turtle Blimp",
		"Turtle Van",
		"Weather Maker",
		"Dimension X",
		"Escape Tunnel",
		"Foot Headquarters",
		"Illegitimate Business",
		"Mutant Town",
		"Northampton Farm",
		"TCRI Building",
		"Turtle Lair",
		"Plains",
		"Island",
		"Swamp",
		"Mountain",
		"Forest",
	}
}
